// antonimos.js

/**
 * @file Dicionário de antônimos em Português do Brasil.
 * Contém mapeamentos de palavras para suas palavras antônimas correspondentes.
 * Esta lista é uma amostra expandida e pode ser aprimorada com mais termos e nuances.
 * @author [Seu Nome ou Nome da Organização]
 * @version 1.0.0
 */

/**
 * Objeto que mapeia palavras (chaves) para um array de seus antônimos (valores).
 * @type {Object<string, string[]>}
 */
const ANTONIMOS_DATA = {
    // Adjetivos comuns
    "bom": ["ruim", "mau", "péssimo", "detestável"],
    "grande": ["pequeno", "minúsculo", "diminuto", "reduzido"],
    "feliz": ["triste", "infeliz", "melancólico", "desanimado"],
    "rápido": ["lento", "devagar", "demorado", "vagoroso"],
    "claro": ["escuro", "obscuro", "sombrio", "turvo", "nebuloso"],
    "alto": ["baixo", "raso", "curto"],
    "novo": ["velho", "antigo", "obsoleto", "arcaico"],
    "bonito": ["feio", "horrível", "desagradável"],
    "forte": ["fraco", "débil", "frágil"],
    "quente": ["frio", "gelado", "gélido"],
    "cheio": ["vazio", "oco", "desocupado"],
    "pesado": ["leve", "delicado"],
    "largo": ["estreito", "apertado"],
    "fácil": ["difícil", "complicado", "árduo"],
    "rico": ["pobre", "miserável", "desprovido"],
    "limpo": ["sujo", "imundo", "maculado"],
    "doce": ["amargo", "azedo", "salgado"],
    "duro": ["mole", "macio", "brando"],
    "aberto": ["fechado", "cerrado", "vedado"],
    "curto": ["longo", "comprido", "extenso"],
    "calmo": ["agitado", "nervoso", "inquieto"],
    "gordo": ["magro", "esbelto", "fino"],
    "alegre": ["triste", "desanimado", "sombrio"],
    "sincero": ["mentiroso", "falso", "dissimulado"],
    "verdadeiro": ["falso", "irreal", "mentiroso"],
    "corajoso": ["covarde", "medroso", "pusilânime"],
    "silencioso": ["barulhento", "ruidoso"],
    "inteligente": ["burro", "ignorante", "tolo"],
    "justo": ["injusto", "parcial", "tendencioso"],
    "esperto": ["ingênuo", "bobo", "tolo"],
    "delicioso": ["horrível", "nojento", "desagradável"],
    "legal": ["ilegal", "chato", "ilegitimo"],
    "ativo": ["inativo", "passivo", "ocioso"],
    "generoso": ["egoísta", "mesquinho", "avarento"],
    "prudente": ["imprudente", "descuidado", "temerário"],
    "amigável": ["hostil", "antipático", "inimigo"],
    "útil": ["inútil", "dispensável", "supérfluo"],
    "presente": ["ausente", "faltoso"],
    "possível": ["impossível", "improvável"],
    "completo": ["incompleto", "parcial", "deficiente"],
    "correto": ["incorreto", "errado", "equivocado"],
    "visível": ["invisível", "oculto", "escondido"],
    "direto": ["indireto", "tortuoso"],
    "fraco": ["forte", "resistente", "robusto"],
    "rico": ["pobre", "carente"],
    "certo": ["errado", "incerto", "duvidoso"],
    "liso": ["áspero", "rugoso"],
    "suave": ["áspero", "ríspido"],
    "macio": ["duro", "rígido"],
    "jovem": ["idoso", "ancião"],
    "veloz": ["lento", "moroso"],
    "doente": ["saudável", "sadio"],
    "sábio": ["ignorante", "néscio"],
    "comum": ["raro", "incomum"],
    "igual": ["diferente", "desigual"],
    "honesto": ["desonesto", "trapaceiro"],
    "fiel": ["infiel", "traidor"],
    "organizado": ["desorganizado", "caótico"],
    "disciplinado": ["indisciplinado", "rebelde"],
    "otimista": ["pessimista", "desesperançoso"],
    "ativo": ["inativo", "passivo"],
    "paciente": ["impaciente", "ansioso"],
    "capaz": ["incapaz", "inapto"],
    "limpo": ["sujo", "embaçado"],
    "molhado": ["seco", "enxuto"],
    "doce": ["amargo", "azedo"],
    "cruel": ["gentil", "bondoso"],
    "justo": ["injusto", "desonesto"],
    "simples": ["complexo", "complicado"],
    "generoso": ["mesquinho", "egoísta"],
    "ativo": ["passivo", "ocioso"],
    "comum": ["raro", "excepcional"],
    "presente": ["ausente", "passado"],
    "futuro": ["passado", "anterior"],
    "unido": ["separado", "dividido"],
    "abundante": ["escasso", "insuficiente"],
    "eficaz": ["ineficaz", "inoperante"],
    "responsável": ["irresponsável", "negligente"],
    "seguro": ["inseguro", "perigoso"],
    "visível": ["invisível", "oculto"],
    "racional": ["irracional", "ilógico"],
    "coerente": ["incoerente", "contraditório"],
    "legítimo": ["ilegítimo", "falso"],
    "válido": ["inválido", "nulo"],
    "puro": ["impuro", "contaminado"],
    "discreto": ["indiscreto", "chamativo"],
    "legal": ["ilegal", "proibido"],
    "tolerante": ["intolerante", "rígido"],
    "flexível": ["rígido", "inflexível"],
    "natural": ["artificial", "sintético"],
    "real": ["irreal", "fictício"],
    "específico": ["genérico", "geral"],
    "público": ["privado", "secreto"],
    "permanente": ["temporário", "transitório"],
    "fixo": ["móvel", "variável"],
    "interno": ["externo", "exterior"],
    "superior": ["inferior", "subordinado"],
    "principal": ["secundário", "subsidiário"],
    "primário": ["secundário", "terciário"],
    "essencial": ["dispensável", "supérfluo"],
    "necessário": ["desnecessário", "supérfluo"],
    "fundamental": ["dispensável", "acessório"],
    "importante": ["insignificante", "irrelevante"],
    "prioritário": ["secundário", "terciário"],
    "principal": ["subordinado", "acessório"],
    "central": ["periférico", "marginal"],
    "inicial": ["final", "conclusivo"],
    "anterior": ["posterior", "subsequente"],
    "passado": ["futuro", "presente"],
    "ativo": ["passivo", "ocioso"],
    "consciente": ["inconsciente", "desacordado"],
    "voluntário": ["involuntário", "forçado"],
    "direto": ["indireto", "oblíquo"],
    "provisório": ["definitivo", "permanente"],
    "constante": ["variável", "inconstante"],
    "estável": ["instável", "volátil"],
    "estático": ["dinâmico", "móvel"],
    "sólido": ["líquido", "gasoso", "fraco"],
    "cheio": ["vazio", "oco"],

    // Verbos comuns
    "amar": ["odiar", "detestar"],
    "aceitar": ["rejeitar", "recusar", "negar"],
    "abrir": ["fechar", "cerrar"],
    "acender": ["apagar", "desligar"],
    "subir": ["descer", "cair"],
    "começar": ["terminar", "acabar", "finalizar"],
    "comprar": ["vender", "alienar"],
    "dar": ["receber", "tirar", "recolher"],
    "entrar": ["sair", "partir"],
    "vir": ["ir", "partir"],
    "construir": ["destruir", "demolir", "desmantelar"],
    "unir": ["separar", "dividir"],
    "incluir": ["excluir", "retirar"],
    "permitir": ["proibir", "impedir"],
    "lembrar": ["esquecer", "olvidar"],
    "ganhar": ["perder", "derrotar"],
    "aparecer": ["desaparecer", "sumir"],
    "concordar": ["discordar", "divergir"],
    "aprovar": ["reprovar", "desaprovar"],
    "prender": ["soltar", "libertar"],
    "nascer": ["morrer", "falecer"],
    "rir": ["chorar", "lamentar"],
    "dormir": ["acordar", "despertar"],
    "encontrar": ["perder", "desencontrar"],
    "ensinar": ["aprender", "desaprender"],
    "apertar": ["afrouxar", "soltar"],
    "chover": ["estiar", "secar"],
    "conectar": ["desconectar", "separar"],
    "ligar": ["desligar", "interromper"],
    "acelerar": ["desacelerar", "frear"],
    "avançar": ["recuar", "retroceder"],
    "aceitar": ["recusar", "negar"],
    "admitir": ["negar", "demitir"],
    "aumentar": ["diminuir", "reduzir"],
    "colocar": ["retirar", "remover"],
    "chegar": ["partir", "sair"],
    "despertar": ["dormir", "adormecer"],
    "entrar": ["sair", "abandonar"],
    "existir": ["inexistir", "perecer"],
    "iniciar": ["interromper", "cessar"],
    "limpar": ["sujar", "emborcar"],
    "multiplicar": ["dividir", "subtrair"],
    "nascer": ["morrer", "findar"],
    "obedecer": ["desobedecer", "rebelar"],
    "partir": ["chegar", "retornar"],
    "receber": ["dar", "ceder"],
    "retornar": ["partir", "ir"],
    "segurar": ["soltar", "largar"],
    "subir": ["descer", "cair"],
    "unir": ["separar", "desligar"],
    "vencer": ["perder", "fracassar"],
    "virar": ["desvirar", "inverter"],

    // Substantivos comuns
    "dia": ["noite", "madrugada"],
    "início": ["fim", "término", "desfecho"],
    "entrada": ["saída", "partida"],
    "amor": ["ódio", "rancor", "aversão"],
    "paz": ["guerra", "conflito", "discórdia"],
    "vida": ["morte", "fim"],
    "verdade": ["mentira", "falsidade"],
    "alegria": ["tristeza", "melancolia", "desânimo"],
    "saúde": ["doença", "enfermidade"],
    "felicidade": ["infelicidade", "tristeza"],
    "luz": ["escuridão", "trevas"],
    "sorte": ["azar", "infortúnio"],
    "riqueza": ["pobreza", "miséria"],
    "coragem": ["covardia", "medo"],
    "vitória": ["derrota", "fracasso"],
    "bem": ["mal", "ruim"],
    "ganho": ["perda", "prejuízo"],
    "calor": ["frio", "friagem"],
    "silêncio": ["barulho", "ruído"],
    "justiça": ["injustiça", "desigualdade"],
    "liberdade": ["prisão", "escravidão", "opressão"],
    "conhecimento": ["ignorância", "desconhecimento"],
    "humildade": ["soberba", "arrogância"],
    "ordem": ["desordem", "caos"],
    "progresso": ["retrocesso", "regresso"],
    "esperança": ["desespero", "desesperança"],
    "confiança": ["desconfiança", "suspeita"],
    "beleza": ["feiura", "deformidade"],
    "sabedoria": ["ignorância", "insensatez"],
    "honestidade": ["desonestidade", "fraude"],
    "fidelidade": ["infidelidade", "traição"],
    "disciplina": ["indisciplina", "bagunça"],
    "otimismo": ["pessimismo", "desânimo"],
    "atividade": ["inatividade", "ociosidade"],
    "paciência": ["impaciência", "pressa"],
    "capacidade": ["incapacidade", "inaptidão"],
    "limpeza": ["sujeira", "imundície"],
    "doçura": ["amargura", "azedume"],
    "crueldade": ["gentileza", "bondade"],
    "simplicidade": ["complexidade", "complicação"],
    "generosidade": ["mesquinhez", "egoísmo"],
    "comum": ["raro", "excepcional"],
    "presença": ["ausência", "falta"],
    "unidade": ["separação", "divisão"],
    "abundância": ["escassez", "insuficiência"],
    "eficácia": ["ineficácia", "inoperância"],
    "responsabilidade": ["irresponsabilidade", "negligência"],
    "segurança": ["insegurança", "perigo"],
    "visibilidade": ["invisibilidade", "ocultação"],
    "racionalidade": ["irracionalidade", "ilógica"],
    "coerência": ["incoerência", "contradição"],
    "legitimidade": ["ilegitimidade", "falsidade"],
    "validade": ["invalidade", "nulidade"],
    "pureza": ["impureza", "contaminação"],
    "discrição": ["indiscrição", "chamariz"],
    "legalidade": ["ilegalidade", "proibição"],
    "tolerância": ["intolerância", "rigidez"],
    "flexibilidade": ["rigidez", "inflexibilidade"],
    "naturalidade": ["artificialidade", "sinteticidade"],
    "realidade": ["irrealidade", "ficção"],
    "especificidade": ["generalidade", "vagueza"],
    "público": ["privado", "secreto"],
    "permanência": ["transitoriedade", "efemeridade"],
    "fixidez": ["mobilidade", "variabilidade"],
    "interior": ["exterior", "externo"],
    "superioridade": ["inferioridade", "subordinação"],
    "principal": ["secundário", "subalterno"],
    "essencialidade": ["dispensabilidade", "supérfluo"],
    "necessidade": ["desnecessidade", "supérfluo"],
    "fundamentalidade": ["acessório", "secundário"],
    "importância": ["insignificância", "irrelevância"],
    "prioridade": ["secundaridade", "terciariedade"],
    "centralidade": ["periferia", "marginalidade"],
    "início": ["fim", "término"],
    "anterioridade": ["posterioridade", "sequência"],
    "passado": ["futuro", "presente"],
    "atividade": ["passividade", "ociosidade"],
    "consciência": ["inconsciência", "coma"],
    "voluntariedade": ["involuntariedade", "compulsão"],
    "direção": ["indireção", "desvio"],
    "provisoriedade": ["definitividade", "permanência"],
    "constância": ["inconstância", "variabilidade"],
    "estabilidade": ["instabilidade", "volatilidade"],
    "estática": ["dinâmica", "movimento"],
    "solidez": ["fragilidade", "liquidez"],

    // Advérbios
    "perto": ["longe", "distante", "afastado"],
    "dentro": ["fora", "exterior"],
    "agora": ["depois", "antes", "antigamente"],
    "aqui": ["lá", "ali", "acolá"],
    "sim": ["não", "jamais"],
    "sempre": ["nunca", "jamais"],
    "muito": ["pouco", "quase nada"],
    "acima": ["abaixo", "embaixo"],
    "adiante": ["atrás", "para trás"],
    "antes": ["depois", "após"],
    "bem": ["mal", "ruim"],
    "cedo": ["tarde", "tardiamente"],
    "rápido": ["lentamente", "devagar"],
    "junto": ["separado", "afastado"],
    "certo": ["errado", "incorretamente"],
    "claro": ["obscuramente", "escuro"],
    "diretamente": ["indiretamente", "obliquamente"],
    "frequentemente": ["raramente", "ocasionalmente"],
    "geralmente": ["especificamente", "raramente"],
    "hoje": ["ontem", "amanhã"],
    "imediatamente": ["lentamente", "tardiamente"],
    "inclusive": ["exclusive", "exceto"],
    "longe": ["perto", "próximo"],
    "mais": ["menos", "pouco"],
    "melhor": ["pior", "piores"],
    "naturalmente": ["artificialmente", "forçadamente"],
    "nunca": ["sempre", "eternamente"],
    "pouco": ["muito", "abundantemente"],
    "primeiro": ["último", "finalmente"],
    "rapidamente": ["lentamente", "vagorosamente"],
    "simplesmente": ["complicadamente", "elaboradamente"],
    "somente": ["também", "inclusive"],
    "suficientemente": ["insuficientemente", "pouco"],
    "tarde": ["cedo", "adiantado"],
    "totalmente": ["parcialmente", "incompletamente"],
    "verdadeiramente": ["falsamente", "enganosamente"],
    "visivelmente": ["invisivelmente", "ocultamente"],
    "certamente": ["incertamente", "duvidosamente"],
    "facilmente": ["dificilmente", "arduamente"],
    "livremente": ["prisioneiramente", "forçadamente"],
    "secretamente": ["publicamente", "abertamente"],
    "silenciosamente": ["ruidosamente", "barulhentamente"],
    "tranquilamente": ["agitadamente", "nervosamente"],
    "unidamente": ["separadamente", "divididamente"],
    "virtualmente": ["realmente", "fisicamente"],
    "voluntariamente": ["involuntariamente", "compulsoriamente"],
    "acidentalmente": ["intencionalmente", "propositadamente"],
    "ativamente": ["passivamente", "ociosamente"],
    "claramente": ["obscuramente", "indistintamente"],
    "cuidadosamente": ["descuidadamente", "negligentemente"],
    "definidamente": ["indefinidamente", "vagamene"],
    "direitamente": ["esquerdamente", "indiretamente"],
    "eficientemente": ["ineficientemente", "mal"],
    "fortemente": ["fracamente", "debilmente"],
    "honestamente": ["desonestamente", "trapaceiramente"],
    "infelizmente": ["felizmente", "sortudamente"],
    "legalmente": ["ilegalmente", "proibitivamente"],
    "negativamente": ["positivamente", "afirmativamente"],
    "pacientemente": ["impacientemente", "ansiosamente"],
    "permanentemente": ["temporariamente", "provisoriamente"],
    "praticamente": ["teoricamente", "impraticavelmente"],
    "realmente": ["irrealmente", "ficticiamente"],
    "seguramente": ["inseguramente", "perigosamente"],
    "seriamente": ["brincando", "levianamente"],
    "terrivelmente": ["maravilhosamente", "excelentemente"],
    "ultimamente": ["primeiramente", "anteriormente"],
    "utilmente": ["inutilmente", "desnecessariamente"],
    "vagarosamente": ["rapidamente", "pressurosamente"],
    "validamente": ["invalidamente", "ilegitimamente"],
    "violentamente": ["calmamente", "pacificamente"],
    "zelosamente": ["descuidadamente", "negligentemente"],

    // Outros
    "sim": ["não"],
    "para frente": ["para trás", "para trás"],
    "cima": ["baixo"],
    "frente": ["trás", "costas"],
    "dentro": ["fora"],
    "antes": ["depois"],
    "primeiro": ["último"],
    "começo": ["fim"],
    "norte": ["sul"],
    "leste": ["oeste"],
    "positivo": ["negativo"],
    "incluir": ["excluir"],
    "aceitar": ["recusar"],
    "comum": ["incomum", "raro"],
    "ativo": ["passivo"],
    "público": ["privado"],
    "abundância": ["escassez"],
    "alegria": ["tristeza"],
    "calma": ["agitação"],
    "concordância": ["discordância"],
    "coragem": ["covardia"],
    "crédito": ["débito"],
    "culpa": ["inocência"],
    "democracia": ["ditadura"],
    "direita": ["esquerda"],
    "doença": ["saúde"],
    "dúvida": ["certeza"],
    "entrada": ["saída"],
    "esperança": ["desespero"],
    "guerra": ["paz"],
    "liberdade": ["escravidão"],
    "luz": ["escuridão"],
    "maioria": ["minoria"],
    "nascimento": ["morte"],
    "otimismo": ["pessimismo"],
    "perda": ["ganho"],
    "proximidade": ["distância"],
    "simpatia": ["antipatia"],
    "sucesso": ["fracasso"],
    "vantagem": ["desvantagem"],
    "verdade": ["mentira"],
    "vitória": ["derrota"],
    "amigo": ["inimigo"],
    "beleza": ["feiura"],
    "caro": ["barato"],
    "doce": ["azedo", "amargo"],
    "grande": ["pequeno"],
    "grosso": ["fino"],
    "quente": ["frio"],
    "largo": ["estreito"],
    "limpo": ["sujo"],
    "macio": ["duro"],
    "magro": ["gordo"],
    "novo": ["velho"],
    "pesado": ["leve"],
    "rápido": ["lento"],
    "seco": ["molhado"],
    "sol": ["lua"],
    "claro": ["escuro"],
    "cheio": ["vazio"],
    "bom": ["mau"],
    "feliz": ["triste"],
    "vivo": ["morto"],
    "acordado": ["dormindo"],
    "rico": ["pobre"],
    "fraco": ["forte"],
    "jovem": ["velho"],
    "silencioso": ["barulhento"],
    "verdadeiro": ["falso"],
    "corajoso": ["covarde"],
    "doente": ["saudável"],
    "esperto": ["tolo"],
    "gentil": ["rude"],
    "honesto": ["desonesto"],
    "justo": ["injusto"],
    "legal": ["ilegal"],
    "limpo": ["sujo"],
    "natural": ["artificial"],
    "puro": ["impuro"],
    "simples": ["complexo"],
    "sincero": ["dissimulado"],
    "sábio": ["ignorante"],
    "ativo": ["passivo"],
    "calmo": ["agitado"],
    "completo": ["incompleto"],
    "correto": ["errado"],
    "discreto": ["indiscreto"],
    "eficaz": ["ineficaz"],
    "fiel": ["infiel"],
    "flexível": ["rígido"],
    "generoso": ["egoísta"],
    "importante": ["insignificante"],
    "paciente": ["impaciente"],
    "permanente": ["temporário"],
    "possível": ["impossível"],
    "responsável": ["irresponsável"],
    "seguro": ["inseguro"],
    "tolerante": ["intolerante"],
    "útil": ["inútil"],
    "visível": ["invisível"],
    "voluntário": ["involuntário"],
    "aceitar": ["rejeitar"],
    "abrir": ["fechar"],
    "acender": ["apagar"],
    "amar": ["odiar"],
    "aumentar": ["diminuir"],
    "chegar": ["partir"],
    "comprar": ["vender"],
    "começar": ["terminar"],
    "concordar": ["discordar"],
    "construir": ["destruir"],
    "dar": ["receber"],
    "dormir": ["acordar"],
    "entrar": ["sair"],
    "fazer": ["desfazer"],
    "ganhar": ["perder"],
    "incluir": ["excluir"],
    "ir": ["vir"],
    "lembrar": ["esquecer"],
    "ligar": ["desligar"],
    "limpar": ["sujar"],
    "nascer": ["morrer"],
    "permitir": ["proibir"],
    "prender": ["soltar"],
    "subir": ["descer"],
    "unir": ["dividir"],
    "vencer": ["perder"],
    "acima": ["abaixo"],
    "adiante": ["atrás"],
    "agora": ["antes", "depois"],
    "aqui": ["lá", "ali"],
    "bem": ["mal"],
    "cedo": ["tarde"],
    "dentro": ["fora"],
    "frente": ["trás"],
    "junto": ["separado"],
    "longe": ["perto"],
    "muito": ["pouco"],
    "nunca": ["sempre"],
    "primeiro": ["último"],
    "sim": ["não"],
    "totalmente": ["parcialmente"],
    "verdadeiramente": ["falsamente"],
    "ativo": ["inativo"],
    "concordar": ["discordar"],
    "corajoso": ["medroso"],
    "feliz": ["infeliz"],
    "gentil": ["áspero"],
    "grande": ["pequeno"],
    "humilde": ["arrogante"],
    "justo": ["injusto"],
    "limpo": ["sujo"],
    "maior": ["menor"],
    "novo": ["velho"],
    "perto": ["longe"],
    "rico": ["pobre"],
    "sábio": ["tolo"],
    "simples": ["complexo"],
    "tranquilo": ["nervoso"],
    "verdadeiro": ["falso"],
    "útil": ["inútil"],
    "visível": ["invisível"],
    "vivo": ["morto"],
    "acreditar": ["duvidar"],
    "adicionar": ["remover"],
    "admitir": ["negar"],
    "alegrar": ["entristecer"],
    "aparecer": ["desaparecer"],
    "aprovar": ["reprovar"],
    "atingir": ["falhar"],
    "aumentar": ["diminuir"],
    "crescer": ["diminuir"],
    "curar": ["adoecer"],
    "defender": ["atacar"],
    "depois": ["antes"],
    "descer": ["subir"],
    "elevar": ["rebaixar"],
    "encher": ["esvaziar"],
    "fechar": ["abrir"],
    "iniciar": ["interromper"],
    "libertar": ["prender"],
    "mostrar": ["esconder"],
    "obedecer": ["desobedecer"],
    "perdoar": ["condenar"],
    "proibir": ["permitir"],
    "puxar": ["empurrar"],
    "receber": ["dar"],
    "soltar": ["prender"],
    "sumir": ["aparecer"],
    "vazio": ["cheio"],
    "viver": ["morrer"],
    "voltar": ["partir"],
    "ganhar": ["perder"],
    "falar": ["calar"],
    "rir": ["chorar"],
    "dormir": ["acordar"],
    "comer": ["jejuar"],
    "sentar": ["levantar"],
    "andar": ["parar"],
    "chegar": ["partir"],
    "subir": ["descer"],
    "entrar": ["sair"],
    "dar": ["receber"],
    "comprar": ["vender"],
    "amar": ["odiar"],
    "construir": ["destruir"],
    "limpar": ["sujar"],
    "ligar": ["desligar"],
    "chover": ["estiar"],
    "acelerar": ["frear"],
    "apertar": ["afrouxar"],
    "aceitar": ["recusar"],
    "abençoar": ["amaldiçoar"],
    "abundar": ["escassear"],
    "acabar": ["começar"],
    "acerto": ["erro"],
    "acerto": ["erro"],
    "acesso": ["saída"],
    "acesso": ["saída"],
    "acordar": ["dormir"],
    "acordo": ["desacordo"],
    "admitir": ["demitir"],
    "adoecer": ["curar"],
    "agradar": ["desagradar"],
    "alegrar": ["entristecer"],
    "amplo": ["estreito"],
    "antepor": ["pospor"],
    "apagar": ["acender"],
    "apertar": ["afrouxar"],
    "aprofundar": ["superficializar"],
    "aprovar": ["reprovar"],
    "ardente": ["gélido"],
    "ascensão": ["declínio"],
    "assediar": ["proteger"],
    "atar": ["desatar"],
    "atrevido": ["tímido"],
    "aumento": ["diminuição"],
    "avanço": ["retrocesso"],
    "bendizer": ["maldizer"],
    "benevolência": ["malevolência"],
    "blanco": ["negro"],
    "brilhar": ["apagar"],
    "calmo": ["agitado"],
    "cativeiro": ["liberdade"],
    "céu": ["inferno"],
    "coerência": ["incoerência"],
    "côncavo": ["convexo"],
    "concordar": ["discordar"],
    "confiança": ["desconfiança"],
    "confirmar": ["negar"],
    "conforto": ["desconforto"],
    "congelar": ["descongelar"],
    "conectar": ["desconectar"],
    "construir": ["destruir"],
    "continuidade": ["interrupção"],
    "coragem": ["covardia"],
    "crescer": ["diminuir"],
    "culpa": ["inocência"],
    "curar": ["adoecer"],
    "débil": ["forte"],
    "decente": ["indecente"],
    "defender": ["atacar"],
    "definitivo": ["provisório"],
    "delicado": ["grosseiro"],
    "democracia": ["ditadura"],
    "dentro": ["fora"],
    "descanso": ["trabalho"],
    "descer": ["subir"],
    "desfazer": ["fazer"],
    "desligar": ["ligar"],
    "desligado": ["ligado"],
    "desocupado": ["ocupado"],
    "desvantagem": ["vantagem"],
    "direita": ["esquerda"],
    "discreto": ["indiscreto"],
    "discurso": ["silêncio"],
    "doar": ["receber"],
    "doença": ["saúde"],
    "doméstico": ["selvagem"],
    "dúvida": ["certeza"],
    "duro": ["mole"],
    "eficaz": ["ineficaz"],
    "elevar": ["rebaixar"],
    "emergir": ["sumir"],
    "empurrar": ["puxar"],
    "encorajar": ["desencorajar"],
    "encontrar": ["perder"],
    "entrada": ["saída"],
    "errado": ["certo"],
    "escassez": ["abundância"],
    "escuridão": ["luz"],
    "estabilidade": ["instabilidade"],
    "estável": ["instável"],
    "estreito": ["largo"],
    "eternidade": ["mortalidade"],
    "exalar": ["inspirar"],
    "excluir": ["incluir"],
    "existir": ["inexistir"],
    "êxito": ["fracasso"],
    "explícito": ["implícito"],
    "externo": ["interno"],
    "extrovertido": ["introvertido"],
    "fácil": ["difícil"],
    "falso": ["verdadeiro"],
    "familiar": ["estranho"],
    "feliz": ["infeliz"],
    "feminino": ["masculino"],
    "fechar": ["abrir"],
    "fiel": ["infiel"],
    "final": ["inicial"],
    "firme": ["instável"],
    "flexível": ["rígido"],
    "flutuante": ["fixo"],
    "forte": ["fraco"],
    "fracasso": ["sucesso"],
    "fragil": ["resistente"],
    "frente": ["trás"],
    "frio": ["quente"],
    "ganhar": ["perder"],
    "gastar": ["economizar"],
    "generoso": ["mesquinho"],
    "gentil": ["rude"],
    "gordo": ["magro"],
    "grade": ["pequeno"],
    "grosseiro": ["delicado"],
    "guerra": ["paz"],
    "hábil": ["incapaz"],
    "harmonia": ["discórdia"],
    "humilde": ["orgulhoso"],
    "ideal": ["real"],
    "ignorar": ["atentar"],
    "ilegal": ["legal"],
    "ilegítimo": ["legítimo"],
    "iludir": ["desiludir"],
    "imediatamente": ["lentamente"],
    "imparcial": ["parcial"],
    "imperfeito": ["perfeito"],
    "implícito": ["explícito"],
    "importante": ["insignificante"],
    "impossível": ["possível"],
    "impuro": ["puro"],
    "inação": ["ação"],
    "incapaz": ["capaz"],
    "incoerente": ["coerente"],
    "incompleto": ["completo"],
    "inconstante": ["constante"],
    "incorreto": ["correto"],
    "indefinido": ["definido"],
    "indiferente": ["interessado"],
    "indireto": ["direto"],
    "ineficaz": ["eficaz"],
    "inexistente": ["existente"],
    "infeliz": ["feliz"],
    "infiel": ["fiel"],
    "inferior": ["superior"],
    "infinito": ["finito"],
    "inflexível": ["flexível"],
    "informal": ["formal"],
    "injustiça": ["justiça"],
    "inocente": ["culpado"],
    "inoperante": ["operante"],
    "inquieto": ["tranquilo"],
    "insignificante": ["significativo"],
    "instabilidade": ["estabilidade"],
    "insuficiente": ["suficiente"],
    "interno": ["externo"],
    "interromper": ["continuar"],
    "intolerante": ["tolerante"],
    "inválido": ["válido"],
    "invisível": ["visível"],
    "irreal": ["real"],
    "irrelevante": ["relevante"],
    "irresponsável": ["responsável"],
    "jovem": ["idoso"],
    "junto": ["separado"],
    "justiça": ["injustiça"],
    "lado": ["meio"],
    "largo": ["estreito"],
    "legal": ["ilegal"],
    "leve": ["pesado"],
    "liberdade": ["escravidão"],
    "ligado": ["desligado"],
    "limpo": ["sujo"],
    "liso": ["áspero"],
    "longe": ["perto"],
    "luz": ["escuridão"],
    "macio": ["duro"],
    "magro": ["gordo"],
    "maior": ["menor"],
    "mal": ["bem"],
    "maldizer": ["bendizer"],
    "masculino": ["feminino"],
    "medroso": ["corajoso"],
    "melhor": ["pior"],
    "mentira": ["verdade"],
    "mesquinho": ["generoso"],
    "minoria": ["maioria"],
    "molhado": ["seco"],
    "mole": ["duro"],
    "morte": ["vida"],
    "movimento": ["imobilidade"],
    "muito": ["pouco"],
    "natural": ["artificial"],
    "negativo": ["positivo"],
    "negar": ["afirmar"],
    "nenhum": ["algum"],
    "nervoso": ["calmo"],
    "noite": ["dia"],
    "normal": ["anormal"],
    "novo": ["velho"],
    "nulo": ["válido"],
    "obedecer": ["desobedecer"],
    "obscuro": ["claro"],
    "oculto": ["visível"],
    "odiar": ["amar"],
    "ofensivo": ["defensivo"],
    "oposto": ["idêntico"],
    "otimismo": ["pessimismo"],
    "paciente": ["impaciente"],
    "parcial": ["imparcial"],
    "partida": ["chegada"],
    "passado": ["futuro"],
    "passivo": ["ativo"],
    "paz": ["guerra"],
    "pecado": ["virtude"],
    "pequeno": ["grande"],
    "perda": ["ganho"],
    "perfeito": ["imperfeito"],
    "permanente": ["temporário"],
    "permitir": ["proibir"],
    "perto": ["longe"],
    "pesado": ["leve"],
    "pior": ["melhor"],
    "pobre": ["rico"],
    "polido": ["rude"],
    "possível": ["impossível"],
    "postergado": ["antecipado"],
    "pouco": ["muito"],
    "praticar": ["teorizar"],
    "preguiçoso": ["diligente"],
    "presente": ["ausente"],
    "principal": ["secundário"],
    "privado": ["público"],
    "proibir": ["permitir"],
    "progresso": ["retrocesso"],
    "próprio": ["alheio"],
    "proteger": ["expor"],
    "público": ["privado"],
    "puro": ["impuro"],
    "puxar": ["empurrar"],
    "qualificado": ["desqualificado"],
    "quente": ["frio"],
    "quieto": ["agitado"],
    "racional": ["irracional"],
    "rápido": ["lento"],
    "receber": ["dar"],
    "recusar": ["aceitar"],
    "real": ["irreal"],
    "rebelde": ["obediente"],
    "refinar": ["bruto"],
    "remoto": ["próximo"],
    "renovar": ["deteriorar"],
    "resistente": ["frágil"],
    "responsável": ["irresponsável"],
    "retardar": ["acelerar"],
    "retornar": ["partir"],
    "revelar": ["esconder"],
    "rico": ["pobre"],
    "rígido": ["flexível"],
    "romper": ["unir"],
    "rude": ["gentil"],
    "ruidoso": ["silencioso"],
    "sair": ["entrar"],
    "salvar": ["condenar"],
    "saudável": ["doente"],
    "seco": ["molhado"],
    "seguro": ["inseguro"],
    "selvagem": ["doméstico"],
    "sempre": ["nunca"],
    "separado": ["unido"],
    "sereno": ["agitado"],
    "sério": ["brincalhão"],
    "simples": ["complexo"],
    "sincero": ["falso"],
    "sob": ["sobre"],
    "social": ["anti-social"],
    "soltar": ["prender"],
    "sombrio": ["luminoso"],
    "sorte": ["azar"],
    "suave": ["áspero"],
    "subir": ["descer"],
    "submeter": ["rebelar"],
    "subordinado": ["superior"],
    "sucesso": ["fracasso"],
    "suficiente": ["insuficiente"],
    "sujo": ["limpo"],
    "superior": ["inferior"],
    "suspeita": ["confiança"],
    "tarde": ["cedo"],
    "temerário": ["prudente"],
    "temporário": ["permanente"],
    "término": ["início"],
    "tímido": ["atrevido"],
    "tolerante": ["intolerante"],
    "tolo": ["sábio"],
    "total": ["parcial"],
    "trabalho": ["descanso"],
    "tranquilo": ["inquieto"],
    "transparente": ["opaco"],
    "triste": ["alegre"],
    "tudo": ["nada"],
    "último": ["primeiro"],
    "unido": ["separado"],
    "útil": ["inútil"],
    "válido": ["inválido"],
    "vazio": ["cheio"],
    "velho": ["novo"],
    "vender": ["comprar"],
    "verdade": ["mentira"],
    "vício": ["virtude"],
    "vitória": ["derrota"],
    "vivo": ["morto"],
    "voluntário": ["involuntário"],
    "vulnerável": ["invulnerável"],
    "zeloso": ["negligente"],
    "bom": ["ruim", "mau", "péssimo", "detestável"],
    "grande": ["pequeno", "minúsculo", "diminuto", "reduzido"],
    "feliz": ["triste", "infeliz", "melancólico", "desanimado"],
    "rápido": ["lento", "devagar", "demorado", "vagoroso"],
    "claro": ["escuro", "obscuro", "sombrio", "turvo", "nebuloso"],
    "alto": ["baixo", "raso", "curto"],
    "novo": ["velho", "antigo", "obsoleto", "arcaico"],
    "bonito": ["feio", "horrível", "desagradável"],
    "forte": ["fraco", "débil", "frágil"],
    "quente": ["frio", "gelado", "gélido"],
    "cheio": ["vazio", "oco", "desocupado"],
    "pesado": ["leve", "delicado"],
    "largo": ["estreito", "apertado"],
    "fácil": ["difícil", "complicado", "árduo"],
    "rico": ["pobre", "miserável", "desprovido"],
    "limpo": ["sujo", "imundo", "maculado"],
    "doce": ["amargo", "azedo", "salgado"],
    "duro": ["mole", "macio", "brando"],
    "aberto": ["fechado", "cerrado", "vedado"],
    "curto": ["longo", "comprido", "extenso"],
    "calmo": ["agitado", "nervoso", "inquieto"],
    "gordo": ["magro", "esbelto", "fino"],
    "alegre": ["triste", "desanimado", "sombrio"],
    "sincero": ["mentiroso", "falso", "dissimulado"],
    "verdadeiro": ["falso", "irreal", "mentiroso"],
    "corajoso": ["covarde", "medroso", "pusilânime"],
    "silencioso": ["barulhento", "ruidoso"],
    "inteligente": ["burro", "ignorante", "tolo"],
    "justo": ["injusto", "parcial", "tendencioso"],
    "esperto": ["ingênuo", "bobo", "tolo"],
    "delicioso": ["horrível", "nojento", "desagradável"],
    "legal": ["ilegal", "chato", "ilegitimo"],
    "ativo": ["inativo", "passivo", "ocioso"],
    "generoso": ["egoísta", "mesquinho", "avarento"],
    "prudente": ["imprudente", "descuidado", "temerário"],
    "amigável": ["hostil", "antipático", "inimigo"],
    "útil": ["inútil", "dispensável", "supérfluo"],
    "presente": ["ausente", "faltoso"],
    "possível": ["impossível", "improvável"],
    "completo": ["incompleto", "parcial", "deficiente"],
    "correto": ["incorreto", "errado", "equivocado"],
    "visível": ["invisível", "oculto", "escondido"],
    "direto": ["indireto", "tortuoso"],
    "fraco": ["forte", "resistente", "robusto"],
    "rico": ["pobre", "carente"],
    "certo": ["errado", "incerto", "duvidoso"],
    "liso": ["áspero", "rugoso"],
    "suave": ["áspero", "ríspido"],
    "macio": ["duro", "rígido"],
    "jovem": ["idoso", "ancião"],
    "veloz": ["lento", "moroso"],
    "doente": ["saudável", "sadio"],
    "sábio": ["ignorante", "néscio"],
    "comum": ["raro", "incomum"],
    "igual": ["diferente", "desigual"],
    "honesto": ["desonesto", "trapaceiro"],
    "fiel": ["infiel", "traidor"],
    "organizado": ["desorganizado", "caótico"],
    "disciplinado": ["indisciplinado", "rebelde"],
    "otimista": ["pessimista", "desesperançoso"],
    "ativo": ["inativo", "passivo"],
    "paciente": ["impaciente", "ansioso"],
    "capaz": ["incapaz", "inapto"],
    "limpo": ["sujo", "embaçado"],
    "molhado": ["seco", "enxuto"],
    "doce": ["amargo", "azedo"],
    "cruel": ["gentil", "bondoso"],
    "justo": ["injusto", "desonesto"],
    "simples": ["complexo", "complicado"],
    "generoso": ["mesquinho", "egoísta"],
    "ativo": ["passivo", "ocioso"],
    "comum": ["raro", "excepcional"],
    "presente": ["ausente", "passado"],
    "futuro": ["passado", "anterior"],
    "unido": ["separado", "dividido"],
    "abundante": ["escasso", "insuficiente"],
    "eficaz": ["ineficaz", "inoperante"],
    "responsável": ["irresponsável", "negligente"],
    "seguro": ["inseguro", "perigoso"],
    "visível": ["invisível", "oculto"],
    "racional": ["irracional", "ilógico"],
    "coerente": ["incoerente", "contraditório"],
    "legítimo": ["ilegítimo", "falso"],
    "válido": ["inválido", "nulo"],
    "puro": ["impuro", "contaminado"],
    "discreto": ["indiscreto", "chamativo"],
    "legal": ["ilegal", "proibido"],
    "tolerante": ["intolerante", "rígido"],
    "flexível": ["rígido", "inflexível"],
    "natural": ["artificial", "sintético"],
    "real": ["irreal", "fictício"],
    "específico": ["genérico", "geral"],
    "público": ["privado", "secreto"],
    "permanente": ["temporário", "transitório"],
    "fixo": ["móvel", "variável"],
    "interno": ["externo", "exterior"],
    "superior": ["inferior", "subordinado"],
    "principal": ["secundário", "subsidiário"],
    "primário": ["secundário", "terciário"],
    "essencial": ["dispensável", "supérfluo"],
    "necessário": ["desnecessário", "supérfluo"],
    "fundamental": ["dispensável", "acessório"],
    "importante": ["insignificante", "irrelevante"],
    "prioritário": ["secundário", "terciário"],
    "principal": ["subordinado", "acessório"],
    "central": ["periférico", "marginal"],
    "inicial": ["final", "conclusivo"],
    "anterior": ["posterior", "subsequente"],
    "passado": ["futuro", "presente"],
    "ativo": ["passivo", "ocioso"],
    "consciente": ["inconsciente", "desacordado"],
    "voluntário": ["involuntário", "forçado"],
    "direto": ["indireto", "oblíquo"],
    "provisório": ["definitivo", "permanente"],
    "constante": ["variável", "inconstante"],
    "estável": ["instável", "volátil"],
    "estático": ["dinâmico", "móvel"],
    "sólido": ["líquido", "gasoso", "fraco"],
    "cheio": ["vazio", "oco"],

    // Verbos comuns
    "amar": ["odiar", "detestar"],
    "aceitar": ["rejeitar", "recusar", "negar"],
    "abrir": ["fechar", "cerrar"],
    "acender": ["apagar", "desligar"],
    "subir": ["descer", "cair"],
    "começar": ["terminar", "acabar", "finalizar"],
    "comprar": ["vender", "alienar"],
    "dar": ["receber", "tirar", "recolher"],
    "entrar": ["sair", "partir"],
    "vir": ["ir", "partir"],
    "construir": ["destruir", "demolir", "desmantelar"],
    "unir": ["separar", "dividir"],
    "incluir": ["excluir", "retirar"],
    "permitir": ["proibir", "impedir"],
    "lembrar": ["esquecer", "olvidar"],
    "ganhar": ["perder", "derrotar"],
    "aparecer": ["desaparecer", "sumir"],
    "concordar": ["discordar", "divergir"],
    "aprovar": ["reprovar", "desaprovar"],
    "prender": ["soltar", "libertar"],
    "nascer": ["morrer", "falecer"],
    "rir": ["chorar", "lamentar"],
    "dormir": ["acordar", "despertar"],
    "encontrar": ["perder", "desencontrar"],
    "ensinar": ["aprender", "desaprender"],
    "apertar": ["afrouxar", "soltar"],
    "chover": ["estiar", "secar"],
    "conectar": ["desconectar", "separar"],
    "ligar": ["desligar", "interromper"],
    "acelerar": ["desacelerar", "frear"],
    "avançar": ["recuar", "retroceder"],
    "aceitar": ["recusar", "negar"],
    "admitir": ["negar", "demitir"],
    "aumentar": ["diminuir", "reduzir"],
    "colocar": ["retirar", "remover"],
    "chegar": ["partir", "sair"],
    "despertar": ["dormir", "adormecer"],
    "entrar": ["sair", "abandonar"],
    "existir": ["inexistir", "perecer"],
    "iniciar": ["interromper", "cessar"],
    "limpar": ["sujar", "emborcar"],
    "multiplicar": ["dividir", "subtrair"],
    "nascer": ["morrer", "findar"],
    "obedecer": ["desobedecer", "rebelar"],
    "partir": ["chegar", "retornar"],
    "receber": ["dar", "ceder"],
    "retornar": ["partir", "ir"],
    "segurar": ["soltar", "largar"],
    "subir": ["descer", "cair"],
    "unir": ["separar", "desligar"],
    "vencer": ["perder", "fracassar"],
    "virar": ["desvirar", "inverter"],

    // Substantivos comuns
    "dia": ["noite", "madrugada"],
    "início": ["fim", "término", "desfecho"],
    "entrada": ["saída", "partida"],
    "amor": ["ódio", "rancor", "aversão"],
    "paz": ["guerra", "conflito", "discórdia"],
    "vida": ["morte", "fim"],
    "verdade": ["mentira", "falsidade"],
    "alegria": ["tristeza", "melancolia", "desânimo"],
    "saúde": ["doença", "enfermidade"],
    "felicidade": ["infelicidade", "tristeza"],
    "luz": ["escuridão", "trevas"],
    "sorte": ["azar", "infortúnio"],
    "riqueza": ["pobreza", "miséria"],
    "coragem": ["covardia", "medo"],
    "vitória": ["derrota", "fracasso"],
    "bem": ["mal", "ruim"],
    "ganho": ["perda", "prejuízo"],
    "calor": ["frio", "friagem"],
    "silêncio": ["barulho", "ruído"],
    "justiça": ["injustiça", "desigualdade"],
    "liberdade": ["prisão", "escravidão", "opressão"],
    "conhecimento": ["ignorância", "desconhecimento"],
    "humildade": ["soberba", "arrogância"],
    "ordem": ["desordem", "caos"],
    "progresso": ["retrocesso", "regresso"],
    "esperança": ["desespero", "desesperança"],
    "confiança": ["desconfiança", "suspeita"],
    "beleza": ["feiura", "deformidade"],
    "sabedoria": ["ignorância", "insensatez"],
    "honestidade": ["desonestidade", "fraude"],
    "fidelidade": ["infidelidade", "traição"],
    "disciplina": ["indisciplina", "bagunça"],
    "otimismo": ["pessimismo", "desânimo"],
    "atividade": ["inatividade", "ociosidade"],
    "paciência": ["impaciência", "pressa"],
    "capacidade": ["incapacidade", "inaptidão"],
    "limpeza": ["sujeira", "imundície"],
    "doçura": ["amargura", "azedume"],
    "crueldade": ["gentileza", "bondade"],
    "simplicidade": ["complexidade", "complicação"],
    "generosidade": ["mesquinhez", "egoísmo"],
    "comum": ["raro", "excepcional"],
    "presença": ["ausência", "falta"],
    "unidade": ["separação", "divisão"],
    "abundância": ["escassez", "insuficiência"],
    "eficácia": ["ineficácia", "inoperância"],
    "responsabilidade": ["irresponsabilidade", "negligência"],
    "segurança": ["insegurança", "perigo"],
    "visibilidade": ["invisibilidade", "ocultação"],
    "racionalidade": ["irracionalidade", "ilógica"],
    "coerência": ["incoerência", "contradição"],
    "legitimidade": ["ilegitimidade", "falsidade"],
    "validade": ["invalidade", "nulidade"],
    "pureza": ["impureza", "contaminação"],
    "discrição": ["indiscrição", "chamariz"],
    "legalidade": ["ilegalidade", "proibição"],
    "tolerância": ["intolerância", "rigidez"],
    "flexibilidade": ["rigidez", "inflexibilidade"],
    "naturalidade": ["artificialidade", "sinteticidade"],
    "realidade": ["irrealidade", "ficção"],
    "especificidade": ["generalidade", "vagueza"],
    "público": ["privado", "secreto"],
    "permanência": ["transitoriedade", "efemeridade"],
    "fixidez": ["mobilidade", "variabilidade"],
    "interior": ["exterior", "externo"],
    "superioridade": ["inferioridade", "subordinação"],
    "principal": ["secundário", "subordinado"],
    "primário": ["secundário", "terciário"],
    "essencial": ["dispensável", "supérfluo"],
    "necessário": ["desnecessário", "supérfluo"],
    "fundamental": ["dispensável", "acessório"],
    "importante": ["insignificante", "irrelevante"],
    "prioritário": ["secundário", "terciário"],
    "principal": ["subordinado", "acessório"],
    "central": ["periférico", "marginal"],
    "inicial": ["final", "conclusivo"],
    "anterior": ["posterior", "subsequente"],
    "passado": ["futuro", "presente"],
    "ativo": ["passivo", "ocioso"],
    "consciente": ["inconsciente", "desacordado"],
    "voluntário": ["involuntário", "forçado"],
    "direto": ["indireto", "oblíquo"],
    "provisório": ["definitivo", "permanente"],
    "constante": ["variável", "inconstante"],
    "estável": ["instável", "volátil"],
    "estático": ["dinâmico", "móvel"],
    "sólido": ["líquido", "gasoso", "fraco"],
    "cheio": ["vazio", "oco"],

    // Advérbios
    "perto": ["longe", "distante", "afastado"],
    "dentro": ["fora", "exterior"],
    "agora": ["depois", "antes", "antigamente"],
    "aqui": ["lá", "ali", "acolá"],
    "sim": ["não", "jamais"],
    "sempre": ["nunca", "jamais"],
    "muito": ["pouco", "quase nada"],
    "acima": ["abaixo", "embaixo"],
    "adiante": ["atrás", "para trás"],
    "antes": ["depois", "após"],
    "bem": ["mal", "ruim"],
    "cedo": ["tarde", "tardiamente"],
    "rápido": ["lentamente", "devagar"],
    "junto": ["separado", "afastado"],
    "certo": ["errado", "incorretamente"],
    "claro": ["obscuramente", "escuro"],
    "diretamente": ["indiretamente", "obliquamente"],
    "frequentemente": ["raramente", "ocasionalmente"],
    "geralmente": ["especificamente", "raramente"],
    "hoje": ["ontem", "amanhã"],
    "imediatamente": ["lentamente", "tardiamente"],
    "inclusive": ["exclusive", "exceto"],
    "longe": ["perto", "próximo"],
    "mais": ["menos", "pouco"],
    "melhor": ["pior", "piores"],
    "naturalmente": ["artificialmente", "forçadamente"],
    "nunca": ["sempre", "eternamente"],
    "pouco": ["muito", "abundantemente"],
    "primeiro": ["último", "finalmente"],
    "rapidamente": ["lentamente", "vagorosamente"],
    "simplesmente": ["complicadamente", "elaboradamente"],
    "somente": ["também", "inclusive"],
    "suficientemente": ["insuficientemente", "pouco"],
    "tarde": ["cedo", "adiantado"],
    "totalmente": ["parcialmente", "incompletamente"],
    "verdadeiramente": ["falsamente", "enganosamente"],
    "visivelmente": ["invisivelmente", "ocultamente"],
    "certamente": ["incertamente", "duvidosamente"],
    "facilmente": ["dificilmente", "arduamente"],
    "livremente": ["prisioneiramente", "forçadamente"],
    "secretamente": ["publicamente", "abertamente"],
    "silenciosamente": ["ruidosamente", "barulhentamente"],
    "tranquilamente": ["agitadamente", "nervosamente"],
    "unidamente": ["separadamente", "divididamente"],
    "virtualmente": ["realmente", "fisicamente"],
    "voluntariamente": ["involuntariamente", "compulsoriamente"],
    "acidentalmente": ["intencionalmente", "propositadamente"],
    "ativamente": ["passivamente", "ociosamente"],
    "claramente": ["obscuramente", "indistintamente"],
    "cuidadosamente": ["descuidadamente", "negligentemente"],
    "definidamente": ["indefinidamente", "vagamene"],
    "direitamente": ["esquerdamente", "indiretamente"],
    "eficientemente": ["ineficientemente", "mal"],
    "fortemente": ["fracamente", "debilmente"],
    "honestamente": ["desonestamente", "trapaceiramente"],
    "infelizmente": ["felizmente", "sortudamente"],
    "legalmente": ["ilegalmente", "proibitivamente"],
    "negativamente": ["positivamente", "afirmativamente"],
    "pacientemente": ["impacientemente", "ansiosamente"],
    "permanentemente": ["temporariamente", "provisoriamente"],
    "praticamente": ["teoricamente", "impraticavelmente"],
    "realmente": ["irrealmente", "ficticiamente"],
    "seguramente": ["inseguramente", "perigosamente"],
    "seriamente": ["brincando", "levianamente"],
    "terrivelmente": ["maravilhosamente", "excelentemente"],
    "ultimamente": ["primeiramente", "anteriormente"],
    "utilmente": ["inutilmente", "desnecessariamente"],
    "vagarosamente": ["rapidamente", "pressurosamente"],
    "validamente": ["invalidamente", "ilegitimamente"],
    "violentamente": ["calmamente", "pacificamente"],
    "zelosamente": ["descuidadamente", "negligentemente"],

    // Outros
    "sim": ["não"],
    "para frente": ["para trás", "para trás"],
    "cima": ["baixo"],
    "frente": ["trás", "costas"],
    "dentro": ["fora"],
    "antes": ["depois"],
    "primeiro": ["último"],
    "começo": ["fim"],
    "norte": ["sul"],
    "leste": ["oeste"],
    "positivo": ["negativo"],
    "incluir": ["excluir"],
    "aceitar": ["recusar"],
    "comum": ["incomum", "raro"],
    "ativo": ["passivo"],
    "público": ["privado"],
    "abundância": ["escassez"],
    "alegria": ["tristeza"],
    "calma": ["agitação"],
    "concordância": ["discordância"],
    "coragem": ["covardia"],
    "crédito": ["débito"],
    "culpa": ["inocência"],
    "democracia": ["ditadura"],
    "direita": ["esquerda"],
    "doença": ["saúde"],
    "dúvida": ["certeza"],
    "entrada": ["saída"],
    "esperança": ["desespero"],
    "guerra": ["paz"],
    "liberdade": ["escravidão"],
    "luz": ["escuridão"],
    "maioria": ["minoria"],
    "nascimento": ["morte"],
    "otimismo": ["pessimismo"],
    "perda": ["ganho"],
    "proximidade": ["distância"],
    "simpatia": ["antipatia"],
    "sucesso": ["fracasso"],
    "vantagem": ["desvantagem"],
    "verdade": ["mentira"],
    "vitória": ["derrota"],
    "amigo": ["inimigo"],
    "beleza": ["feiura"],
    "caro": ["barato"],
    "doce": ["azedo", "amargo"],
    "grande": ["pequeno"],
    "grosso": ["fino"],
    "quente": ["frio"],
    "largo": ["estreito"],
    "limpo": ["sujo"],
    "macio": ["duro"],
    "magro": ["gordo"],
    "novo": ["velho"],
    "pesado": ["leve"],
    "rápido": ["lento"],
    "seco": ["molhado"],
    "sol": ["lua"],
    "claro": ["escuro"],
    "cheio": ["vazio"],
    "bom": ["mau"],
    "feliz": ["triste"],
    "vivo": ["morto"],
    "acordado": ["dormindo"],
    "rico": ["pobre"],
    "fraco": ["forte"],
    "jovem": ["velho"],
    "silencioso": ["barulhento"],
    "verdadeiro": ["falso"],
    "corajoso": ["covarde"],
    "doente": ["saudável"],
    "esperto": ["tolo"],
    "gentil": ["rude"],
    "honesto": ["desonesto"],
    "justo": ["injusto"],
    "legal": ["ilegal"],
    "limpo": ["sujo"],
    "natural": ["artificial"],
    "puro": ["impuro"],
    "simples": ["complexo"],
    "sincero": ["dissimulado"],
    "sábio": ["tolo"],
    "ativo": ["passivo"],
    "calmo": ["agitado"],
    "completo": ["incompleto"],
    "correto": ["errado"],
    "discreto": ["indiscreto"],
    "eficaz": ["ineficaz"],
    "fiel": ["infiel"],
    "flexível": ["rígido"],
    "generoso": ["egoísta"],
    "importante": ["insignificante"],
    "paciente": ["impaciente"],
    "permanente": ["temporário"],
    "possível": ["impossível"],
    "responsável": ["irresponsável"],
    "seguro": ["inseguro"],
    "tolerante": ["intolerante"],
    "útil": ["inútil"],
    "visível": ["invisível"],
    "voluntário": ["involuntário"],
    "aceitar": ["rejeitar"],
    "abrir": ["fechar"],
    "acender": ["apagar"],
    "amar": ["odiar"],
    "aumentar": ["diminuir"],
    "chegar": ["partir"],
    "comprar": ["vender"],
    "começar": ["terminar"],
    "concordar": ["discordar"],
    "construir": ["destruir"],
    "dar": ["receber"],
    "dormir": ["acordar"],
    "entrar": ["sair"],
    "fazer": ["desfazer"],
    "ganhar": ["perder"],
    "incluir": ["excluir"],
    "ir": ["vir"],
    "lembrar": ["esquecer"],
    "ligar": ["desligar"],
    "limpar": ["sujar"],
    "nascer": ["morrer"],
    "permitir": ["proibir"],
    "prender": ["soltar"],
    "subir": ["descer"],
    "unir": ["dividir"],
    "vencer": ["perder"],
    "acima": ["abaixo"],
    "adiante": ["atrás"],
    "agora": ["antes", "depois"],
    "aqui": ["lá", "ali"],
    "bem": ["mal"],
    "cedo": ["tarde"],
    "dentro": ["fora"],
    "frente": ["trás"],
    "junto": ["separado"],
    "longe": ["perto"],
    "muito": ["pouco"],
    "nunca": ["sempre"],
    "primeiro": ["último"],
    "sim": ["não"],
    "totalmente": ["parcialmente"],
    "verdadeiramente": ["falsamente"],
    "ativo": ["inativo"],
    "concordar": ["discordar"],
    "corajoso": ["medroso"],
    "feliz": ["infeliz"],
    "gentil": ["áspero"],
    "grande": ["pequeno"],
    "humilde": ["arrogante"],
    "justo": ["injusto"],
    "limpo": ["sujo"],
    "maior": ["menor"],
    "novo": ["velho"],
    "perto": ["longe"],
    "rico": ["pobre"],
    "sábio": ["tolo"],
    "simples": ["complexo"],
    "tranquilo": ["nervoso"],
    "verdadeiro": ["falso"],
    "útil": ["inútil"],
    "visível": ["invisível"],
    "vivo": ["morto"],
    "acreditar": ["duvidar"],
    "adicionar": ["remover"],
    "admitir": ["negar"],
    "alegrar": ["entristecer"],
    "aparecer": ["desaparecer"],
    "aprovar": ["reprovar"],
    "atingir": ["falhar"],
    "aumentar": ["diminuir"],
    "crescer": ["diminuir"],
    "curar": ["adoecer"],
    "defender": ["atacar"],
    "depois": ["antes"],
    "descer": ["subir"],
    "elevar": ["rebaixar"],
    "encher": ["esvaziar"],
    "fechar": ["abrir"],
    "iniciar": ["interromper"],
    "libertar": ["prender"],
    "mostrar": ["esconder"],
    "obedecer": ["desobedecer"],
    "perdoar": ["condenar"],
    "proibir": ["permitir"],
    "puxar": ["empurrar"],
    "receber": ["dar"],
    "soltar": ["prender"],
    "sumir": ["aparecer"],
    "vazio": ["cheio"],
    "viver": ["morrer"],
    "voltar": ["partir"],
    "ganhar": ["perder"],
    "falar": ["calar"],
    "rir": ["chorar"],
    "dormir": ["acordar"],
    "comer": ["jejuar"],
    "sentar": ["levantar"],
    "andar": ["parar"],
    "chegar": ["partir"],
    "subir": ["descer"],
    "entrar": ["sair"],
    "dar": ["receber"],
    "comprar": ["vender"],
    "amar": ["odiar"],
    "construir": ["destruir"],
    "limpar": ["sujar"],
    "ligar": ["desligar"],
    "chover": ["estiar"],
    "acelerar": ["frear"],
    "apertar": ["afrouxar"],
    "aceitar": ["recusar"],
    "abençoar": ["amaldiçoar"],
    "abundar": ["escassear"],
    "acabar": ["começar"],
    "acerto": ["erro"],
    "acesso": ["saída"],
    "acordar": ["dormir"],
    "acordo": ["desacordo"],
    "admitir": ["demitir"],
    "adoecer": ["curar"],
    "agradar": ["desagradar"],
    "alegrar": ["entristecer"],
    "amplo": ["estreito"],
    "antepor": ["pospor"],
    "apagar": ["acender"],
    "apertar": ["afrouxar"],
    "aprofundar": ["superficializar"],
    "aprovar": ["reprovar"],
    "ardente": ["gélido"],
    "ascensão": ["declínio"],
    "assediar": ["proteger"],
    "atar": ["desatar"],
    "atrevido": ["tímido"],
    "aumento": ["diminuição"],
    "avanço": ["retrocesso"],
    "bendizer": ["maldizer"],
    "benevolência": ["malevolência"],
    "blanco": ["negro"],
    "brilhar": ["apagar"],
    "calmo": ["agitado"],
    "cativeiro": ["liberdade"],
    "céu": ["inferno"],
    "coerência": ["incoerência"],
    "côncavo": ["convexo"],
    "concordar": ["discordar"],
    "confiança": ["desconfiança"],
    "confirmar": ["negar"],
    "conforto": ["desconforto"],
    "congelar": ["descongelar"],
    "conectar": ["desconectar"],
    "construir": ["destruir"],
    "continuidade": ["interrupção"],
    "coragem": ["covardia"],
    "crescer": ["diminuir"],
    "culpa": ["inocência"],
    "curar": ["adoecer"],
    "débil": ["forte"],
    "decente": ["indecente"],
    "defender": ["atacar"],
    "definitivo": ["provisório"],
    "delicado": ["grosseiro"],
    "democracia": ["ditadura"],
    "dentro": ["fora"],
    "descanso": ["trabalho"],
    "descer": ["subir"],
    "desfazer": ["fazer"],
    "desligar": ["ligar"],
    "desligado": ["ligado"],
    "desocupado": ["ocupado"],
    "desvantagem": ["vantagem"],
    "direita": ["esquerda"],
    "discreto": ["indiscreto"],
    "discurso": ["silêncio"],
    "doar": ["receber"],
    "doença": ["saúde"],
    "doméstico": ["selvagem"],
    "dúvida": ["certeza"],
    "duro": ["mole"],
    "eficaz": ["ineficaz"],
    "elevar": ["rebaixar"],
    "emergir": ["sumir"],
    "empurrar": ["puxar"],
    "encorajar": ["desencorajar"],
    "encontrar": ["perder"],
    "entrada": ["saída"],
    "errado": ["certo"],
    "escassez": ["abundância"],
    "escuridão": ["luz"],
    "estabilidade": ["instabilidade"],
    "estável": ["instável"],
    "estreito": ["largo"],
    "eternidade": ["mortalidade"],
    "exalar": ["inspirar"],
    "excluir": ["incluir"],
    "existir": ["inexistir"],
    "êxito": ["fracasso"],
    "explícito": ["implícito"],
    "externo": ["interno"],
    "extrovertido": ["introvertido"],
    "fácil": ["difícil"],
    "falso": ["verdadeiro"],
    "familiar": ["estranho"],
    "feliz": ["infeliz"],
    "feminino": ["masculino"],
    "fechar": ["abrir"],
    "fiel": ["infiel"],
    "final": ["inicial"],
    "firme": ["instável"],
    "flexível": ["rígido"],
    "flutuante": ["fixo"],
    "forte": ["fraco"],
    "fracasso": ["sucesso"],
    "fragil": ["resistente"],
    "frente": ["trás"],
    "frio": ["quente"],
    "ganhar": ["perder"],
    "gastar": ["economizar"],
    "generoso": ["mesquinho"],
    "gentil": ["rude"],
    "gordo": ["magro"],
    "grade": ["pequeno"],
    "grosseiro": ["delicado"],
    "guerra": ["paz"],
    "hábil": ["incapaz"],
    "harmonia": ["discórdia"],
    "humilde": ["orgulhoso"],
    "ideal": ["real"],
    "ignorar": ["atentar"],
    "ilegal": ["legal"],
    "ilegítimo": ["legítimo"],
    "iludir": ["desiludir"],
    "imediatamente": ["lentamente"],
    "imparcial": ["parcial"],
    "imperfeito": ["perfeito"],
    "implícito": ["explícito"],
    "importante": ["insignificante"],
    "impossível": ["possível"],
    "impuro": ["puro"],
    "inação": ["ação"],
    "incapaz": ["capaz"],
    "incoerente": ["coerente"],
    "incompleto": ["completo"],
    "inconstante": ["constante"],
    "incorreto": ["correto"],
    "indefinido": ["definido"],
    "indiferente": ["interessado"],
    "indireto": ["direto"],
    "ineficaz": ["eficaz"],
    "inexistente": ["existente"],
    "infeliz": ["feliz"],
    "infiel": ["fiel"],
    "inferior": ["superior"],
    "infinito": ["finito"],
    "inflexível": ["flexível"],
    "informal": ["formal"],
    "injustiça": ["justiça"],
    "inocente": ["culpado"],
    "inoperante": ["operante"],
    "inquieto": ["tranquilo"],
    "insignificante": ["significativo"],
    "instabilidade": ["estabilidade"],
    "insuficiente": ["suficiente"],
    "interno": ["externo"],
    "interromper": ["continuar"],
    "intolerante": ["tolerante"],
    "inválido": ["válido"],
    "invisível": ["visível"],
    "irreal": ["real"],
    "irrelevante": ["relevante"],
    "irresponsável": ["responsável"],
    "jovem": ["idoso"],
    "junto": ["separado"],
    "justiça": ["injustiça"],
    "lado": ["meio"],
    "largo": ["estreito"],
    "legal": ["ilegal"],
    "leve": ["pesado"],
    "liberdade": ["escravidão"],
    "ligado": ["desligado"],
    "limpo": ["sujo"],
    "liso": ["áspero"],
    "longe": ["perto"],
    "luz": ["escuridão"],
    "macio": ["duro"],
    "magro": ["gordo"],
    "maior": ["menor"],
    "mal": ["bem"],
    "maldizer": ["bendizer"],
    "masculino": ["feminino"],
    "medroso": ["corajoso"],
    "melhor": ["pior"],
    "mentira": ["verdade"],
    "mesquinho": ["generoso"],
    "minoria": ["maioria"],
    "molhado": ["seco"],
    "mole": ["duro"],
    "morte": ["vida"],
    "movimento": ["imobilidade"],
    "muito": ["pouco"],
    "natural": ["artificial"],
    "negativo": ["positivo"],
    "negar": ["afirmar"],
    "nenhum": ["algum"],
    "nervoso": ["calmo"],
    "noite": ["dia"],
    "normal": ["anormal"],
    "novo": ["velho"],
    "nulo": ["válido"],
    "obedecer": ["desobedecer"],
    "obscuro": ["claro"],
    "oculto": ["visível"],
    "odiar": ["amar"],
    "ofensivo": ["defensivo"],
    "oposto": ["idêntico"],
    "otimismo": ["pessimismo"],
    "paciente": ["impaciente"],
    "parcial": ["imparcial"],
    "partida": ["chegada"],
    "passado": ["futuro"],
    "passivo": ["ativo"],
    "paz": ["guerra"],
    "pecado": ["virtude"],
    "pequeno": ["grande"],
    "perda": ["ganho"],
    "perfeito": ["imperfeito"],
    "permanente": ["temporário"],
    "permitir": ["proibir"],
    "perto": ["longe"],
    "pesado": ["leve"],
    "pior": ["melhor"],
    "pobre": ["rico"],
    "polido": ["rude"],
    "possível": ["impossível"],
    "postergado": ["antecipado"],
    "pouco": ["muito"],
    "praticar": ["teorizar"],
    "preguiçoso": ["diligente"],
    "presente": ["ausente"],
    "principal": ["secundário"],
    "privado": ["público"],
    "proibir": ["permitir"],
    "progresso": ["retrocesso"],
    "próprio": ["alheio"],
    "proteger": ["expor"],
    "público": ["privado"],
    "puro": ["impuro"],
    "puxar": ["empurrar"],
    "qualificado": ["desqualificado"],
    "quente": ["frio"],
    "quieto": ["agitado"],
    "racional": ["irracional"],
    "rápido": ["lento"],
    "receber": ["dar"],
    "recusar": ["aceitar"],
    "real": ["irreal"],
    "rebelde": ["obediente"],
    "refinar": ["bruto"],
    "remoto": ["próximo"],
    "renovar": ["deteriorar"],
    "resistente": ["frágil"],
    "responsável": ["irresponsável"],
    "retardar": ["acelerar"],
    "retornar": ["partir"],
    "revelar": ["esconder"],
    "rico": ["pobre"],
    "rígido": ["flexível"],
    "romper": ["unir"],
    "rude": ["gentil"],
    "ruidoso": ["silencioso"],
    "sair": ["entrar"],
    "salvar": ["condenar"],
    "saudável": ["doente"],
    "seco": ["molhado"],
    "seguro": ["inseguro"],
    "selvagem": ["doméstico"],
    "sempre": ["nunca"],
    "separado": ["unido"],
    "sereno": ["agitado"],
    "sério": ["brincalhão"],
    "simples": ["complexo"],
    "sincero": ["falso"],
    "sob": ["sobre"],
    "social": ["anti-social"],
    "soltar": ["prender"],
    "sombrio": ["luminoso"],
    "sorte": ["azar"],
    "suave": ["áspero"],
    "subir": ["descer"],
    "submeter": ["rebelar"],
    "subordinado": ["superior"],
    "sucesso": ["fracasso"],
    "suficiente": ["insuficiente"],
    "sujo": ["limpo"],
    "superior": ["inferior"],
    "suspeita": ["confiança"],
    "tarde": ["cedo"],
    "temerário": ["prudente"],
    "temporário": ["permanente"],
    "término": ["início"],
    "tímido": ["atrevido"],
    "tolerante": ["intolerante"],
    "tolo": ["sábio"],
    "total": ["parcial"],
    "trabalho": ["descanso"],
    "tranquilo": ["inquieto"],
    "transparente": ["opaco"],
    "triste": ["alegre"],
    "tudo": ["nada"],
    "último": ["primeiro"],
    "unido": ["separado"],
    "útil": ["inútil"],
    "válido": ["inválido"],
    "vazio": ["cheio"],
    "velho": ["novo"],
    "vender": ["comprar"],
    "verdade": ["mentira"],
    "vício": ["virtude"],
    "vitória": ["derrota"],
    "vivo": ["morto"],
    "voluntário": ["involuntário"],
    "vulnerável": ["invulnerável"],
    "zeloso": ["negligente"],

    // --- Novas adições para expandir a lista com 200+ antônimos diferentes ---

    // Mais Adjetivos
    "abençoado": ["amaldiçoado", "desgraçado"],
    "acessível": ["inacessível", "restrito"],
    "acertado": ["errado", "equivocado"],
    "acessível": ["inacessível"],
    "acabado": ["inacabado", "começado"],
    "acostumado": ["desacostumado", "estranho"],
    "adequado": ["inadequado", "impróprio"],
    "adiantado": ["atrasado", "retardado"],
    "administrável": ["inadministrável"],
    "afável": ["inflexível", "ríspido"],
    "afinado": ["desafinado"],
    "agradável": ["desagradável", "repugnante"],
    "aguçado": ["obtuso", "embotado"],
    "ajuizado": ["insensato", "desajuizado"],
    "alado": ["áptero"],
    "aliviado": ["oprimido", "pesado"],
    "alternado": ["contínuo", "sequencial"],
    "amplo": ["estreito", "reduzido"],
    "analítico": ["sintético", "holístico"],
    "ancestral": ["descendente", "futuro"],
    "anormal": ["normal", "comum"],
    "aparente": ["disfarçado", "oculto"],
    "apropriado": ["inapropriado", "indevido"],
    "aprovado": ["reprovado", "vetado"],
    "ardente": ["gélido", "frio"],
    "armado": ["desarmado"],
    "assente": ["dissenso", "discordância"],
    "atento": ["desatento", "distraído"],
    "atraente": ["repelente", "desinteressante"],
    "autêntico": ["falso", "artificial"],
    "ávido": ["desinteressado", "apático"],
    "básico": ["avançado", "complexo"],
    "benéfico": ["maléfico", "prejudicial"],
    "bissexual": ["heterossexual", "homossexual"], // Adicionei exemplos de orientação sexual para diversificar
    "brilhante": ["fosco", "opaco", "obscuro"],
    "cativante": ["repelente", "aborrecido"],
    "certo": ["incerto", "duvidoso"],
    "cíclico": ["linear", "sequencial"],
    "civilizado": ["selvagem", "bárbaro"],
    "coletivo": ["individual", "pessoal"],
    "colorido": ["incolor", "monocromático"],
    "concreto": ["abstrato", "imaterial"],
    "confiável": ["não confiável", "enganoso"],
    "congelado": ["derretido", "quente"],
    "confortável": ["desconfortável", "incômodo"],
    "conhecido": ["desconhecido", "ignorado"],
    "conseqüente": ["inconsequente"],
    "considerado": ["desconsiderado", "ignorado"],
    "constante": ["inconstante", "variável"],
    "construtivo": ["destrutivo", "nocivo"],
    "contínuo": ["descontínuo", "intermitente"],
    "conveniente": ["inconveniente", "impróprio"],
    "convergente": ["divergente"],
    "cooperativo": ["não cooperativo", "competitivo"],
    "corajoso": ["covarde", "temeroso"],
    "crescente": ["decrescente", "minguante"],
    "culpado": ["inocente", "inocentado"],
    "decente": ["indecente", "obsceno"],
    "decisivo": ["indeciso", "hesitante"],
    "declarado": ["oculto", "secreto"],
    "defensivo": ["ofensivo"],
    "deliberado": ["acidental", "impensado"],
    "dependente": ["independente", "autônomo"],
    "desejável": ["indesejável", "repugnante"],
    "desenvolvido": ["subdesenvolvido", "atrasado"],
    "desligado": ["ligado", "conectado"],
    "desocupado": ["ocupado", "cheio"],
    "detalhista": ["generalista", "superficial"],
    "determinante": ["indeterminante"],
    "direcionado": ["indirecionado", "aleatório"],
    "distinto": ["indistinto", "comum"],
    "divergente": ["convergente"],
    "dominante": ["submisso", "subserviente"],
    "educado": ["mal-educado", "grosseiro"],
    "efêmero": ["duradouro", "eterno"],
    "elegível": ["inelegível"],
    "emocional": ["racional", "insensível"],
    "empático": ["apático", "insensível"],
    "endêmico": ["pandêmico", "global"],
    "energético": ["letárgico", "apático"],
    "enfermo": ["saudável", "forte"],
    "engraçado": ["chato", "sem graça"],
    "específico": ["genérico", "abrangente"],
    "espesso": ["fino", "raro"],
    "essencial": ["dispensável", "supérfluo"],
    "estável": ["instável", "variável"],
    "estimulante": ["deprimente", "desanimador"],
    "estranho": ["familiar", "conhecido"],
    "exato": ["inexato", "aproximado"],
    "exclusivo": ["inclusivo", "comum"],
    "experiente": ["inexperiente", "novato"],
    "explícito": ["implícito", "oculto"],
    "extenso": ["curto", "reduzido"],
    "externo": ["interno", "interior"],
    "extravagante": ["econômico", "moderado"],

    // Mais Verbos
    "acabar": ["começar", "iniciar"],
    "acertar": ["errar", "falhar"],
    "afastar": ["aproximar", "achegar"],
    "aliviar": ["piorar", "agravar"],
    "atacar": ["defender", "proteger"],
    "atrair": ["repelir", "afastar"],
    "aumentar": ["diminuir", "reduzir"],
    "beneficiar": ["prejudicar", "danificar"],
    "bloquear": ["desbloquear", "liberar"],
    "castigar": ["recompensar", "perdoar"],
    "cativar": ["repelir", "desencantar"],
    "ceder": ["resistir", "insistir"],
    "censurar": ["elogiar", "aprovar"],
    "cessar": ["continuar", "prosseguir"],
    "cooperar": ["competir", "rivalizar"],
    "criticar": ["elogiar", "aprovar"],
    "decidir": ["hesitar", "indeciso"],
    "declinar": ["aceitar", "ascender"],
    "deduzir": ["adicionar", "somar"],
    "deitar": ["levantar", "erguer"],
    "demitir": ["admitir", "contratar"],
    "depositar": ["retirar", "sacar"],
    "derreter": ["congelar", "solidificar"],
    "desaparecer": ["aparecer", "surgir"],
    "desatar": ["atar", "amarrar"],
    "descer": ["subir", "elevar"],
    "desconectar": ["conectar", "ligar"],
    "desconstruir": ["construir", "edificar"],
    "desfrutar": ["sofrer", "padecer"],
    "desistir": ["insistir", "persistir"],
    "desligar": ["ligar", "conectar"],
    "desobedecer": ["obedecer", "submeter"],
    "desvalorizar": ["valorizar", "superestimar"],
    "difamar": ["elogiar", "defender"],
    "disputar": ["concordar", "ceder"],
    "dissolver": ["solidificar", "condensar"],
    "distanciar": ["aproximar", "unir"],
    "divorciar": ["casar", "unir"],
    "duvidar": ["acreditar", "confiar"],
    "elevar": ["rebaixar", "diminuir"],
    "eliminar": ["incluir", "manter"],
    "emocionar": ["indiferenciar", "entristecer"],
    "esconder": ["mostrar", "revelar"],
    "esvaziar": ["encher", "preencher"],
    "evitar": ["enfrentar", "procurar"],
    "expandir": ["contrair", "reduzir"],
    "expor": ["ocultar", "proteger"],
    "expulsar": ["admitir", "acolher"],

    // Mais Substantivos
    "abundância": ["escassez", "falta"],
    "aceitação": ["rejeição", "recusa"],
    "acerto": ["erro", "engano"],
    "acordo": ["desacordo", "divergência"],
    "aliança": ["desunião", "ruptura"],
    "ascensão": ["declínio", "queda"],
    "ataque": ["defesa", "proteção"],
    "aversão": ["atração", "afeição"],
    "benefício": ["prejuízo", "malefício"],
    "calamidade": ["bênção", "sorte"],
    "cativeiro": ["liberdade", "soltura"],
    "caos": ["ordem", "harmonia"],
    "certeza": ["dúvida", "incerteza"],
    "comédia": ["tragédia", "drama"],
    "conflito": ["paz", "harmonia"],
    "concordância": ["discordância", "desacordo"],
    "confiança": ["desconfiança", "ceticismo"],
    "conforto": ["desconforto", "incômodo"],
    "conexão": ["desconexão", "separação"],
    "conquista": ["derrota", "fracasso"],
    "culpa": ["inocência", "isenção"],
    "declínio": ["ascensão", "crescimento"],
    "demissão": ["admissão", "contratação"],
    "depressão": ["euforia", "ânimo"],
    "derrota": ["vitória", "sucesso"],
    "desacordo": ["acordo", "concordância"],
    "desafeto": ["afeto", "afeição"],
    "desânimo": ["ânimo", "entusiasmo"],
    "desastre": ["milagre", "sorte"],
    "desavença": ["acordo", "paz"],
    "desconhecimento": ["conhecimento", "sabedoria"],
    "descontentamento": ["contentamento", "satisfação"],
    "desesperança": ["esperança", "otimismo"],
    "desgraça": ["graça", "sorte"],
    "desvantagem": ["vantagem", "benefício"],
    "direita": ["esquerda"],
    "discordância": ["concordância", "acordo"],
    "discórdia": ["harmonia", "paz"],
    "distância": ["proximidade", "cercania"],
    "divisão": ["unidade", "união"],
    "domínio": ["submissão", "dependência"],
    "doença": ["saúde", "cura"],
    "dúvida": ["certeza", "convicção"],
    "economia": ["desperdício", "esbanjamento"],
    "eficácia": ["ineficácia", "incompetência"],
    "entrada": ["saída", "êxodo"],
    "erro": ["acerto", "correção"],
    "escassez": ["abundância", "excesso"],
    "escuridão": ["luz", "claridade"],
    "esperança": ["desespero", "descrença"],
    "evolução": ["involução", "regressão"],
    "expansão": ["contração", "redução"],
    "exaustão": ["vigor", "energia"],
    "êxito": ["fracasso", "insucesso"],
    "exterior": ["interior", "íntimo"],

    // Mais Advérbios
    "aleatoriamente": ["sistematicamente", "intencionalmente"],
    "amplamente": ["restritamente", "limitadamente"],
    "analiticamente": ["sinteticamente", "holisticamente"],
    "anteriormente": ["posteriormente", "futuramente"],
    "aparentemente": ["realmente", "verdadeiramente"],
    "apropriadamente": ["inadequadamente", "impropriamente"],
    "aproximadamente": ["exatamente", "precisamente"],
    "assiduamente": ["ocasionalmente", "raramente"],
    "atentamente": ["desatentamente", "distraidamente"],
    "atraentemente": ["repugnantemente", "desinteressantemente"],
    "basicamente": ["avançadamente", "detalhadamente"],
    "beneficamente": ["maleficamente", "prejudicialmente"],
    "brilhantemente": ["opacamente", "obscuramente"],
    "calmamente": ["agitadamente", "nervosamente"],
    "candidamente": ["ardilosamente", "enganosamente"],
    "cativantemente": ["repelentemente", "aborrecidamente"],
    "certamente": ["incertamente", "duvidosamente"],
    "civilizadamente": ["selvagemente", "barbaramente"],
    "coletivamente": ["individualmente", "separadamente"],
    "completamente": ["parcialmente", "incompletamente"],
    "confiante": ["desconfiado"],
    "conforme": ["desconforme", "irregular"],
    "consecutivamente": ["intermitentemente", "aleatoriamente"],
    "consideravelmente": ["insignificantemente", "pouco"],
    "construtivamente": ["destrutivamente", "nocivamente"],
    "continuamente": ["intermitentemente", "descontinuamente"],
    "convenientemente": ["inconvenientemente", "impropriamente"],
    "cooperativamente": ["competitivamente", "individualmente"],
    "corajosamente": ["covardemente", "medrosamente"],
    "crescentemente": ["decrescentemente", "diminuindo"],
    "culpadamente": ["inocentemente", "sem culpa"],
    "decentemente": ["indecentemente", "obscenamente"],
    "decisivamente": ["indecisivamente", "hesitantemente"],
    "declaradamente": ["secretamente", "ocultamente"],
    "defensivamente": ["ofensivamente"],
    "deliberadamente": ["acidentalmente", "impensadamente"],
    "dependentemente": ["independentemente", "autonomamente"],
    "desejavelmente": ["indesejavelmente", "repugnantemente"],
    "desligadamente": ["ligadamente", "conectadamente"],
    "detalhadamente": ["generalizadamente", "superficialmente"],
    "determinantemente": ["indeterminadamente"],
    "direcionadamente": ["indirecionadamente", "aleatoriamente"],
    "distintamente": ["indistintamente", "comumente"],
    "divergentemente": ["convergentemente"],
    "dominantemente": ["submissivamente", "subservientemente"],
    "educadamente": ["mal-educadamente", "grosseiramente"],
    "efemeramente": ["duradouramente", "eternamente"],
    "elegivelmente": ["inelegivelmente"],
    "emocionalmente": ["racionalmente", "insensivelmente"],
    "empaticamente": ["apaticamente", "insensivelmente"],
    "energeticamente": ["letargicamente", "apaticamente"],
    "engraçadamente": ["chatamente", "sem graça"],
    "especificamente": ["genericamente", "abrangentemente"],
    "espessamente": ["finamente", "raramente"],
    "essencialmente": ["dispensavelmente", "supérfluamente"],
    "estavelmente": ["instavelmente", "variavelmente"],
    "estimulantemente": ["deprimentemente", "desanimadoramente"],
    "estranhamente": ["familiarmente", "comumente"],
    "exatamente": ["inexatamente", "aproximadamente"],
    "exclusivamente": ["inclusivamente", "comumente"],
    "experientemente": ["inexperientemente", "novatamente"],
    "explicitamente": ["implicitamente", "ocultamente"],
    "extensivamente": ["curtamente", "reduzidamentemente"],
    "externamente": ["internamente", "interiormente"],
    "extravagantemente": ["economicamente", "moderadamente"],
    "fielmente": ["infielmente", "traidoramente"],
    "formalmente": ["informalmente", "casualmentemente"],
    "fortuitamente": ["deliberadamente", "intencionalmente"],
    "frequentemente": ["raramente", "ocasionalmente"],
    "globalmente": ["localmente", "regionalmente"],
    "gradualmente": ["abruptamente", "rapidamente"],
    "gratuitamente": ["pagamente", "onerosamente"],
    "historicamente": ["futuramente", "contemporaneamente"],
    "idealmente": ["realisticamente", "praticamente"],
    "ilegalmente": ["legalmente", "licitamente"],
    "ilicitamente": ["licitamente", "legalmente"],
    "imediatamente": ["posteriormente", "lentamente"],
    "imperfeitamente": ["perfeitamente", "completamente"],
    "impossivelmente": ["possivelmente", "provavelmente"],
    "impulsivamente": ["criteriosamente", "racionalmente"],
    "inalteravelmente": ["mutavelmente", "variadamente"],
    "inconscientemente": ["conscientemente", "voluntariamente"],
    "independente": ["dependente"],
    "indubitavelmente": ["duvidosamente", "incertamente"],
    "infinitamente": ["finitamente", "limitadamente"],
    "infelizmente": ["felizmente", "sortudamente"],
    "injustamente": ["justamente", "equitativamente"],
    "inocentemente": ["culpadamente", "maliciosamente"],
    "inquestionavelmente": ["questionavelmente", "discutivelmente"],
    "insensivelmente": ["sensivelmente", "empaticamente"],
    "insignificantemente": ["significativamente", "importante"],
    "instantaneamente": ["lentamente", "gradualmente"],
    "intencionalmente": ["acidentalmente", "involuntariamente"],
    "interessantemente": ["desinteressantemente", "monotonamente"],
    "internamente": ["externamente", "exteriormente"],
    "inutilmente": ["utilmente", "proveitosamente"],
    "involuntariamente": ["voluntariamente", "deliberadamente"],
    "legalmente": ["ilegalmente", "proibidamentemente"],
    "legitimamente": ["ilegitimamente", "falsamente"],
    "lentamente": ["rapidamente", "pressurosamente"],
    "livremente": ["prisioneiramente", "obrigatoriamente"],
    "localmente": ["globalmente", "nacionalmente"],
    "logicamente": ["ilógicamente", "irracionalmente"],
    "maiormente": ["menormente", "secundariamente"],
    "manifestamente": ["ocultamente", "secretamente"],
    "metodicamente": ["caoticamente", "desorganizadamente"],
    "modestamente": ["arrogantemente", "presunçosamente"],
    "naturalmente": ["artificialmente", "forçadamente"],
    "necessariamente": ["desnecessariamente", "opcionalmente"],
    "negativamente": ["positivamente", "afirmativamente"],
    "nervosamente": ["calmamente", "tranquilamente"],
    "nitidamente": ["obscuramente", "vagamene"],
    "normalmente": ["anormalmente", "excepcionalmente"],
    "notavelmente": ["insignificantemente", "comumente"],
    "ocasionalmente": ["frequentemente", "constantemente"],
    "ofensivamente": ["defensivamente", "pacificamente"],
    "oficialmente": ["extraoficialmente", "informalmente"],
    "opressivamente": ["liberadamente", "livremente"],
    "otimista": ["pessimista"],
    "pacificamente": ["conflituosamente", "agressivamente"],
    "parcialmente": ["totalmente", "completamente"],
    "passivamente": ["ativamente", "dinamicamente"],
    "perigosamente": ["seguramente", "salvadoramente"],
    "periodicamentemente": ["constantemente", "irregularmente"],
    "persistentemente": ["desistindo", "cedendo"],
    "piormente": ["melhormente", "otimamente"],
    "plenamente": ["parcialmente", "incompletamente"],
    "politicamente": ["apoliticamente", "socialmente"],
    "popularmente": ["elitistamente", "impopularmente"],
    "positivamente": ["negativamente", "criticamente"],
    "possivelmente": ["impossivelmente", "improvavelmente"],
    "potencialmente": ["atualmente", "realmente"],
    "precisamente": ["aproximadamente", "vagamente"],
    "preocupadamente": ["despreocupadamente", "tranquilamente"],
    "primariamente": ["secundariamente", "finalmente"],
    "prioritariamente": ["secundariamente", "por último"],
    "provavelmente": ["improvavelmente", "certamente não"],
    "provisoriamente": ["definitivamente", "permanentemente"],
    "publicamente": ["secretamente", "privadamente"],
    "puramente": ["impureza", "misto"],
    "qualificadamente": ["desqualificadamente", "mal"],
    "rapidamente": ["lentamente", "devagar"],
    "racionalmente": ["irracionalmente", "emocionalmente"],
    "realmente": ["irrealmente", "ficticiamente"],
    "regularmente": ["irregularmente", "raramente"],
    "relativamente": ["absolutamente", "totalmente"],
    "religiosamente": ["irreligiosamente", "secularmente"],
    "remotamente": ["proximamente", "localmente"],
    "repetidamente": ["ocasionalmente", "raramente"],
    "responsavelmente": ["irresponsavelmente", "negligentemente"],
    "rigidamente": ["flexivelmente", "brandamente"],
    "rotineiramente": ["excepcionalmente", "incomumente"],
    "seguramente": ["inseguramente", "perigosamente"],
    "selvagemente": ["domesticadamente", "civilizadamente"],
    "separadamente": ["juntamente", "unidamente"],
    "seriamente": ["brincando", "levianamente"],
    "silenciosamente": ["barulhentamente", "ruidosamente"],
    "simbolicamente": ["literalmente", "diretamente"],
    "simplesmente": ["complicadamente", "elaboradamente"],
    "sinceramente": ["falsamente", "enganosamente"],
    "soberbamente": ["humildemente", "modestamente"],
    "socialmente": ["anti-socialmente", "individualmente"],
    "solitariamente": ["acompanhado", "em grupo"],
    "suficientemente": ["insuficientemente", "pouco"],
    "subjetivamente": ["objetivamente", "imparcialmente"],
    "subitamente": ["gradualmente", "lentamente"],
    "superiormente": ["inferiormente", "abaixo"],
    "sutilmente": ["abertamente", "explicitamente"],
    "teoricamente": ["praticamente", "realisticamente"],
    "terrivelmente": ["maravilhosamente", "excelentemente"],
    "totalmente": ["parcialmente", "incompletamente"],
    "tranquilamente": ["agitadamente", "nervosamente"],
    "transparentemente": ["opacamente", "obscuramente"],
    "utilmente": ["inutilmente", "desnecessariamente"],
    "validamente": ["invalidamente", "ilegitimamente"],
    "vagarosamente": ["rapidamente", "pressurosamente"],
    "verdadeiramente": ["falsamente", "enganosamente"],
    "violentamente": ["calmamente", "pacificamente"],
    "visivelmente": ["invisivelmente", "ocultamente"],
    "vitalmente": ["insignificantemente", "irrelevante"],
    "voluntariamente": ["involuntariamente", "compulsoriamente"],
    "vulneravelmente": ["invulneravelmente", "protegidamente"],
    "zelosamente": ["negligentemente", "descuidadamente"]
};