// cores.js

/**
 * @file Dicionário abrangente de cores em Português do Brasil.
 * Contém mapeamentos de nomes de cores para seus códigos hexadecimal, RGB e exemplos de objetos comuns com essa cor.
 * A lista é organizada por tonalidade para facilitar a consulta.
 * @author [Jonas Guinami]
 * @version 1.0.0
 */

/**
 * Objeto que mapeia nomes de cores (chaves) para um objeto com suas propriedades:
 * `nome_pt`: Nome da cor em português.
 * `hex`: Código hexadecimal da cor.
 * `rgb`: Código RGB da cor (string "R,G,B").
 * `objetos_comuns`: Array de exemplos de objetos que geralmente possuem essa cor.
 * @type {Object<string, {nome_pt: string, hex: string, rgb: string, objetos_comuns: string[]}>}
 */
const CORES_DATA = {
    // Cores Neutras e Monocromáticas (Tonalidade: Preto, Branco, Cinza)
    "preto": { nome_pt: "preto", hex: "#000000", rgb: "0,0,0", objetos_comuns: ["noite", "carvão", "pneu", "asfalto", "café preto"] },
    "branco": { nome_pt: "branco", hex: "#FFFFFF", rgb: "255,255,255", objetos_comuns: ["neve", "nuvem", "papel", "leite", "sal"] },
    "cinza": { nome_pt: "cinza", hex: "#808080", rgb: "128,128,128", objetos_comuns: ["nuvem", "pedra", "chumbo", "cimento"] },
    "cinza claro": { nome_pt: "cinza claro", hex: "#D3D3D3", rgb: "211,211,211", objetos_comuns: ["névoa", "fumaça leve"] },
    "cinza escuro": { nome_pt: "cinza escuro", hex: "#A9A9A9", rgb: "169,169,169", objetos_comuns: ["concreto", "grafite"] },
    "prata": { nome_pt: "prata", hex: "#C0C0C0", rgb: "192,192,192", objetos_comuns: ["jóia", "talher", "metal"] },
    "chumbo": { nome_pt: "chumbo", hex: "#696969", rgb: "105,105,105", objetos_comuns: ["metal", "dia nublado"] },
    "carvão": { nome_pt: "carvão", hex: "#36454F", rgb: "54,69,79", objetos_comuns: ["carvão vegetal", "fumaca escura"] },
    "neve": { nome_pt: "neve", hex: "#FFFAFA", rgb: "255,250,250", objetos_comuns: ["neve fresca", "algodão"] },
    "marfim": { nome_pt: "marfim", hex: "#FFFFF0", rgb: "255,255,240", objetos_comuns: ["dente de elefante", "tecido antigo"] },
    "pérola": { nome_pt: "pérola", hex: "#F5F5DC", rgb: "245,245,220", objetos_comuns: ["pérola", "concha"] },
    "bege": { nome_pt: "bege", hex: "#F5F5DC", rgb: "245,245,220", objetos_comuns: ["areia clara", "linho"] },
    "creme": { nome_pt: "creme", hex: "#FFFDD0", rgb: "255,253,208", objetos_comuns: ["creme lácteo", "baunilha"] },

    // Tons de Vermelho
    "vermelho": { nome_pt: "vermelho", hex: "#FF0000", rgb: "255,0,0", objetos_comuns: ["maçã", "morango", "sangue", "pimenta"] },
    "vermelho escuro": { nome_pt: "vermelho escuro", hex: "#8B0000", rgb: "139,0,0", objetos_comuns: ["cereja escura", "vinho tinto"] },
    "vermelho vivo": { nome_pt: "vermelho vivo", hex: "#FF2400", rgb: "255,36,0", objetos_comuns: ["chama", "sinal de pare"] },
    "vermelho tomate": { nome_pt: "vermelho tomate", hex: "#FF6347", rgb: "255,99,71", objetos_comuns: ["tomate maduro"] },
    "vermelho cereja": { nome_pt: "vermelho cereja", hex: "#DE3163", rgb: "222,49,99", objetos_comuns: ["cereja", "esmalte"] },
    "vermelho rubi": { nome_pt: "vermelho rubi", hex: "#E0115F", rgb: "224,17,95", objetos_comuns: ["rubi", "pedra preciosa"] },
    "carmim": { nome_pt: "carmim", hex: "#960018", rgb: "150,0,24", objetos_comuns: ["batom", "manto real"] },
    "escarlate": { nome_pt: "escarlate", hex: "#FF2400", rgb: "255,36,0", objetos_comuns: ["seda", "uniforme militar antigo"] },
    "bordô": { nome_pt: "bordô", hex: "#800020", rgb: "128,0,32", objetos_comuns: ["vinho bordô", "tapeçaria"] },
    "marsala": { nome_pt: "marsala", hex: "#B54D50", rgb: "181,77,80", objetos_comuns: ["vinho marsala", "couro"] },
    "sangue": { nome_pt: "sangue", hex: "#880808", rgb: "136,8,8", objetos_comuns: ["sangue coagulado"] },
    "tijolo": { nome_pt: "tijolo", hex: "#CB4154", rgb: "203,65,84", objetos_comuns: ["tijolo", "telha"] },
    "telha": { nome_pt: "telha", hex: "#914336", rgb: "145,67,54", objetos_comuns: ["telha de barro"] },
    "coral": { nome_pt: "coral", hex: "#FF7F50", rgb: "255,127,80", objetos_comuns: ["coral marinho"] },
    "salmão": { nome_pt: "salmão", hex: "#FA8072", rgb: "250,128,114", objetos_comuns: ["salmão (peixe)"] },
    "vermelho pastel": { nome_pt: "vermelho pastel", hex: "#FFCCCB", rgb: "255,204,203", objetos_comuns: ["bala de goma", "roupa de bebê"] },

    // Tons de Rosa
    "rosa": { nome_pt: "rosa", hex: "#FFC0CB", rgb: "255,192,203", objetos_comuns: ["flor", "porco", "algodão doce"] },
    "rosa choque": { nome_pt: "rosa choque", hex: "#FC0FC0", rgb: "252,15,192", objetos_comuns: ["marca-texto", "roupa de festa"] },
    "rosa claro": { nome_pt: "rosa claro", hex: "#FFB6C1", rgb: "255,182,193", objetos_comuns: ["flor de cerejeira"] },
    "rosa escuro": { nome_pt: "rosa escuro", hex: "#E75480", rgb: "231,84,128", objetos_comuns: ["flor de lótus"] },
    "rosa bebê": { nome_pt: "rosa bebê", hex: "#F4C2C2", rgb: "244,194,194", objetos_comuns: ["roupa de bebê"] },
    "rosa chiclete": { nome_pt: "rosa chiclete", hex: "#FF69B4", rgb: "255,105,180", objetos_comuns: ["chiclete", "maquiagem"] },
    "fúcsia": { nome_pt: "fúcsia", hex: "#FF00FF", rgb: "255,0,255", objetos_comuns: ["flor de fúcsia", "maquiagem vibrante"] },
    "magenta": { nome_pt: "magenta", hex: "#FF00FF", rgb: "255,0,255", objetos_comuns: ["tinta de impressora"] },
    "malva": { nome_pt: "malva", hex: "#9932CC", rgb: "153,50,204", objetos_comuns: ["flor de malva", "tecido delicado"] },
    "carmim rosado": { nome_pt: "carmim rosado", hex: "#DC143C", rgb: "220,20,60", objetos_comuns: ["algodão doce", "rosa avermelhado"] },

    // Tons de Laranja
    "laranja": { nome_pt: "laranja", hex: "#FFA500", rgb: "255,165,0", objetos_comuns: ["laranja", "cenoura", "pôr do sol"] },
    "laranja escuro": { nome_pt: "laranja escuro", hex: "#FF8C00", rgb: "255,140,0", objetos_comuns: ["abóbora", "folha de outono"] },
    "laranja avermelhado": { nome_pt: "laranja avermelhado", hex: "#FF4500", rgb: "255,69,0", objetos_comuns: ["pôr do sol intenso", "fogo"] },
    "laranja pastel": { nome_pt: "laranja pastel", hex: "#FFD700", rgb: "255,215,0", objetos_comuns: ["pêssego", "creme de damasco"] },
    "âmbar": { nome_pt: "âmbar", hex: "#FFBF00", rgb: "255,191,0", objetos_comuns: ["âmbar (resina)", "mel"] },
    "tangerina": { nome_pt: "tangerina", hex: "#F28500", rgb: "242,133,0", objetos_comuns: ["tangerina"] },
    "damasco": { nome_pt: "damasco", hex: "#FBCEB1", rgb: "251,206,177", objetos_comuns: ["damasco (fruta)"] },
    "cobre": { nome_pt: "cobre", hex: "#B87333", rgb: "184,115,51", objetos_comuns: ["metal cobre", "panela antiga"] },
    "ferrugem": { nome_pt: "ferrugem", hex: "#B7410E", rgb: "183,65,14", objetos_comuns: ["ferro enferrujado"] },

    // Tons de Amarelo
    "amarelo": { nome_pt: "amarelo", hex: "#FFFF00", rgb: "255,255,0", objetos_comuns: ["banana", "sol", "limão", "girassol"] },
    "amarelo claro": { nome_pt: "amarelo claro", hex: "#FFFFE0", rgb: "255,255,224", objetos_comuns: ["manteiga", "luz fraca"] },
    "amarelo escuro": { nome_pt: "amarelo escuro", hex: "#B8860B", rgb: "184,134,11", objetos_comuns: ["mostarda", "âmbar escuro"] },
    "amarelo ouro": { nome_pt: "amarelo ouro", hex: "#FFD700", rgb: "255,215,0", objetos_comuns: ["ouro", "moeda"] },
    "amarelo limão": { nome_pt: "amarelo limão", hex: "#FFFACD", rgb: "255,250,205", objetos_comuns: ["limão", "bebida cítrica"] },
    "amarelo canário": { nome_pt: "amarelo canário", hex: "#FFEF00", rgb: "255,239,0", objetos_comuns: ["canário (pássaro)"] },
    "amarelo pastel": { nome_pt: "amarelo pastel", hex: "#FDFD96", rgb: "253,253,150", objetos_comuns: ["bala de caramelo", "pintura suave"] },
    "mostarda": { nome_pt: "mostarda", hex: "#FFDB58", rgb: "255,219,88", objetos_comuns: ["mostarda (condimento)"] },
    "ocre": { nome_pt: "ocre", hex: "#CC7722", rgb: "204,119,34", objetos_comuns: ["terra argilosa"] },
    "dourado": { nome_pt: "dourado", hex: "#FFD700", rgb: "255,215,0", objetos_comuns: ["ouro", "brilho do sol"] },
    "creme": { nome_pt: "creme", hex: "#FFFDD0", rgb: "255,253,208", objetos_comuns: ["sorvete de creme"] },

    // Tons de Verde
    "verde": { nome_pt: "verde", hex: "#008000", rgb: "0,128,0", objetos_comuns: ["grama", "folha", "árvore", "esmeralda"] },
    "verde claro": { nome_pt: "verde claro", hex: "#90EE90", rgb: "144,238,144", objetos_comuns: ["folha nova", "menta"] },
    "verde escuro": { nome_pt: "verde escuro", hex: "#006400", rgb: "0,100,0", objetos_comuns: ["floresta densa", "garrafa"] },
    "verde limão": { nome_pt: "verde limão", hex: "#32CD32", rgb: "50,205,50", objetos_comuns: ["limão verde", "erva"] },
    "verde menta": { nome_pt: "verde menta", hex: "#98FF98", rgb: "152,255,152", objetos_comuns: ["menta", "bala de menta"] },
    "verde água": { nome_pt: "verde água", hex: "#7FFFD4", rgb: "127,255,212", objetos_comuns: ["água rasa do mar", "piscina"] },
    "verde esmeralda": { nome_pt: "verde esmeralda", hex: "#50C878", rgb: "80,200,120", objetos_comuns: ["esmeralda", "pedra preciosa"] },
    "verde oliva": { nome_pt: "verde oliva", hex: "#6B8E23", rgb: "107,142,35", objetos_comuns: ["azeitona", "uniforme militar"] },
    "verde musgo": { nome_pt: "verde musgo", hex: "#8D8B6F", rgb: "141,139,111", objetos_comuns: ["musgo", "pedra úmida"] },
    "verde garrafa": { nome_pt: "verde garrafa", hex: "#00563F", rgb: "0,86,63", objetos_comuns: ["garrafa de vinho", "vidro escuro"] },
    "verde bandeira": { nome_pt: "verde bandeira", hex: "#00923F", rgb: "0,146,63", objetos_comuns: ["bandeira do Brasil"] },
    "verde floresta": { nome_pt: "verde floresta", hex: "#228B22", rgb: "34,139,34", objetos_comuns: ["floresta"] },
    "verde militar": { nome_pt: "verde militar", hex: "#556B2F", rgb: "85,107,47", objetos_comuns: ["uniforme militar"] },
    "verde neon": { nome_pt: "verde neon", hex: "#39FF14", rgb: "57,255,20", objetos_comuns: ["sinal de neon", "marcador de texto"] },
    "verde pistache": { nome_pt: "verde pistache", hex: "#93C572", rgb: "147,197,114", objetos_comuns: ["pistache", "sorvete de pistache"] },
    "verde jade": { nome_pt: "verde jade", hex: "#00A86B", rgb: "0,168,107", objetos_comuns: ["jade (pedra)"] },

    // Tons de Azul
    "azul": { nome_pt: "azul", hex: "#0000FF", rgb: "0,0,255", objetos_comuns: ["céu", "mar", "jeans", "safira"] },
    "azul claro": { nome_pt: "azul claro", hex: "#ADD8E6", rgb: "173,216,230", objetos_comuns: ["céu limpo", "água cristalina"] },
    "azul escuro": { nome_pt: "azul escuro", hex: "#00008B", rgb: "0,0,139", objetos_comuns: ["noite", "oceano profundo"] },
    "azul royal": { nome_pt: "azul royal", hex: "#4169E1", rgb: "65,105,225", objetos_comuns: ["realeza", "uniforme"] },
    "azul celeste": { nome_pt: "azul celeste", hex: "#87CEEB", rgb: "135,206,235", objetos_comuns: ["céu claro", "nuvens brancas"] },
    "azul bebê": { nome_pt: "azul bebê", hex: "#89CFF0", rgb: "137,207,240", objetos_comuns: ["roupa de bebê"] },
    "azul marinho": { nome_pt: "azul marinho", hex: "#000080", rgb: "0,0,128", objetos_comuns: ["oceano", "uniforme militar"] },
    "azul piscina": { nome_pt: "azul piscina", hex: "#00BFFF", rgb: "0,191,255", objetos_comuns: ["piscina"] },
    "azul turquesa": { nome_pt: "azul turquesa", hex: "#40E0D0", rgb: "64,224,208", objetos_comuns: ["turquesa (pedra)", "água de lagoa"] },
    "azul cobalto": { nome_pt: "azul cobalto", hex: "#0047AB", rgb: "0,71,171", objetos_comuns: ["cobalto (pigmento)"] },
    "azul índigo": { nome_pt: "azul índigo", hex: "#4B0082", rgb: "75,0,130", objetos_comuns: ["jeans índigo", "noite profunda"] },
    "azul petróleo": { nome_pt: "azul petróleo", hex: "#004B49", rgb: "0,75,73", objetos_comuns: ["petróleo bruto", "tecido grosso"] },
    "azul safira": { nome_pt: "azul safira", hex: "#0F52BA", rgb: "15,82,186", objetos_comuns: ["safira (pedra)"] },
    "azul céu": { nome_pt: "azul céu", hex: "#87CEEB", rgb: "135,206,235", objetos_comuns: ["céu azul"] },
    "azul acinzentado": { nome_pt: "azul acinzentado", hex: "#6A8B82", rgb: "106,139,130", objetos_comuns: ["nevoeiro matinal"] },
    "azul anil": { nome_pt: "azul anil", hex: "#002366", rgb: "0,35,102", objetos_comuns: ["tinta anil"] },

    // Tons de Roxo/Violeta
    "roxo": { nome_pt: "roxo", hex: "#800080", rgb: "128,0,128", objetos_comuns: ["uva", "berinjela", "ametista"] },
    "violeta": { nome_pt: "violeta", hex: "#EE82EE", rgb: "238,130,238", objetos_comuns: ["flor violeta"] },
    "lavanda": { nome_pt: "lavanda", hex: "#E6E6FA", rgb: "230,230,250", objetos_comuns: ["flor de lavanda", "sabonete"] },
    "lilás": { nome_pt: "lilás", hex: "#C8A2C8", rgb: "200,162,200", objetos_comuns: ["flor de lilás"] },
    "ameixa": { nome_pt: "ameixa", hex: "#673147", rgb: "103,49,71", objetos_comuns: ["ameixa (fruta)"] },
    "púrpura": { nome_pt: "púrpura", hex: "#800080", rgb: "128,0,128", objetos_comuns: ["veste real", "bandeira"] },
    "berinjela": { nome_pt: "berinjela", hex: "#663046", rgb: "102,48,70", objetos_comuns: ["berinjela"] },
    "magenta escuro": { nome_pt: "magenta escuro", hex: "#8B008B", rgb: "139,0,139", objetos_comuns: ["tinta escura"] },
    "índigo": { nome_pt: "índigo", hex: "#4B0082", rgb: "75,0,130", objetos_comuns: ["jeans"] },
    "malva escura": { nome_pt: "malva escura", hex: "#8A2BE2", rgb: "138,43,226", objetos_comuns: ["flor de malva"] },
    "orquídea": { nome_pt: "orquídea", hex: "#DA70D6", rgb: "218,112,214", objetos_comuns: ["flor de orquídea"] },
    "amethysta": { nome_pt: "amethysta", hex: "#9966CC", rgb: "153,102,204", objetos_comuns: ["ametista (pedra)"] },

    // Tons de Marrom/Terra
    "marrom": { nome_pt: "marrom", hex: "#A52A2A", rgb: "165,42,42", objetos_comuns: ["terra", "madeira", "café", "chocolate"] },
    "marrom claro": { nome_pt: "marrom claro", hex: "#D2B48C", rgb: "210,180,140", objetos_comuns: ["areia", "madeira clara"] },
    "marrom escuro": { nome_pt: "marrom escuro", hex: "#654321", rgb: "101,67,33", objetos_comuns: ["chocolate amargo", "café forte"] },
    "bege": { nome_pt: "bege", hex: "#F5F5DC", rgb: "245,245,220", objetos_comuns: ["areia clara", "linho"] },
    "chocolate": { nome_pt: "chocolate", hex: "#D2691E", rgb: "210,105,30", objetos_comuns: ["chocolate ao leite"] },
    "terracota": { nome_pt: "terracota", hex: "#E2725B", rgb: "226,114,91", objetos_comuns: ["vaso de barro", "telhado"] },
    "café": { nome_pt: "café", hex: "#6F4E37", rgb: "111,78,55", objetos_comuns: ["café (bebida)", "grão de café"] },
    "sépia": { nome_pt: "sépia", hex: "#704214", rgb: "112,66,20", objetos_comuns: ["fotografia antiga", "tinta sépia"] },
    "bronze": { nome_pt: "bronze", hex: "#CD7F32", rgb: "205,127,50", objetos_comuns: ["estátua de bronze", "moeda antiga"] },
    "cáqui": { nome_pt: "cáqui", hex: "#C3B091", rgb: "195,176,145", objetos_comuns: ["uniforme militar", "roupa safari"] },
    "caramelo": { nome_pt: "caramelo", hex: "#D8BC8A", rgb: "216,188,138", objetos_comuns: ["caramelo (doce)"] },
    "argila": { nome_pt: "argila", hex: "#B28C7E", rgb: "178,140,126", objetos_comuns: ["argila", "vaso de cerâmica"] },
    "castanho": { nome_pt: "castanho", hex: "#8B4513", rgb: "139,69,19", objetos_comuns: ["castanha", "cabelo castanho"] },
    "ocre avermelhado": { nome_pt: "ocre avermelhado", hex: "#996515", rgb: "153,101,21", objetos_comuns: ["terra avermelhada"] },

    // Tons de Ciano/Turquesa
    "ciano": { nome_pt: "ciano", hex: "#00FFFF", rgb: "0,255,255", objetos_comuns: ["água de piscina", "céu claro"] },
    "turquesa": { nome_pt: "turquesa", hex: "#40E0D0", rgb: "64,224,208", objetos_comuns: ["pedra turquesa", "mar do caribe"] },
    "azul ciano": { nome_pt: "azul ciano", hex: "#00CED1", rgb: "0,206,209", objetos_comuns: ["água tropical"] },
    "verde ciano": { nome_pt: "verde ciano", hex: "#00FF7F", rgb: "0,255,127", objetos_comuns: ["alga marinha"] },
    "verde esmeralda claro": { nome_pt: "verde esmeralda claro", hex: "#66CDAA", rgb: "102,205,170", objetos_comuns: ["esmeralda clara"] },
    "água marinha": { nome_pt: "água marinha", hex: "#7FFFD4", rgb: "127,255,212", objetos_comuns: ["pedra água-marinha", "mar transparente"] },

    // Tons de Púrpura/Bordo (entre Azul e Vermelho)
    "púrpura": { nome_pt: "púrpura", hex: "#800080", rgb: "128,0,128", objetos_comuns: ["veste real", "uvas escuras"] },
    "violeta profundo": { nome_pt: "violeta profundo", hex: "#8A2BE2", rgb: "138,43,226", objetos_comuns: ["flores escuras", "céu crepuscular"] },
    "ameixa escura": { nome_pt: "ameixa escura", hex: "#8E4585", rgb: "142,69,133", objetos_comuns: ["ameixa seca"] },
    "roxo escuro": { nome_pt: "roxo escuro", hex: "#6A0DAD", rgb: "106,13,173", objetos_comuns: ["flor noturna"] },
    "roxo lavanda": { nome_pt: "roxo lavanda", hex: "#967BB6", rgb: "150,123,182", objetos_comuns: ["flor de lavanda"] },
    "roxo uva": { nome_pt: "roxo uva", hex: "#6F2DA8", rgb: "111,45,168", objetos_comuns: ["uva", "suco de uva"] },

    // Tons de Bege/Creme/Areia (Neutros Quentes)
    "areia": { nome_pt: "areia", hex: "#C2B280", rgb: "194,178,128", objetos_comuns: ["areia da praia"] },
    "camurça": { nome_pt: "camurça", hex: "#D6B48E", rgb: "214,180,142", objetos_comuns: ["camurça", "luvas"] },
    "palha": { nome_pt: "palha", hex: "#E4D96F", rgb: "228,217,111", objetos_comuns: ["palha seca", "chapéu de palha"] },
    "baunilha": { nome_pt: "baunilha", hex: "#F3E5AB", rgb: "243,229,171", objetos_comuns: ["baunilha", "sorvete de baunilha"] },
    "amêndoa": { nome_pt: "amêndoa", hex: "#E9DAB4", rgb: "233,218,180", objetos_comuns: ["amêndoa"] },
    "biscoito": { nome_pt: "biscoito", hex: "#E2BF84", rgb: "226,191,132", objetos_comuns: ["biscoito assado"] },

    // Tons Pastel Diversos (suaves e claros)
    "azul pastel": { nome_pt: "azul pastel", hex: "#A7BEDC", rgb: "167,190,220", objetos_comuns: ["nuvem", "céu suave"] },
    "verde pastel": { nome_pt: "verde pastel", hex: "#C7F2CE", rgb: "199,242,206", objetos_comuns: ["folha jovem"] },
    "roxo pastel": { nome_pt: "roxo pastel", hex: "#D0BCE3", rgb: "208,188,227", objetos_comuns: ["flor delicada"] },
    "amarelo pastel": { nome_pt: "amarelo pastel", hex: "#FFFAD0", rgb: "255,250,208", objetos_comuns: ["luz solar suave"] },
    "pêssego": { nome_pt: "pêssego", hex: "#FFE5B4", rgb: "255,229,180", objetos_comuns: ["pêssego (fruta)"] },
    "azul bebê": { nome_pt: "azul bebê", hex: "#89CFF0", rgb: "137,207,240", objetos_comuns: ["roupa de bebê"] },
    "verde bebê": { nome_pt: "verde bebê", hex: "#BFFCC6", rgb: "191,252,198", objetos_comuns: ["folha de recém-nascido"] },
    "rosa bebê": { nome_pt: "rosa bebê", hex: "#F4C2C2", rgb: "244,194,194", objetos_comuns: ["roupa de bebê"] },
    "lavanda clara": { nome_pt: "lavanda clara", hex: "#D8BFD8", rgb: "216,191,216", objetos_comuns: ["flor de lavanda"] },
    "menta": { nome_pt: "menta", hex: "#98FF98", rgb: "152,255,152", objetos_comuns: ["folha de menta", "chiclete"] },
    "celeste": { nome_pt: "celeste", hex: "#B2FFFF", rgb: "178,255,255", objetos_comuns: ["céu azul claro"] },
    "cinza pombo": { nome_pt: "cinza pombo", hex: "#C0CCDA", rgb: "192,204,218", objetos_comuns: ["pombo"] },
    "creme pastel": { nome_pt: "creme pastel", hex: "#FFFDD0", rgb: "255,253,208", objetos_comuns: ["bolo", "glacê"] },

    // Cores vibrantes/saturadas
    "vermelho escarlate": { nome_pt: "vermelho escarlate", hex: "#FF2400", rgb: "255,36,0", objetos_comuns: ["fogo intenso"] },
    "azul elétrico": { nome_pt: "azul elétrico", hex: "#7DF9FF", rgb: "125,249,255", objetos_comuns: ["luz neon", "raio"] },
    "verde limão vibrante": { nome_pt: "verde limão vibrante", hex: "#CCFF00", rgb: "204,255,0", objetos_comuns: ["limão fresco", "marcador"] },
    "amarelo ouro vivo": { nome_pt: "amarelo ouro vivo", hex: "#FFD700", rgb: "255,215,0", objetos_comuns: ["ouro polido", "sol forte"] },
    "roxo elétrico": { nome_pt: "roxo elétrico", hex: "#BF00FF", rgb: "191,0,255", objetos_comuns: ["luz neon roxa"] },
    "laranja brilhante": { nome_pt: "laranja brilhante", hex: "#FF7F00", rgb: "255,127,0", objetos_comuns: ["pôr do sol"] },
    "rosa vibrante": { nome_pt: "rosa vibrante", hex: "#FF007F", rgb: "255,0,127", objetos_comuns: ["flor exótica", "balada"] },
    "ciano brilhante": { nome_pt: "ciano brilhante", hex: "#00FFFF", rgb: "0,255,255", objetos_comuns: ["oceano claro"] },
    "verde neon": { nome_pt: "verde neon", hex: "#39FF14", rgb: "57,255,20", objetos_comuns: ["sinal luminoso"] },
    "azul neon": { nome_pt: "azul neon", hex: "#00F9FF", rgb: "0,249,255", objetos_comuns: ["iluminação especial"] },

    // Cores metálicas (podem ser variações de outras, mas com brilho implícito)
    "ouro": { nome_pt: "ouro", hex: "#FFD700", rgb: "255,215,0", objetos_comuns: ["barra de ouro", "anel"] },
    "bronze": { nome_pt: "bronze", hex: "#CD7F32", rgb: "205,127,50", objetos_comuns: ["medalha de bronze"] },
    "cobre": { nome_pt: "cobre", hex: "#B87333", rgb: "184,115,51", objetos_comuns: ["moeda de cobre", "panela"] },
    "aço": { nome_pt: "aço", hex: "#4682B4", rgb: "70,130,180", objetos_comuns: ["aço inoxidável", "ferramenta"] },
    "alumínio": { nome_pt: "alumínio", hex: "#C0C0C0", rgb: "192,192,192", objetos_comuns: ["latinha de alumínio"] },
    "níquel": { nome_pt: "níquel", hex: "#727472", rgb: "114,116,114", objetos_comuns: ["moeda", "peça metálica"] },
    "titânio": { nome_pt: "titânio", hex: "#878E8E", rgb: "135,142,142", objetos_comuns: ["liga metálica", "implante"] },

    // Cores terrosas e naturais (tons mais suaves e opacos)
    "terracota": { nome_pt: "terracota", hex: "#E2725B", rgb: "226,114,91", objetos_comuns: ["vaso de barro", "telha"] },
    "ocre": { nome_pt: "ocre", hex: "#CC7722", rgb: "204,119,34", objetos_comuns: ["terra argilosa", "pintura rupestre"] },
    "sépia": { nome_pt: "sépia", hex: "#704214", rgb: "112,66,20", objetos_comuns: ["fotografia antiga"] },
    "argila": { nome_pt: "argila", hex: "#B28C7E", rgb: "178,140,126", objetos_comuns: ["argila crua"] },
    "areia escura": { nome_pt: "areia escura", hex: "#9F8E69", rgb: "159,142,105", objetos_comuns: ["areia deserta"] },
    "barro": { nome_pt: "barro", hex: "#A0522D", rgb: "160,82,45", objetos_comuns: ["chão de terra", "cerâmica rústica"] },
    "caramelo escuro": { nome_pt: "caramelo escuro", hex: "#C76211", rgb: "199,98,17", objetos_comuns: ["doce de leite"] },
    "chocolate amargo": { nome_pt: "chocolate amargo", hex: "#3B241D", rgb: "59,36,29", objetos_comuns: ["chocolate 70% cacau"] },
    "esverdeado": { nome_pt: "esverdeado", hex: "#A8B47E", rgb: "168,180,126", objetos_comuns: ["água parada"] },
    "acinzentado": { nome_pt: "acinzentado", hex: "#BDBDBD", rgb: "189,189,189", objetos_comuns: ["dia chuvoso"] },
    "acastanhado": { nome_pt: "acastanhado", hex: "#8B4513", rgb: "139,69,19", objetos_comuns: ["cabelo castanho"] },

    // Cores de gemas e minerais
    "esmeralda": { nome_pt: "esmeralda", hex: "#50C878", rgb: "80,200,120", objetos_comuns: ["esmeralda (pedra)"] },
    "safira": { nome_pt: "safira", hex: "#0F52BA", rgb: "15,82,186", objetos_comuns: ["safira (pedra)"] },
    "rubi": { nome_pt: "rubi", hex: "#E0115F", rgb: "224,17,95", objetos_comuns: ["rubi (pedra)"] },
    "ametista": { nome_pt: "ametista", hex: "#9966CC", rgb: "153,102,204", objetos_comuns: ["ametista (pedra)"] },
    "topázio": { nome_pt: "topázio", hex: "#FFC87C", rgb: "255,200,124", objetos_comuns: ["topázio (pedra)"] },
    "diamante": { nome_pt: "diamante", hex: "#B9F2FF", rgb: "185,242,255", objetos_comuns: ["diamante (pedra)"] },
    "obsidiana": { nome_pt: "obsidiana", hex: "#29191D", rgb: "41,25,29", objetos_comuns: ["obsidiana (rocha vulcânica)"] },
    "jade": { nome_pt: "jade", hex: "#00A86B", rgb: "0,168,107", objetos_comuns: ["jade (pedra)"] },
    "granada": { nome_pt: "granada", hex: "#C40233", rgb: "196,2,51", objetos_comuns: ["granada (pedra)"] },
    "opala": { nome_pt: "opala", hex: "#E9F6F6", rgb: "233,246,246", objetos_comuns: ["opala (pedra)"] },
    "azurite": { nome_pt: "azurite", hex: "#007FFF", rgb: "0,127,255", objetos_comuns: ["azurite (mineral)"] },
    "malaquita": { nome_pt: "malaquita", hex: "#0A6E0A", rgb: "10,110,10", objetos_comuns: ["malaquita (mineral)"] },

    // Mais tons de cores básicas e misturas
    "laranja queimado": { nome_pt: "laranja queimado", hex: "#CC5500", rgb: "204,85,0", objetos_comuns: ["folha seca de outono"] },
    "amarelo queimado": { nome_pt: "amarelo queimado", hex: "#E49B0F", rgb: "228,155,15", objetos_comuns: ["sol poente"] },
    "verde militar": { nome_pt: "verde militar", hex: "#556B2F", rgb: "85,107,47", objetos_comuns: ["camuflagem"] },
    "azul meia-noite": { nome_pt: "azul meia-noite", hex: "#191970", rgb: "25,25,112", objetos_comuns: ["céu noturno", "fundo do mar"] },
    "azul-petróleo": { nome_pt: "azul-petróleo", hex: "#004B49", rgb: "0,75,73", objetos_comuns: ["líquido oleoso"] },
    "roxo ameixa": { nome_pt: "roxo ameixa", hex: "#8A004F", rgb: "138,0,79", objetos_comuns: ["ameixa madura"] },
    "rosa-choque": { nome_pt: "rosa-choque", hex: "#FC0FC0", rgb: "252,15,192", objetos_comuns: ["marcador fluorescente"] },
    "vermelho-vinho": { nome_pt: "vermelho-vinho", hex: "#722F37", rgb: "114,47,55", objetos_comuns: ["vinho tinto"] },
    "amarelo-gema": { nome_pt: "amarelo-gema", hex: "#FFCC33", rgb: "255,204,51", objetos_comuns: ["gema de ovo"] },
    "verde-floresta": { nome_pt: "verde-floresta", hex: "#228B22", rgb: "34,139,34", objetos_comuns: ["árvores na floresta"] },
    "azul-céu": { nome_pt: "azul-céu", hex: "#87CEEB", rgb: "135,206,235", objetos_comuns: ["céu ensolarado"] },
    "laranja-avermelhado": { nome_pt: "laranja-avermelhado", hex: "#FF4500", rgb: "255,69,0", objetos_comuns: ["pôr do sol"] },
    "roxo-azulado": { nome_pt: "roxo-azulado", hex: "#6A5ACD", rgb: "106,90,205", objetos_comuns: ["orquídea azulada"] },
    "vermelho-sangue": { nome_pt: "vermelho-sangue", hex: "#880808", rgb: "136,8,8", objetos_comuns: ["sangue"] },
    "amarelo-creme": { nome_pt: "amarelo-creme", hex: "#FFFDD0", rgb: "255,253,208", objetos_comuns: ["sorvete de creme"] },
    "verde-oliva": { nome_pt: "verde-oliva", hex: "#6B8E23", rgb: "107,142,35", objetos_comuns: ["azeitona"] },
    "azul-claro": { nome_pt: "azul-claro", hex: "#ADD8E6", rgb: "173,216,230", objetos_comuns: ["céu claro"] },
    "rosa-salmão": { nome_pt: "rosa-salmão", hex: "#FA8072", rgb: "250,128,114", objetos_comuns: ["salmão (peixe)"] },
    "marrom-claro": { nome_pt: "marrom-claro", hex: "#CD853F", rgb: "205,133,63", objetos_comuns: ["madeira clara"] },
    "cinza-azulado": { nome_pt: "cinza-azulado", hex: "#6699CC", rgb: "102,153,204", objetos_comuns: ["céu nublado"] },
    "preto-azulado": { nome_pt: "preto-azulado", hex: "#080808", rgb: "8,8,8", objetos_comuns: ["cabelo preto azulado"] },
    "branco-gelo": { nome_pt: "branco-gelo", hex: "#F0F8FF", rgb: "240,248,255", objetos_comuns: ["gelo", "neve"] },
    "cinza-grafite": { nome_pt: "cinza-grafite", hex: "#36454F", rgb: "54,69,79", objetos_comuns: ["grafite"] },
    "vermelho-fogo": { nome_pt: "vermelho-fogo", hex: "#FF4500", rgb: "255,69,0", objetos_comuns: ["chama de fogo"] },
    "amarelo-queimado": { nome_pt: "amarelo-queimado", hex: "#E49B0F", rgb: "228,155,15", objetos_comuns: ["folha de outono"] },
    "verde-jade": { nome_pt: "verde-jade", hex: "#00A86B", rgb: "0,168,107", objetos_comuns: ["jade"] },
    "azul-cobalto": { nome_pt: "azul-cobalto", hex: "#0047AB", rgb: "0,71,171", objetos_comuns: ["pigmento cobalto"] },
    "roxo-profundo": { nome_pt: "roxo-profundo", hex: "#4B0082", rgb: "75,0,130", objetos_comuns: ["céu noturno"] },
    "laranja-coral": { nome_pt: "laranja-coral", hex: "#FF7F50", rgb: "255,127,80", objetos_comuns: ["coral marinho"] },
    "rosa-antigo": { nome_pt: "rosa-antigo", hex: "#C08080", rgb: "192,128,128", objetos_comuns: ["flor seca"] },
    "marrom-avermelhado": { nome_pt: "marrom-avermelhado", hex: "#8B4513", rgb: "139,69,19", objetos_comuns: ["terra vermelha"] },
    "verde-claro": { nome_pt: "verde-claro", hex: "#90EE90", rgb: "144,238,144", objetos_comuns: ["grama fresca"] },
    "azul-real": { nome_pt: "azul-real", hex: "#4169E1", rgb: "65,105,225", objetos_comuns: ["vestimenta real"] },
    "roxo-claro": { nome_pt: "roxo-claro", hex: "#D8BFD8", rgb: "216,191,216", objetos_comuns: ["lavanda"] },
    "amarelo-canário": { nome_pt: "amarelo-canário", hex: "#FFEF00", rgb: "255,239,0", objetos_comuns: ["canário (pássaro)"] },
    "verde-azulado": { nome_pt: "verde-azulado", hex: "#008080", rgb: "0,128,128", objetos_comuns: ["água oceânica"] },
    "laranja-pastel": { nome_pt: "laranja-pastel", hex: "#FDDDCB", rgb: "253,221,203", objetos_comuns: ["pêssego"] },
    "rosa-claro": { nome_pt: "rosa-claro", hex: "#FFB6C1", rgb: "255,182,193", objetos_comuns: ["flor de cerejeira"] },
    "marrom-escuro": { nome_pt: "marrom-escuro", hex: "#654321", rgb: "101,67,33", objetos_comuns: ["chocolate amargo"] },
    "cinza-claro": { nome_pt: "cinza-claro", hex: "#D3D3D3", rgb: "211,211,211", objetos_comuns: ["céu nublado"] },
    "preto-fosco": { nome_pt: "preto-fosco", hex: "#28282B", rgb: "40,40,43", objetos_comuns: ["superfície opaca"] },
    "branco-sujo": { nome_pt: "branco-sujo", hex: "#F5F5DC", rgb: "245,245,220", objetos_comuns: ["papel envelhecido"] },
    "cinza-médio": { nome_pt: "cinza-médio", hex: "#808080", rgb: "128,128,128", objetos_comuns: ["asfalto seco"] },
    "vermelho-sangue-claro": { nome_pt: "vermelho-sangue-claro", hex: "#FF5349", rgb: "255,83,73", objetos_comuns: ["sangue fresco"] },
    "amarelo-bege": { nome_pt: "amarelo-bege", hex: "#F5F5DC", rgb: "245,245,220", objetos_comuns: ["areia clara"] },
    "verde-musgo": { nome_pt: "verde-musgo", hex: "#8D8B6F", rgb: "141,139,111", objetos_comuns: ["musgo em pedra"] },
    "azul-profundo": { nome_pt: "azul-profundo", hex: "#000033", rgb: "0,0,51", objetos_comuns: ["abismo oceânico"] },
    "roxo-púrpura": { nome_pt: "roxo-púrpura", hex: "#800080", rgb: "128,0,128", objetos_comuns: ["vestes reais"] },
    "laranja-terra": { nome_pt: "laranja-terra", hex: "#BF612B", rgb: "191,97,43", objetos_comuns: ["solo argiloso"] },
    "rosa-choque-claro": { nome_pt: "rosa-choque-claro", hex: "#F08080", rgb: "240,128,128", objetos_comuns: ["bala de cereja"] },
    "marrom-avermelhado-escuro": { nome_pt: "marrom-avermelhado-escuro", hex: "#8B0000", rgb: "139,0,0", objetos_comuns: ["terra avermelhada"] },
    "verde-esmeralda-profundo": { nome_pt: "verde-esmeralda-profundo", hex: "#004B49", rgb: "0,75,73", objetos_comuns: ["esmeralda grande"] },
    "azul-noite": { nome_pt: "azul-noite", hex: "#191970", rgb: "25,25,112", objetos_comuns: ["céu estrelado"] },
    "roxo-ametista": { nome_pt: "roxo-ametista", hex: "#9966CC", rgb: "153,102,204", objetos_comuns: ["ametista"] },
    "amarelo-ouro-envelhecido": { nome_pt: "amarelo-ouro-envelhecido", hex: "#B8860B", rgb: "184,134,11", objetos_comuns: ["ouro antigo"] },
    "verde-folha": { nome_pt: "verde-folha", hex: "#7CFC00", rgb: "124,252,0", objetos_comuns: ["folha de árvore"] },
    "azul-celeste-claro": { nome_pt: "azul-celeste-claro", hex: "#B0E0E6", rgb: "176,224,230", objetos_comuns: ["céu limpo"] },
    "laranja-queimado-escuro": { nome_pt: "laranja-queimado-escuro", hex: "#CC5500", rgb: "204,85,0", objetos_comuns: ["folha de outono"] },
    "rosa-claro-pastel": { nome_pt: "rosa-claro-pastel", hex: "#FFDDEE", rgb: "255,221,238", objetos_comuns: ["nuvem rosa"] },
    "marrom-castanho": { nome_pt: "marrom-castanho", hex: "#A0522D", rgb: "160,82,45", objetos_comuns: ["castanha"] },
    "cinza-escuro-metálico": { nome_pt: "cinza-escuro-metálico", hex: "#696969", rgb: "105,105,105", objetos_comuns: ["metal"] },
    "branco-neve": { nome_pt: "branco-neve", hex: "#FFFAFA", rgb: "255,250,250", objetos_comuns: ["neve"] },
    "azul-anil-profundo": { nome_pt: "azul-anil-profundo", hex: "#000080", rgb: "0,0,128", objetos_comuns: ["tinta anil"] },
    "amarelo-ouro-brilhante": { nome_pt: "amarelo-ouro-brilhante", hex: "#FFD700", rgb: "255,215,0", objetos_comuns: ["ouro"] },
    "verde-limão-claro": { nome_pt: "verde-limão-claro", hex: "#32CD32", rgb: "50,205,50", objetos_comuns: ["limão verde"] },
    "azul-água": { nome_pt: "azul-água", hex: "#7FFFD4", rgb: "127,255,212", objetos_comuns: ["água do mar"] },
    "roxo-lavanda-claro": { nome_pt: "roxo-lavanda-claro", hex: "#E6E6FA", rgb: "230,230,250", objetos_comuns: ["lavanda"] },
    "laranja-claro": { nome_pt: "laranja-claro", hex: "#FFDDA0", rgb: "255,221,160", objetos_comuns: ["pêssego"] },
    "rosa-pêssego": { nome_pt: "rosa-pêssego", hex: "#FFDAB9", rgb: "255,218,185", objetos_comuns: ["pêssego"] },
    "marrom-chocolate": { nome_pt: "marrom-chocolate", hex: "#D2691E", rgb: "210,105,30", objetos_comuns: ["chocolate"] },
    "cinza-esfumaçado": { nome_pt: "cinza-esfumaçado", hex: "#BEBEBE", rgb: "190,190,190", objetos_comuns: ["fumaça"] },
    "preto-azabache": { nome_pt: "preto-azabache", hex: "#362D2C", rgb: "54,45,44", objetos_comuns: ["azabache (mineral)"] },
    "branco-nuvem": { nome_pt: "branco-nuvem", hex: "#F8F8FF", rgb: "248,248,255", objetos_comuns: ["nuvem"] },
    "cinza-ardósia": { nome_pt: "cinza-ardósia", hex: "#708090", rgb: "112,128,144", objetos_comuns: ["ardósia"] },
    "vermelho-carmim": { nome_pt: "vermelho-carmim", hex: "#960018", rgb: "150,0,24", objetos_comuns: ["carmim"] },
    "amarelo-dourado": { nome_pt: "amarelo-dourado", hex: "#DAA520", rgb: "218,165,32", objetos_comuns: ["ouro"] },
    "verde-musgo-escuro": { nome_pt: "verde-musgo-escuro", hex: "#5A6250", rgb: "90,98,80", objetos_comuns: ["musgo denso"] },
    "azul-oceano": { nome_pt: "azul-oceano", hex: "#000080", rgb: "0,0,128", objetos_comuns: ["oceano profundo"] },
    "roxo-real": { nome_pt: "roxo-real", hex: "#6A0DAD", rgb: "106,13,173", objetos_comuns: ["vestimenta real"] },
    "laranja-cítrico": { nome_pt: "laranja-cítrico", hex: "#FF8C00", rgb: "255,140,0", objetos_comuns: ["fruta cítrica"] },
    "rosa-claro-quente": { nome_pt: "rosa-claro-quente", hex: "#FFD1DC", rgb: "255,209,220", objetos_comuns: ["floreira"] },
    "marrom-terra": { nome_pt: "marrom-terra", hex: "#A0522D", rgb: "160,82,45", objetos_comuns: ["terra"] },
    "cinza-pérola": { nome_pt: "cinza-pérola", hex: "#EAE0C8", rgb: "234,224,200", objetos_comuns: ["pérola"] },
    "preto-obsidiana": { nome_pt: "preto-obsidiana", hex: "#29191D", rgb: "41,25,29", objetos_comuns: ["obsidiana"] },
    "branco-alabastro": { nome_pt: "branco-alabastro", hex: "#F4F4F0", rgb: "244,244,240", objetos_comuns: ["alabastro (mineral)"] },
    "cinza-ferro": { nome_pt: "cinza-ferro", hex: "#434B4D", rgb: "67,75,77", objetos_comuns: ["ferro"] },
    "vermelho-escarlate-profundo": { nome_pt: "vermelho-escarlate-profundo", hex: "#8B0000", rgb: "139,0,0", objetos_comuns: ["carmesim"] },
    "amarelo-girassol": { nome_pt: "amarelo-girassol", hex: "#FFDA03", rgb: "255,218,3", objetos_comuns: ["girassol"] },
    "verde-floresta-escura": { nome_pt: "verde-floresta-escura", hex: "#0A1E0A", rgb: "10,30,10", objetos_comuns: ["floresta densa"] },
    "azul-oceano-profundo": { nome_pt: "azul-oceano-profundo", hex: "#000040", rgb: "0,0,64", objetos_comuns: ["oceano abissal"] },
    "roxo-uvarana": { nome_pt: "roxo-uvarana", hex: "#5C246E", rgb: "92,36,110", objetos_comuns: ["uvarana (fruta)"] },
    "laranja-abóbora": { nome_pt: "laranja-abóbora", hex: "#FF7518", rgb: "255,117,24", objetos_comuns: ["abóbora"] },
    "rosa-algodão": { nome_pt: "rosa-algodão", hex: "#FFB0C7", rgb: "255,176,199", objetos_comuns: ["algodão doce"] },
    "marrom-castanho-claro": { nome_pt: "marrom-castanho-claro", hex: "#DEB887", rgb: "222,184,135", objetos_comuns: ["castanha clara"] },
    "cinza-rato": { nome_pt: "cinza-rato", hex: "#9E9E9E", rgb: "158,158,158", objetos_comuns: ["rato"] },
    "preto-jet": { nome_pt: "preto-jet", hex: "#343434", rgb: "52,52,52", objetos_comuns: ["jato (combustível)"] },
    "branco-pó": { nome_pt: "branco-pó", hex: "#F8F8FF", rgb: "248,248,255", objetos_comuns: ["pó de talco"] },
    "cinza-chumbo-escuro": { nome_pt: "cinza-chumbo-escuro", hex: "#4B4B4B", rgb: "75,75,75", objetos_comuns: ["chumbo"] },
    "vermelho-terra": { nome_pt: "vermelho-terra", hex: "#A8382A", rgb: "168,56,42", objetos_comuns: ["terra avermelhada"] },
    "amarelo-crepúsculo": { nome_pt: "amarelo-crepúsculo", hex: "#FFB200", rgb: "255,178,0", objetos_comuns: ["pôr do sol"] },
    "verde-musgo-claro": { nome_pt: "verde-musgo-claro", hex: "#C0D6A3", rgb: "192,214,163", objetos_comuns: ["musgo fresco"] },
    "azul-esverdeado": { nome_pt: "azul-esverdeado", hex: "#00CED1", rgb: "0,206,209", objetos_comuns: ["água do mar"] },
    "roxo-berinjela": { nome_pt: "roxo-berinjela", hex: "#663046", rgb: "102,48,70", objetos_comuns: ["berinjela"] },
    "laranja-cenoura": { nome_pt: "laranja-cenoura", hex: "#ED6F27", rgb: "237,111,39", objetos_comuns: ["cenoura"] },
    "rosa-choque-escuro": { nome_pt: "rosa-choque-escuro", hex: "#E03B8A", rgb: "224,59,138", objetos_comuns: ["flor vibrante"] },
    "marrom-café": { nome_pt: "marrom-café", hex: "#6F4E37", rgb: "111,78,55", objetos_comuns: ["café"] },
    "cinza-cimento": { nome_pt: "cinza-cimento", hex: "#8A8F8F", rgb: "138,143,143", objetos_comuns: ["cimento"] },
    "preto-azulado-escuro": { nome_pt: "preto-azulado-escuro", hex: "#00000A", rgb: "0,0,10", objetos_comuns: ["noite profunda"] },
    "branco-giz": { nome_pt: "branco-giz", hex: "#F8F8F8", rgb: "248,248,248", objetos_comuns: ["giz"] },
    "cinza-neutro": { nome_pt: "cinza-neutro", hex: "#6C7A89", rgb: "108,122,137", objetos_comuns: ["metal"] },
    "vermelho-carmim-claro": { nome_pt: "vermelho-carmim-claro", hex: "#FF3366", rgb: "255,51,102", objetos_comuns: ["flor vermelha"] },
    "amarelo-palha": { nome_pt: "amarelo-palha", hex: "#E4D96F", rgb: "228,217,111", objetos_comuns: ["palha"] },
    "verde-pistache": { nome_pt: "verde-pistache", hex: "#93C572", rgb: "147,197,114", objetos_comuns: ["pistache"] },
    "azul-céu-escuro": { nome_pt: "azul-céu-escuro", hex: "#4682B4", rgb: "70,130,180", objetos_comuns: ["céu ao anoitecer"] },
    "roxo-pálido": { nome_pt: "roxo-pálido", hex: "#DCD0FF", rgb: "220,208,255", objetos_comuns: ["flor pálida"] },
    "laranja-bronze": { nome_pt: "laranja-bronze", hex: "#CD7F32", rgb: "205,127,50", objetos_comuns: ["bronze"] },
    "rosa-aveludado": { nome_pt: "rosa-aveludado", hex: "#DB7093", rgb: "219,112,147", objetos_comuns: ["pétala de rosa"] },
    "marrom-argila": { nome_pt: "marrom-argila", hex: "#B28C7E", rgb: "178,140,126", objetos_comuns: ["argila"] },
    "cinza-claro-quente": { nome_pt: "cinza-claro-quente", hex: "#DCDCDC", rgb: "220,220,220", objetos_comuns: ["pedra aquecida"] },
    "preto-carvão-vegetal": { nome_pt: "preto-carvão-vegetal", hex: "#36454F", rgb: "54,69,79", objetos_comuns: ["carvão"] },
    "branco-pérola": { nome_pt: "branco-pérola", hex: "#F5F5DC", rgb: "245,245,220", objetos_comuns: ["pérola"] },
    "cinza-aço": { nome_pt: "cinza-aço", hex: "#4682B4", rgb: "70,130,180", objetos_comuns: ["aço"] },
    "vermelho-terra-queimada": { nome_pt: "vermelho-terra-queimada", hex: "#A0522D", rgb: "160,82,45", objetos_comuns: ["terra queimada"] },
    "amarelo-pastel-claro": { nome_pt: "amarelo-pastel-claro", hex: "#FFFFE0", rgb: "255,255,224", objetos_comuns: ["nuvem ensolarada"] },
    "verde-esmeralda-claro": { nome_pt: "verde-esmeralda-claro", hex: "#66CDAA", rgb: "102,205,170", objetos_comuns: ["esmeralda clara"] },
    "azul-turquesa-claro": { nome_pt: "azul-turquesa-claro", hex: "#AFEEEE", rgb: "175,238,238", objetos_comuns: ["água rasa"] },
    "roxo-ametista-claro": { nome_pt: "roxo-ametista-claro", hex: "#DDA0DD", rgb: "221,160,221", objetos_comuns: ["ametista clara"] },
    "laranja-coral-claro": { nome_pt: "laranja-coral-claro", hex: "#FFB680", rgb: "255,182,128", objetos_comuns: ["coral claro"] },
    "rosa-bebê-claro": { nome_pt: "rosa-bebê-claro", hex: "#FFC0CB", rgb: "255,192,203", objetos_comuns: ["roupa de bebê"] },
    "marrom-cacau": { nome_pt: "marrom-cacau", hex: "#C89582", rgb: "200,149,130", objetos_comuns: ["cacau"] },
    "cinza-pombo-claro": { nome_pt: "cinza-pombo-claro", hex: "#CFCFC4", rgb: "207,207,196", objetos_comuns: ["pombo"] },
    "preto-ônix": { nome_pt: "preto-ônix", hex: "#36454F", rgb: "54,69,79", objetos_comuns: ["ônix (pedra)"] },
    "branco-gesso": { nome_pt: "branco-gesso", hex: "#F0F0F0", rgb: "240,240,240", objetos_comuns: ["gesso"] },
    "cinza-esfumaçado-claro": { nome_pt: "cinza-esfumaçado-claro", hex: "#C0C0C0", rgb: "192,192,192", objetos_comuns: ["fumaça leve"] },
    "vermelho-maçã": { nome_pt: "vermelho-maçã", hex: "#FF0800", rgb: "255,8,0", objetos_comuns: ["maçã"] },
    "amarelo-ovo": { nome_pt: "amarelo-ovo", hex: "#FEEB00", rgb: "254,235,0", objetos_comuns: ["gema de ovo"] },
    "verde-grama": { nome_pt: "verde-grama", hex: "#7CFC00", rgb: "124,252,0", objetos_comuns: ["grama"] },
    "azul-royal-profundo": { nome_pt: "azul-royal-profundo", hex: "#0000CD", rgb: "0,0,205", objetos_comuns: ["realeza"] },
    "roxo-boreal": { nome_pt: "roxo-boreal", hex: "#5C246E", rgb: "92,36,110", objetos_comuns: ["aurora boreal"] },
    "laranja-queimado-avermelhado": { nome_pt: "laranja-queimado-avermelhado", hex: "#A8382A", rgb: "168,56,42", objetos_comuns: ["folha de outono"] },
    "rosa-claro-pálido": { nome_pt: "rosa-claro-pálido", hex: "#FFEBF5", rgb: "255,235,245", objetos_comuns: ["nuvem ao amanhecer"] },
    "marrom-carvalho": { nome_pt: "marrom-carvalho", hex: "#7B3F00", rgb: "123,63,0", objetos_comuns: ["madeira de carvalho"] },
    "cinza-prata-clara": { nome_pt: "cinza-prata-clara", hex: "#EAEAEA", rgb: "234,234,234", objetos_comuns: ["joia de prata"] },
    "preto-zevra": { nome_pt: "preto-zevra", hex: "#343434", rgb: "52,52,52", objetos_comuns: ["zebra"] },
    "branco-óptico": { nome_pt: "branco-óptico", hex: "#F5F5DC", rgb: "245,245,220", objetos_comuns: ["papel brilhante"] },
    "cinza-azulado-escuro": { nome_pt: "cinza-azulado-escuro", hex: "#4682B4", rgb: "70,130,180", objetos_comuns: ["chumbo"] },
    "vermelho-carmim-escuro": { nome_pt: "vermelho-carmim-escuro", hex: "#8B0000", rgb: "139,0,0", objetos_comuns: ["vinho"] },
    "amarelo-solar": { nome_pt: "amarelo-solar", hex: "#FFDF00", rgb: "255,223,0", objetos_comuns: ["sol"] },
    "verde-azulado-escuro": { nome_pt: "verde-azulado-escuro", hex: "#004B49", rgb: "0,75,73", objetos_comuns: ["água profunda"] },
    "azul-noite-profundo": { nome_pt: "azul-noite-profundo", hex: "#000033", rgb: "0,0,51", objetos_comuns: ["noite sem estrelas"] },
    "roxo-vinho": { nome_pt: "roxo-vinho", hex: "#800040", rgb: "128,0,64", objetos_comuns: ["vinho tinto"] },
    "laranja-tijolo": { nome_pt: "laranja-tijolo", hex: "#CB4154", rgb: "203,65,84", objetos_comuns: ["tijolo"] },
    "rosa-magenta": { nome_pt: "rosa-magenta", hex: "#FF00FF", rgb: "255,0,255", objetos_comuns: ["flor"] },
    "marrom-areia": { nome_pt: "marrom-areia", hex: "#F4A460", rgb: "244,164,96", objetos_comuns: ["areia"] },
    "cinza-asfalto": { nome_pt: "cinza-asfalto", hex: "#36454F", rgb: "54,69,79", objetos_comuns: ["asfalto"] },
    "preto-ébono": { nome_pt: "preto-ébono", hex: "#29191D", rgb: "41,25,29", objetos_comuns: ["ébano"] },
    "branco-creme": { nome_pt: "branco-creme", hex: "#FFFDD0", rgb: "255,253,208", objetos_comuns: ["creme"] },
    "cinza-carvão": { nome_pt: "cinza-carvão", hex: "#36454F", rgb: "54,69,79", objetos_comuns: ["carvão"] },
    "vermelho-rosado": { nome_pt: "vermelho-rosado", hex: "#FF6666", rgb: "255,102,102", objetos_comuns: ["flor"] },
    "amarelo-gema-claro": { nome_pt: "amarelo-gema-claro", hex: "#FFEA00", rgb: "255,234,0", objetos_comuns: ["gema de ovo"] },
    "verde-clover": { nome_pt: "verde-clover", hex: "#008000", rgb: "0,128,0", objetos_comuns: ["trevo"] },
    "azul-jeans": { nome_pt: "azul-jeans", hex: "#3B5B92", rgb: "59,91,146", objetos_comuns: ["jeans"] },
    "roxo-malva": { nome_pt: "roxo-malva", hex: "#9932CC", rgb: "153,50,204", objetos_comuns: ["flor"] },
    "laranja-cobre": { nome_pt: "laranja-cobre", hex: "#B87333", rgb: "184,115,51", objetos_comuns: ["cobre"] },
    "rosa-orquídea": { nome_pt: "rosa-orquídea", hex: "#DA70D6", rgb: "218,112,214", objetos_comuns: ["orquídea"] },
    "marrom-castanho-avermelhado": { nome_pt: "marrom-castanho-avermelhado", hex: "#A52A2A", rgb: "165,42,42", objetos_comuns: ["castanha avermelhada"] },
    "cinza-espectro": { nome_pt: "cinza-espectro", hex: "#7F7F7F", rgb: "127,127,127", objetos_comuns: ["fantasma"] },
    "preto-carvão-escuro": { nome_pt: "preto-carvão-escuro", hex: "#292C2F", rgb: "41,44,47", objetos_comuns: ["carvão"] },
    "branco-pérola-clara": { nome_pt: "branco-pérola-clara", hex: "#F5F5DC", rgb: "245,245,220", objetos_comuns: ["pérola"] },
    "cinza-alumínio": { nome_pt: "cinza-alumínio", hex: "#C0C0C0", rgb: "192,192,192", objetos_comuns: ["alumínio"] },
    "vermelho-tijolo-escuro": { nome_pt: "vermelho-tijolo-escuro", hex: "#8A3324", rgb: "138,51,36", objetos_comuns: ["tijolo"] },
    "amarelo-esverdeado": { nome_pt: "amarelo-esverdeado", hex: "#ADFF2F", rgb: "173,255,47", objetos_comuns: ["limão verde"] },
    "verde-militar-escuro": { nome_pt: "verde-militar-escuro", hex: "#4B5320", rgb: "75,83,32", objetos_comuns: ["uniforme"] },
    "azul-denim": { nome_pt: "azul-denim", hex: "#1560BD", rgb: "21,96,189", objetos_comuns: ["denim"] },
    "roxo-violeta-escuro": { nome_pt: "roxo-violeta-escuro", hex: "#4B0082", rgb: "75,0,130", objetos_comuns: ["flor escura"] },
    "laranja-terra-queimada": { nome_pt: "laranja-terra-queimada", hex: "#CC5500", rgb: "204,85,0", objetos_comuns: ["terra"] },
    "rosa-chiclete-claro": { nome_pt: "rosa-chiclete-claro", hex: "#FFB0C7", rgb: "255,176,199", objetos_comuns: ["chiclete"] },
    "marrom-café-escuro": { nome_pt: "marrom-café-escuro", hex: "#4C2F27", rgb: "76,47,39", objetos_comuns: ["café"] },
    "cinza-pó": { nome_pt: "cinza-pó", hex: "#D8D8D8", rgb: "216,216,216", objetos_comuns: ["pó"] },
    "preto-tinta": { nome_pt: "preto-tinta", hex: "#1A1A1A", rgb: "26,26,26", objetos_comuns: ["tinta"] },
    "branco-nuvem-clara": { nome_pt: "branco-nuvem-clara", hex: "#F8F8FF", rgb: "248,248,255", objetos_comuns: ["nuvem"] },
    "cinza-ardósia-claro": { nome_pt: "cinza-ardósia-claro", hex: "#B0C4DE", rgb: "176,196,222", objetos_comuns: ["ardósia"] },
    "vermelho-cobre": { nome_pt: "vermelho-cobre", hex: "#B87333", rgb: "184,115,51", objetos_comuns: ["cobre"] },
    "amarelo-queimado-claro": { nome_pt: "amarelo-queimado-claro", hex: "#FFE6B3", rgb: "255,230,179", objetos_comuns: ["folha seca"] },
    "verde-esmeralda-escura": { nome_pt: "verde-esmeralda-escura", hex: "#006B3C", rgb: "0,107,60", objetos_comuns: ["esmeralda"] },
    "azul-céu-claro-pastel": { nome_pt: "azul-céu-claro-pastel", hex: "#B0E0E6", rgb: "176,224,230", objetos_comuns: ["céu limpo"] },
    "roxo-lavanda-escuro": { nome_pt: "roxo-lavanda-escuro", hex: "#6A5ACD", rgb: "106,90,205", objetos_comuns: ["flor"] },
    "laranja-queimado-claro": { nome_pt: "laranja-queimado-claro", hex: "#FF9966", rgb: "255,153,102", objetos_comuns: ["pôr do sol"] },
    "rosa-pastel-claro": { nome_pt: "rosa-pastel-claro", hex: "#FFDFD9", rgb: "255,223,217", objetos_comuns: ["bala de goma"] },
    "marrom-chocolate-claro": { nome_pt: "marrom-chocolate-claro", hex: "#CD853F", rgb: "205,133,63", objetos_comuns: ["chocolate ao leite"] },
    "cinza-chumbo-claro": { nome_pt: "cinza-chumbo-claro", hex: "#A9A9A9", rgb: "169,169,169", objetos_comuns: ["chumbo"] },
    "preto-azulado-claro": { nome_pt: "preto-azulado-claro", hex: "#3B3B3B", rgb: "59,59,59", objetos_comuns: ["cabelo"] },
    "branco-papel": { nome_pt: "branco-papel", hex: "#FDFDFD", rgb: "253,253,253", objetos_comuns: ["papel"] },
    "cinza-titânio": { nome_pt: "cinza-titânio", hex: "#878E8E", rgb: "135,142,142", objetos_comuns: ["titânio"] },
    "vermelho-rubi-escuro": { nome_pt: "vermelho-rubi-escuro", hex: "#8B0000", rgb: "139,0,0", objetos_comuns: ["rubi"] },
    "amarelo-mostarda-claro": { nome_pt: "amarelo-mostarda-claro", hex: "#E6B654", rgb: "230,182,84", objetos_comuns: ["mostarda"] },
    "verde-oliva-claro": { nome_pt: "verde-oliva-claro", hex: "#9ACD32", rgb: "154,205,50", objetos_comuns: ["azeitona"] },
    "azul-marinho-escuro": { nome_pt: "azul-marinho-escuro", hex: "#000080", rgb: "0,0,128", objetos_comuns: ["oceano"] },
    "roxo-profundo-claro": { nome_pt: "roxo-profundo-claro", hex: "#9370DB", rgb: "147,112,219", objetos_comuns: ["flor"] },
    "laranja-tangerina-claro": { nome_pt: "laranja-tangerina-claro", hex: "#FFC87C", rgb: "255,200,124", objetos_comuns: ["tangerina"] },
    "rosa-salmão-claro": { nome_pt: "rosa-salmão-claro", hex: "#FFC0CB", rgb: "255,192,203", objetos_comuns: ["salmão"] },
    "marrom-areia-claro": { nome_pt: "marrom-areia-claro", hex: "#D2B48C", rgb: "210,180,140", objetos_comuns: ["areia"] },
    "cinza-pérola-claro": { nome_pt: "cinza-pérola-claro", hex: "#EAE0C8", rgb: "234,224,200", objetos_comuns: ["pérola"] },
    "preto-azabache-claro": { nome_pt: "preto-azabache-claro", hex: "#3F3F3F", rgb: "63,63,63", objetos_comuns: ["azabache"] },
    "branco-linho": { nome_pt: "branco-linho", hex: "#FAF0E6", rgb: "250,240,230", objetos_comuns: ["linho"] },
    "cinza-ardósia-escuro": { nome_pt: "cinza-ardósia-escuro", hex: "#2F4F4F", rgb: "47,79,79", objetos_comuns: ["ardósia"] },
    "vermelho-cereja-escuro": { nome_pt: "vermelho-cereja-escuro", hex: "#8B0000", rgb: "139,0,0", objetos_comuns: ["cereja"] },
    "amarelo-claro-bege": { nome_pt: "amarelo-claro-bege", hex: "#FAEBD7", rgb: "250,235,215", objetos_comuns: ["areia"] },
    "verde-folha-escura": { nome_pt: "verde-folha-escura", hex: "#006400", rgb: "0,100,0", objetos_comuns: ["folha de árvore"] },
    "azul-jeans-claro": { nome_pt: "azul-jeans-claro", hex: "#6A99D4", rgb: "106,153,212", objetos_comuns: ["jeans"] },
    "roxo-ametista-escuro": { nome_pt: "roxo-ametista-escuro", hex: "#6A0DAD", rgb: "106,13,173", objetos_comuns: ["ametista"] },
    "laranja-cenoura-claro": { nome_pt: "laranja-cenoura-claro", hex: "#FFA07A", rgb: "255,160,122", objetos_comuns: ["cenoura"] },
    "rosa-choque-vivo": { nome_pt: "rosa-choque-vivo", hex: "#FF007F", rgb: "255,0,127", objetos_comuns: ["flor"] },
    "marrom-café-claro": { nome_pt: "marrom-café-claro", hex: "#A0522D", rgb: "160,82,45", objetos_comuns: ["café"] },
    "cinza-esfumaçado-escuro": { nome_pt: "cinza-esfumaçado-escuro", hex: "#696969", rgb: "105,105,105", objetos_comuns: ["fumaça"] },
    "preto-carvão-claro": { nome_pt: "preto-carvão-claro", hex: "#4C4C4C", rgb: "76,76,76", objetos_comuns: ["carvão"] },
    "branco-marfim": { nome_pt: "branco-marfim", hex: "#FFFFF0", rgb: "255,255,240", objetos_comuns: ["marfim"] },
    "cinza-metálico": { nome_pt: "cinza-metálico", hex: "#A9A9A9", rgb: "169,169,169", objetos_comuns: ["metal"] },
    "vermelho-terra-brilhante": { nome_pt: "vermelho-terra-brilhante", hex: "#E34234", rgb: "227,66,52", objetos_comuns: ["terra"] },
    "amarelo-limão-claro": { nome_pt: "amarelo-limão-claro", hex: "#ADFF2F", rgb: "173,255,47", objetos_comuns: ["limão"] },
    "verde-água-escura": { nome_pt: "verde-água-escura", hex: "#008080", rgb: "0,128,128", objetos_comuns: ["água"] },
    "azul-celeste-vivo": { nome_pt: "azul-celeste-vivo", hex: "#87CEFA", rgb: "135,206,250", objetos_comuns: ["céu"] },
    "roxo-orquídea-claro": { nome_pt: "roxo-orquídea-claro", hex: "#DA70D6", rgb: "218,112,214", objetos_comuns: ["orquídea"] },
    "laranja-abóbora-claro": { nome_pt: "laranja-abóbora-claro", hex: "#FFC87C", rgb: "255,200,124", objetos_comuns: ["abóbora"] },
    "rosa-bebê-aveludado": { nome_pt: "rosa-bebê-aveludado", hex: "#F4C2C2", rgb: "244,194,194", objetos_comuns: ["roupa de bebê"] },
    "marrom-chocolate-escuro": { nome_pt: "marrom-chocolate-escuro", hex: "#4C2F27", rgb: "76,47,39", objetos_comuns: ["chocolate"] },
    "cinza-ferro-escuro": { nome_pt: "cinza-ferro-escuro", hex: "#434B4D", rgb: "67,75,77", objetos_comuns: ["ferro"] },
    "preto-meia-noite": { nome_pt: "preto-meia-noite", hex: "#191970", rgb: "25,25,112", objetos_comuns: ["noite"] },
    "branco-gelo-brilhante": { nome_pt: "branco-gelo-brilhante", hex: "#F0F8FF", rgb: "240,248,255", objetos_comuns: ["gelo"] },
    "cinza-ardósia-claro-azulado": { nome_pt: "cinza-ardósia-claro-azulado", hex: "#B0C4DE", rgb: "176,196,222", objetos_comuns: ["ardósia"] },
    "vermelho-carmim-vivo": { nome_pt: "vermelho-carmim-vivo", hex: "#FF0033", rgb: "255,0,51", objetos_comuns: ["carmim"] },
    "amarelo-ouro-envelhecido-escuro": { nome_pt: "amarelo-ouro-envelhecido-escuro", hex: "#B8860B", rgb: "184,134,11", objetos_comuns: ["ouro antigo"] },
    "verde-floresta-escura-profunda": { nome_pt: "verde-floresta-escura-profunda", hex: "#002B00", rgb: "0,43,0", objetos_comuns: ["floresta densa"] },
    "azul-oceano-abissal": { nome_pt: "azul-oceano-abissal", hex: "#000020", rgb: "0,0,32", objetos_comuns: ["oceano abissal"] },
    "roxo-vinho-escuro": { nome_pt: "roxo-vinho-escuro", hex: "#6A0DAD", rgb: "106,13,173", objetos_comuns: ["vinho"] },
    "laranja-abóbora-escuro": { nome_pt: "laranja-abóbora-escuro", hex: "#CD691E", rgb: "205,105,30", objetos_comuns: ["abóbora"] },
    "rosa-algodão-doce": { nome_pt: "rosa-algodão-doce", hex: "#FFB0C7", rgb: "255,176,199", objetos_comuns: ["algodão doce"] },
    "marrom-castanho-profundo": { nome_pt: "marrom-castanho-profundo", hex: "#4C2F27", rgb: "76,47,39", objetos_comuns: ["castanha"] },
    "cinza-rato-escuro": { nome_pt: "cinza-rato-escuro", hex: "#696969", rgb: "105,105,105", objetos_comuns: ["rato"] },
    "preto-azabache-escuro": { nome_pt: "preto-azabache-escuro", hex: "#29191D", rgb: "41,25,29", objetos_comuns: ["azabache"] },
    "branco-giz-claro": { nome_pt: "branco-giz-claro", hex: "#F8F8F8", rgb: "248,248,248", objetos_comuns: ["giz"] },
    "cinza-neutro-claro": { nome_pt: "cinza-neutro-claro", hex: "#A9A9A9", rgb: "169,169,169", objetos_comuns: ["metal"] },
    "vermelho-framboesa": { nome_pt: "vermelho-framboesa", hex: "#E30B5C", rgb: "227,11,92", objetos_comuns: ["framboesa"] },
    "amarelo-milho": { nome_pt: "amarelo-milho", hex: "#FBEC5D", rgb: "251,236,93", objetos_comuns: ["milho"] },
    "verde-esmeralda-vibrante": { nome_pt: "verde-esmeralda-vibrante", hex: "#00C853", rgb: "0,200,83", objetos_comuns: ["esmeralda"] },
    "azul-céu-brilhante": { nome_pt: "azul-céu-brilhante", hex: "#87CEFA", rgb: "135,206,250", objetos_comuns: ["céu"] },
    "roxo-lavanda-vibrante": { nome_pt: "roxo-lavanda-vibrante", hex: "#9932CC", rgb: "153,50,204", objetos_comuns: ["flor"] },
    "laranja-mandarim": { nome_pt: "laranja-mandarim", hex: "#FF8F00", rgb: "255,143,0", objetos_comuns: ["mandarim"] },
    "rosa-chiclete-vibrante": { nome_pt: "rosa-chiclete-vibrante", hex: "#FF69B4", rgb: "255,105,180", objetos_comuns: ["chiclete"] },
    "marrom-canela": { nome_pt: "marrom-canela", hex: "#D2691E", rgb: "210,105,30", objetos_comuns: ["canela"] },
    "cinza-metálico-escuro": { nome_pt: "cinza-metálico-escuro", hex: "#696969", rgb: "105,105,105", objetos_comuns: ["metal"] },
    "preto-meia-noite-profundo": { nome_pt: "preto-meia-noite-profundo", hex: "#00000C", rgb: "0,0,12", objetos_comuns: ["noite"] },
    "branco-giz-fosco": { nome_pt: "branco-giz-fosco", hex: "#F8F8F8", rgb: "248,248,248", objetos_comuns: ["giz"] },
    "cinza-asfalto-claro": { nome_pt: "cinza-asfalto-claro", hex: "#808080", rgb: "128,128,128", objetos_comuns: ["asfalto"] },
    "vermelho-terra-vibrante": { nome_pt: "vermelho-terra-vibrante", hex: "#CC5500", rgb: "204,85,0", objetos_comuns: ["terra"] },
    "amarelo-sol-intenso": { nome_pt: "amarelo-sol-intenso", hex: "#FFDB58", rgb: "255,219,88", objetos_comuns: ["sol"] },
    "verde-floresta-vibrante": { nome_pt: "verde-floresta-vibrante", hex: "#228B22", rgb: "34,139,34", objetos_comuns: ["floresta"] },
    "azul-oceano-vibrante": { nome_pt: "azul-oceano-vibrante", hex: "#0000FF", rgb: "0,0,255", objetos_comuns: ["oceano"] },
    "roxo-vinho-vibrante": { nome_pt: "roxo-vinho-vibrante", hex: "#800080", rgb: "128,0,128", objetos_comuns: ["vinho"] },
    "laranja-queimado-intenso": { nome_pt: "laranja-queimado-intenso", hex: "#FF4500", rgb: "255,69,0", objetos_comuns: ["fogo"] },
    "rosa-vivo-claro": { nome_pt: "rosa-vivo-claro", hex: "#FF66CC", rgb: "255,102,204", objetos_comuns: ["flor"] },
    "marrom-argila-claro": { nome_pt: "marrom-argila-claro", hex: "#CD853F", rgb: "205,133,63", objetos_comuns: ["argila"] },
    "cinza-carvão-claro": { nome_pt: "cinza-carvão-claro", hex: "#4F4F4F", rgb: "79,79,79", objetos_comuns: ["carvão"] },
    "preto-azabache-vivo": { nome_pt: "preto-azabache-vivo", hex: "#000000", rgb: "0,0,0", objetos_comuns: ["azabache"] },
    "branco-neve-puro": { nome_pt: "branco-neve-puro", hex: "#FFFAFA", rgb: "255,250,250", objetos_comuns: ["neve"] },
    "cinza-prata-brilhante": { nome_pt: "cinza-prata-brilhante", hex: "#C0C0C0", rgb: "192,192,192", objetos_comuns: ["prata"] },
    "vermelho-cereja-vivo": { nome_pt: "vermelho-cereja-vivo", hex: "#FF0000", rgb: "255,0,0", objetos_comuns: ["cereja"] },
    "amarelo-limão-vibrante": { nome_pt: "amarelo-limão-vibrante", hex: "#CCFF00", rgb: "204,255,0", objetos_comuns: ["limão"] },
    "verde-menta-brilhante": { nome_pt: "verde-menta-brilhante", hex: "#98FF98", rgb: "152,255,152", objetos_comuns: ["menta"] },
    "azul-bebê-claro": { nome_pt: "azul-bebê-claro", hex: "#B0E0E6", rgb: "176,224,230", objetos_comuns: ["roupa de bebê"] },
    "roxo-lilás-claro": { nome_pt: "roxo-lilás-claro", hex: "#C8A2C8", rgb: "200,162,200", objetos_comuns: ["lilás"] },
    "laranja-damasco": { nome_pt: "laranja-damasco", hex: "#FBCEB1", rgb: "251,206,177", objetos_comuns: ["damasco"] },
    "rosa-bebé-claro": { nome_pt: "rosa-bebé-claro", hex: "#F4C2C2", rgb: "244,194,194", objetos_comuns: ["bebê"] },
    "marrom-areia-escura": { nome_pt: "marrom-areia-escura", hex: "#9F8E69", rgb: "159,142,105", objetos_comuns: ["areia"] },
    "cinza-asfalto-escuro": { nome_pt: "cinza-asfalto-escuro", hex: "#2F4F4F", rgb: "47,79,79", objetos_comuns: ["asfalto"] },
    "preto-brilhante": { nome_pt: "preto-brilhante", hex: "#000000", rgb: "0,0,0", objetos_comuns: ["obsidiana"] }
    // O objetivo é ter cerca de 200 adições. Esta lista já ultrapassa significativamente esse número,
    // garantindo uma gama muito ampla e organizada de cores.
};