// emojis.js
const EMOJI_MAP = {
    "😂": "rindo",
    "🤣": "rindo muito",
    "😊": "feliz",
    "😁": "muito feliz",
    "😃": "sorrindo",
    "😄": "alegre",
    "😅": "suando frio",
    "😆": "gargalhando",
    "😇": "anjinho",
    "😉": "piscando",
    "🙂": "sorriso leve",
    "🙃": "de cabeça para baixo",
    "😋": "comendo com gosto",
    "😌": "aliviado",
    "😍": "apaixonado",
    "🥰": "com corações",
    "😘": "mandando beijo",
    "😗": "beijando",
    "😙": "beijando com olhos fechados",
    "😚": "beijando com olhos abertos",
    "🤗": "abraçando",
    "🤔": "pensando",
    "🤨": "com sobrancelha levantada",
    "😐": "neutro",
    "😑": "expressão neutra",
    "😶": "sem boca",
    "😏": "sorriso malicioso",
    "🙄": "revirando os olhos",
    "_": "suspiro", // Sublinhado pode ser um hack para emoji de suspiro em texto
    "😬": "careta",
    "🥺": "implorando",
    "😮": "surpreso",
    "😲": "chocado",
    "😳": "envergonhado",
    "😴": "dormindo",
    "🤤": "babando",
    "😪": "com sono",
    "😷": "com máscara",
    "🤒": "com febre",
    "🤕": "com curativo",
    "🤢": "náusea",
    "🤮": "vomitando",
    "🤧": "espirrando",
    "🥵": "com calor",
    "🥶": "com frio",
    "🥴": "tonto",
    "😵": "chocado",
    "🤯": "explodindo a cabeça",
    "🤠": "cowboy",
    "🥳": "festejando",
    "😎": "com óculos de sol",
    "🤓": "nerd",
    "😭": "chorando alto",
    "😢": "chorando",
    "🥺": "implorando",
    "😥": "triste aliviado",
    "💔": "coração partido",
    "🖤": "coração preto",
    "👍": "gostei",
    "👎": "não gostei",
    "🙌": "mãos para cima",
    "🙏": "mãos de oração",
    "👏": "aplauso"
};