// funcoesobjetos.js

/**
 * @file Dicionário de objetos e suas funções principais.
 * Mapeia nomes de objetos para uma ou mais descrições de suas funcionalidades.
 * Esta lista é abrangente e visa associar objetos a seus propósitos.
 * @author [Seu Nome ou Nome da Organização]
 * @version 1.0.0
 */

const FUNCOES_OBJETOS_DATA = {
    // Escrita e Leitura
    "caneta": "escrever",
    "lápis": "escrever ou desenhar",
    "borracha": "apagar escrita a lápis",
    "caderno": "registrar informações e anotações",
    "papel": "registrar informações, desenhar ou embrulhar",
    "livro": "fornecer conhecimento e entretenimento pela leitura",
    "revista": "fornecer informação e entretenimento",
    "jornal": "informar sobre notícias diárias",
    "marcador de texto": "destacar informações importantes em texto",
    "giz": "escrever ou desenhar em superfícies ásperas",
    "quadro branco": "escrever e apagar facilmente com marcadores",
    "lousa": "escrever com giz",
    "apagador": "apagar escrita em lousas ou quadros",
    "dicionário": "consultar significados e grafia de palavras",
    "enciclopédia": "fornecer informações abrangentes sobre diversos temas",
    "mapa": "representar geograficamente uma área",
    "globo terrestre": "representar o planeta Terra em 3D",
    "régua": "medir e traçar linhas retas",
    "compasso": "desenhar círculos e arcos",
    "transferidor": "medir ângulos",
    "calculadora": "realizar cálculos matemáticos",

    // Tecnologia e Eletrônicos
    "computador": "processar dados e realizar tarefas",
    "celular": "comunicação e acesso à internet",
    "televisão": "exibir imagens e áudios para entretenimento e informação",
    "rádio": "transmitir e receber áudio",
    "tablet": "navegar na internet, ler e consumir mídia",
    "impressora": "produzir cópias físicas de documentos digitais",
    "scanner": "digitalizar documentos e imagens",
    "mouse": "controlar o cursor na tela do computador",
    "teclado": "inserir texto e comandos em um computador",
    "monitor": "exibir informações visuais do computador",
    "câmera fotográfica": "capturar imagens estáticas",
    "filmadora": "gravar vídeos",
    "webcam": "capturar vídeo para videoconferências",
    "fone de ouvido": "ouvir áudio de forma privada",
    "microfone": "capturar e transmitir som",
    "caixa de som": "reproduzir áudio em alto volume",
    "projetor": "exibir imagens em uma superfície grande",
    "pendrive": "armazenar e transportar dados digitais",
    "disco rígido": "armazenar dados permanentemente em um computador",
    "cartão de memória": "armazenar dados em dispositivos portáteis",
    "roteador": "distribuir conexão de internet sem fio",
    "modem": "conectar-se à internet",
    "mousepad": "proporcionar superfície para o mouse",
    "carregador": "fornecer energia para dispositivos eletrônicos",
    "bateria": "armazenar energia elétrica",
    "controle remoto": "operar dispositivos eletrônicos à distância",
    "console de videogame": "executar jogos eletrônicos",
    "joystick": "controlar personagens ou ações em jogos",
    "drone": "voar e capturar imagens aéreas",
    "smartwatch": "monitorar atividades físicas e exibir notificações",
    "assistente virtual": "responder a comandos de voz e controlar dispositivos",
    "câmera de segurança": "monitorar ambientes",
    "detector de metais": "localizar objetos metálicos",
    "GPS": "fornecer localização e navegação",
    "power bank": "carregar dispositivos móveis portatilmente",

    // Móveis e Utensílios Domésticos
    "mesa": "apoiar objetos ou pessoas",
    "cadeira": "sentar",
    "sofá": "sentar e descansar confortavelmente",
    "cama": "dormir e descansar",
    "armário": "armazenar roupas e objetos",
    "estante": "organizar livros e objetos",
    "guarda-roupa": "armazenar e organizar roupas",
    "fogão": "cozinhar alimentos",
    "geladeira": "refrigerar e conservar alimentos",
    "micro-ondas": "aquecer e cozinhar alimentos rapidamente",
    "forno": "assar alimentos",
    "lava-louças": "lavar louças automaticamente",
    "máquina de lavar": "lavar roupas automaticamente",
    "secadora de roupas": "secar roupas automaticamente",
    "aspirador de pó": "limpar poeira e sujeira",
    "liquidificador": "misturar e triturar alimentos",
    "batedeira": "bater ingredientes para receitas",
    "torradeira": "torrar pães",
    "cafeteira": "preparar café",
    "ferro de passar": "alisar roupas",
    "tábua de passar": "apoiar roupas para passar",
    "balde": "conter líquidos",
    "vassoura": "limpar o chão",
    "pá de lixo": "recolher lixo",
    "pano de chão": "limpar superfícies molhadas",
    "rodo": "espalhar ou remover líquidos",
    "esponja": "limpar e esfregar superfícies",
    "sabonete": "limpar e higienizar a pele",
    "shampoo": "limpar e tratar o cabelo",
    "condicionador": "hidratar e desembaraçar o cabelo",
    "escova de dentes": "limpar os dentes",
    "pasta de dente": "auxiliar na limpeza dos dentes",
    "fio dental": "remover resíduos entre os dentes",
    "saboneteira": "apoiar o sabonete",
    "toalha": "secar o corpo ou objetos",
    "tapete": "decorar e aquecer ambientes, reter sujeira",
    "cortina": "controlar a entrada de luz e garantir privacidade",
    "lençol": "cobrir e proteger o colchão",
    "travesseiro": "apoiar a cabeça ao dormir",
    "cobertor": "aquecer ao dormir",
    "vaso sanitário": "descartar resíduos orgânicos",
    "chuveiro": "fornecer água para o banho",
    "pia": "lavar mãos e objetos",
    "espelho": "refletir imagens",
    "porta": "permitir ou bloquear a entrada e saída",
    "janela": "permitir a entrada de luz e ventilação",
    "lâmpada": "iluminar ambientes",
    "ventilador": "circular o ar e refrescar ambientes",
    "ar-condicionado": "controlar a temperatura ambiente",
    "aquecedor": "aquecer ambientes",
    "cortador de grama": "cortar a grama",
    "mangueira": "transportar água",
    "carrinho de compras": "transportar produtos em supermercados",
    "cesto de roupa suja": "armazenar roupas sujas",
    "ralo": "drenar líquidos",
    "lixeira": "armazenar lixo",
    "extintor de incêndio": "combater pequenos incêndios",
    "detetor de fumaça": "alertar sobre fumaça ou incêndio",

    // Ferramentas e Construção
    "martelo": "bater ou pregar",
    "chave de fenda": "apertar ou soltar parafusos com fenda",
    "chave philips": "apertar ou soltar parafusos philips",
    "alicate": "segurar, torcer ou cortar arames",
    "furadeira": "fazer furos em superfícies",
    "serra": "cortar materiais como madeira ou metal",
    "trena": "medir distâncias",
    "nível": "verificar o nivelamento de superfícies",
    "esquadro": "verificar ângulos retos",
    "prego": "fixar objetos",
    "parafuso": "fixar objetos com rosca",
    "porca": "fixar parafusos",
    "arruela": "distribuir a carga de um parafuso",
    "fita métrica": "medir distâncias",
    "lixa": "alisar superfícies",
    "broca": "fazer furos com furadeira",
    "pistola de cola quente": "aplicar cola quente",
    "kit de primeiros socorros": "fornecer itens para emergências médicas",
    "luvas": "proteger as mãos",
    "óculos de segurança": "proteger os olhos",
    "capacete": "proteger a cabeça",
    "máscara de proteção": "proteger as vias respiratórias",
    "lanterna": "iluminar áreas escuras",
    "pilha": "fornecer energia para dispositivos portáteis",
    "bancada de trabalho": "fornecer superfície para trabalho manual",
    "esmerilhadeira": "cortar, desbastar e lixar materiais",
    "chave inglesa": "apertar e soltar porcas e parafusos de diversos tamanhos",
    "pá": "cavar ou mover materiais soltos",
    "enxada": "preparar o solo, capinar",
    "picareta": "quebrar solo duro, rochas",
    "carrinho de mão": "transportar materiais",
    "betoneira": "misturar concreto",

    // Meios de Transporte
    "carro": "transportar pessoas e cargas em terra",
    "moto": "transportar uma ou duas pessoas em terra",
    "bicicleta": "transportar uma pessoa, movida por pedal",
    "ônibus": "transportar grande número de passageiros em terra",
    "trem": "transportar pessoas e cargas em trilhos",
    "metrô": "transportar passageiros em trilhos subterrâneos/elevados",
    "avião": "transportar pessoas e cargas pelo ar",
    "helicóptero": "transportar pessoas e cargas pelo ar, com capacidade de voo estacionário",
    "navio": "transportar pessoas e cargas pelo mar",
    "barco": "transportar pessoas e cargas pela água",
    "submarino": "navegar submerso",
    "caminhão": "transportar grandes cargas em terra",
    "van": "transportar grupos menores de pessoas ou pequenas cargas",
    "skate": "locomoção e manobras radicais",
    "patins": "locomoção e lazer",
    "skate elétrico": "locomoção elétrica",
    "patinete": "locomoção com propulsão humana ou elétrica",
    "monociclo": "locomoção com uma roda",
    "teleférico": "transportar pessoas em cabos aéreos",
    "funicular": "transportar pessoas em trilhos inclinados",
    "bonde": "transportar passageiros em trilhos urbanos",

    // Vestuário e Acessórios
    "camisa": "cobrir o tronco",
    "calça": "cobrir as pernas",
    "vestido": "cobrir o corpo com uma peça única",
    "saia": "cobrir a parte inferior do corpo",
    "blusa": "cobrir o tronco",
    "casaco": "proteger do frio",
    "jaqueta": "proteger do frio e do vento",
    "sapato": "proteger e calçar os pés",
    "tênis": "calçar os pés para conforto e esporte",
    "bota": "proteger os pés e parte da perna",
    "meia": "cobrir e aquecer os pés",
    "cueca": "roupa íntima masculina",
    "calcinha": "roupa íntima feminina",
    "sutiã": "apoiar os seios",
    "chapéu": "proteger a cabeça do sol ou frio",
    "boné": "proteger a cabeça do sol",
    "cachecol": "aquecer o pescoço",
    "luva": "proteger e aquecer as mãos",
    "óculos de sol": "proteger os olhos da luz solar",
    "óculos de grau": "corrigir a visão",
    "relógio de pulso": "indicar as horas no pulso",
    "colar": "decorar o pescoço",
    "brinco": "decorar as orelhas",
    "anel": "decorar os dedos",
    "pulseira": "decorar o pulso",
    "cinto": "ajustar roupas na cintura",
    "bolsa": "transportar objetos pessoais",
    "carteira": "armazenar dinheiro e documentos",
    "mochila": "transportar objetos nas costas",
    "guarda-chuva": "proteger da chuva",
    "sombrinha": "proteger do sol",
    "lenço": "limpar ou decorar",
    "gravata": "decorar o pescoço",
    "paletó": "parte de um terno",
    "meião": "cobrir a perna para esportes",
    "roupa de banho": "vestir-se para nadar",
    "pijama": "vestir-se para dormir",
    "roupão": "cobrir-se após o banho",
    "sandália": "calçar os pés levemente",
    "chinelo": "calçar os pés casualmente",
    "cinto de segurança": "proteger em veículos",
    "colete salva-vidas": "manter a pessoa flutuando na água",

    // Alimentos e Utensílios de Cozinha
    "faca": "cortar alimentos ou objetos",
    "garfo": "espetar alimentos",
    "colher": "pegar ou mexer alimentos líquidos/pastosos",
    "prato": "servir alimentos",
    "copo": "conter líquidos para beber",
    "xícara": "conter líquidos quentes para beber",
    "tigela": "conter alimentos ou líquidos",
    "panela": "cozinhar alimentos no fogão",
    "frigideira": "fritar alimentos",
    "travessa": "servir alimentos em mesa",
    "liquidificador": "misturar e triturar alimentos",
    "batedeira": "bater ingredientes",
    "abridor de latas": "abrir latas",
    "abridor de garrafas": "abrir garrafas",
    "saca-rolhas": "abrir garrafas de vinho",
    "tábua de corte": "apoiar alimentos para cortar",
    "ralador": "ralar alimentos",
    "escorredor de macarrão": "drenar água de alimentos",
    "bandeja": "transportar alimentos e bebidas",
    "copo medidor": "medir líquidos",
    "colher de medida": "medir pequenas quantidades",
    "balança de cozinha": "pesar alimentos",
    "assadeira": "assar alimentos no forno",
    "forma de bolo": "assar bolos",
    "rolo de massa": "esticar massas",
    "espatula": "raspar, virar ou espalhar alimentos",
    "concha": "servir líquidos",
    "fatiador": "fatiar alimentos",
    "mixer": "misturar ou triturar alimentos em recipientes",
    "fogão elétrico": "cozinhar alimentos usando eletricidade",
    "micro-ondas com grill": "aquecer e grelhar alimentos",
    "sanduicheira": "preparar sanduíches quentes",
    "grill": "grelhar alimentos",
    "máquina de fazer pão": "preparar pão automaticamente",
    "moedor de carne": "moer carne",
    "espremedor de frutas": "espremer sucos de frutas",
    "chaleira": "ferver água",
    "garrafa térmica": "manter líquidos quentes ou frios",
    "pano de prato": "secar louça",
    "luva térmica": "proteger as mãos do calor",
    "avental": "proteger a roupa ao cozinhar",
    "timer de cozinha": "controlar o tempo de cozimento",
    "termômetro de cozinha": "medir a temperatura de alimentos",
    "cortador de pizza": "cortar pizza",
    "peneira": "separar sólidos de líquidos, aerar farinha",
    "amassados de alho": "amassar alho",
    "descascador de legumes": "descascar legumes",

    // Itens de Jardim e Lazer
    "pá": "cavar",
    "rastelo": "reunir folhas, nivelar terra",
    "tesoura de poda": "podar plantas",
    "carrinho de mão": "transportar terra, folhas, etc.",
    "regador": "regar plantas",
    "semente": "germinar e dar origem a uma planta",
    "flor": "atrair polinizadores e embelezar",
    "planta": "produzir oxigênio, decorar, alimentar",
    "vaso de planta": "conter terra para plantas",
    "ferramenta de jardinagem": "auxiliar no cultivo de plantas",
    "rede": "descansar, pescar",
    "bola": "brincar, praticar esportes",
    "pipa": "voar com o vento",
    "bicicleta": "pedalar",
    "skate": "andar de skate",
    "patins": "patinar",
    "chuteira": "jogar futebol",
    "raquete": "rebater bola em esportes",
    "peteca": "jogar peteca",
    "baralho": "jogar cartas",
    "dado": "gerar números aleatórios em jogos",
    "tabuleiro de xadrez": "jogar xadrez",
    "peças de xadrez": "mover no tabuleiro para jogar xadrez",
    "dominó": "jogar dominó",
    "quebra-cabeça": "montar uma imagem a partir de peças",
    "carrinho de brinquedo": "brincar",
    "boneca": "brincar",
    "lego": "montar estruturas",
    "massinha de modelar": "modelar formas",
    "giz de cera": "colorir",
    "tinta": "pintar",
    "pincel": "aplicar tinta",
    "tela": "superfície para pintura",
    "instrumento musical": "produzir som musical",
    "violão": "tocar música",
    "piano": "tocar música",
    "bateria (musical)": "produzir ritmo",
    "flauta": "tocar música",
    "violino": "tocar música",
    "lápis de cor": "colorir",
    "fantasia": "vestir-se para representar um personagem",
    "balão": "decorar, brincar, voar",
    "confete": "decorar festas",
    "serpentina": "decorar festas",
    "vela": "iluminar, decorar bolos",
    "fósforo": "produzir fogo",
    "isqueiro": "produzir fogo",
    "barraca de camping": "montar abrigo temporário",
    "saco de dormir": "dormir em camping",
    "fogareiro": "cozinhar em camping",
    "mochila de acampamento": "transportar equipamentos de camping",
    "bússola": "orientar-se geograficamente",
    "binóculo": "observar objetos distantes",
    "vara de pescar": "pescar",
    "anzol": "capturar peixes",
    "linha de pesca": "conectar o anzol à vara",
    "chumbo (pesca)": "pesar a linha de pesca",
    "boia": "manter o anzol na profundidade certa",
    "isca": "atrair peixes",
    "skatepark": "local para praticar skate",
    "campo de futebol": "local para jogar futebol",
    "piscina": "nadar",
    "praia": "lazer, nadar, tomar sol",
    "parque": "lazer, recreação",
    "bicicleta ergométrica": "exercitar-se em casa",
    "esteira": "caminhar ou correr em casa",
    "halter": "treinar força muscular",
    "colchonete": "fazer exercícios no chão",
    "bola de yoga": "fazer exercícios de yoga",

    // Saúde e Higiene Pessoal
    "sabonete": "limpar e higienizar a pele",
    "shampoo": "limpar e tratar o cabelo",
    "condicionador": "hidratar e desembaraçar o cabelo",
    "escova de dentes": "limpar os dentes",
    "pasta de dente": "auxiliar na limpeza dos dentes",
    "fio dental": "remover resíduos entre os dentes",
    "saboneteira": "apoiar o sabonete",
    "toalha": "secar o corpo ou objetos",
    "algodão": "limpar e aplicar produtos",
    "cotonete": "limpar áreas delicadas",
    "álcool": "desinfetar",
    "gaze": "cobrir feridas",
    "band-aid": "proteger pequenos cortes",
    "termômetro": "medir a temperatura corporal",
    "medicamento": "tratar doenças",
    "seringa": "aplicar injeções",
    "bandagem": "cobrir e proteger feridas",
    "esparadrapo": "fixar bandagens",
    "tesoura cirúrgica": "cortar tecidos em cirurgias",
    "agulha": "costurar, aplicar injeções",
    "máscara facial": "proteger contra partículas e vírus",
    "protetor solar": "proteger a pele do sol",
    "hidratante": "hidratar a pele",
    "perfume": "perfumar o corpo",
    "desodorante": "controlar o odor corporal",
    "pente": "pentear o cabelo",
    "escova de cabelo": "pentear e desembaraçar o cabelo",
    "secador de cabelo": "secar o cabelo",
    "chapinha": "alisar o cabelo",
    "modelador de cachos": "cachear o cabelo",
    "cortador de unha": "cortar unhas",
    "lixa de unha": "lixar e dar forma às unhas",
    "pinça": "remover pelos pequenos",
    "barbeador": "cortar pelos do rosto ou corpo",
    "creme de barbear": "facilitar o barbear",
    "loção pós-barba": "acalmar a pele após o barbear",
    "bandeja de higiene": "organizar produtos de higiene",
    "aparelho de pressão": "medir a pressão arterial",
    "estetoscópio": "auscultar sons corporais",
    "muleta": "auxiliar na locomoção",
    "cadeira de rodas": "transportar pessoas com dificuldade de locomoção",
    "kit de costura": "reparar roupas",

    // Alimentos e Bebidas (como objetos)
    "maçã": "alimentar",
    "banana": "alimentar",
    "pão": "alimentar",
    "leite": "alimentar e hidratar",
    "água": "hidratar",
    "café": "estimular e aquecer",
    "chá": "aquecer, relaxar ou estimular",
    "suco": "hidratar e nutrir",
    "refrigerante": "refrescar e satisfazer sede",
    "pizza": "alimentar",
    "sanduíche": "alimentar",
    "bolo": "alimentar e celebrar",
    "doce": "satisfazer desejo por açúcar",
    "sal": "temperar alimentos",
    "açúcar": "adoçar alimentos",
    "arroz": "alimentar",
    "feijão": "alimentar",
    "carne": "alimentar",
    "frango": "alimentar",
    "peixe": "alimentar",
    "vegetal": "alimentar e nutrir",
    "fruta": "alimentar e nutrir",
    "ovo": "alimentar",
    "queijo": "alimentar",
    "manteiga": "condimentar, cozinhar",
    "azeite": "temperar, cozinhar",
    "vinagre": "temperar",
    "molho": "condimentar",
    "tempero": "dar sabor a alimentos",

    // Outros objetos diversos
    "chave": "abrir ou fechar fechaduras",
    "cadeado": "proteger objetos",
    "moeda": "meio de troca",
    "nota (dinheiro)": "meio de troca",
    "cartão de crédito": "meio de pagamento",
    "câmera de segurança": "monitorar e registrar atividades",
    "alarme": "alertar sobre perigos",
    "escada": "subir e descer alturas",
    "extintor de incêndio": "combater fogo",
    "cinzeiro": "coletar cinzas de cigarro",
    "espelho": "refletir imagens",
    "flâmula": "decorar, sinalizar",
    "bandeira": "representar nações ou grupos",
    "brinquedo": "divertir e desenvolver",
    "dardo": "jogar em alvo",
    "balão de festa": "decorar festas",
    "presente": "demonstrar afeto, celebrar",
    "envelope": "conter cartas ou documentos",
    "selo": "validar correspondência",
    "caixa de correio": "receber correspondências",
    "coleira": "controlar animais de estimação",
    "guia (para cães)": "conduzir animais de estimação",
    "casinha de cachorro": "abrigo para cães",
    "comedouro": "servir alimento para animais",
    "bebedouro": "servir água para animais",
    "aquário": "conter peixes e plantas aquáticas",
    "gaiola": "conter pássaros ou pequenos animais",
    "coleção": "agrupar itens de interesse",
    "álbum de fotos": "organizar e guardar fotos",
    "troféu": "recompensar conquistas",
    "medalha": "recompensar conquistas",
    "diploma": "certificar conclusão de estudos",
    "certidão": "documentar um evento",
    "passaporte": "documento de viagem internacional",
    "carteira de identidade": "identificar uma pessoa",
    "carteira de motorista": "habilitar a dirigir",
    "chaveiro": "organizar chaves",
    "ímã": "fixar objetos em superfícies metálicas",
    "velcro": "fixar objetos com fecho de contato",
    "ziper": "abrir e fechar tecidos",
    "botão": "fechar roupas",
    "agulha de costura": "costurar",
    "linha de costura": "costurar",
    "dedal": "proteger o dedo ao costurar",
    "tesoura de tecido": "cortar tecido",
    "máquina de costura": "costurar automaticamente",
    "ferro de solda": "unir metais por soldagem",
    "cabo (elétrico)": "conduzir eletricidade ou dados",
    "tomada": "conectar aparelhos à rede elétrica",
    "plugue": "conectar cabos à tomada",
    "interruptor": "ligar e desligar circuitos elétricos",
    "fusível": "proteger circuitos elétricos",
    "disjuntor": "interromper corrente elétrica em caso de sobrecarga",
    "bomba de ar": "inflar objetos",
    "mangueira de ar": "conduzir ar comprimido",
    "rodinha": "facilitar o movimento",
    "alavanca": "multiplicar força",
    "mola": "armazenar e liberar energia mecânica",
    "engrenagem": "transmitir movimento",
    "rolamento": "reduzir atrito",
    "polia": "modificar a direção de uma força",
    "corda": "amarrar, puxar, suspender",
    "corrente": "amarrar, puxar, suspender",
    "prego (metal)": "fixar",
    "abraçadeira": "fixar cabos ou tubos",
    "fita adesiva": "fixar ou vedar",
    "cola": "unir materiais",
    "argamassa": "unir tijolos",
    "cimento": "material de construção",
    "tinta (parede)": "cobrir e decorar superfícies",
    "pincel (pintura)": "aplicar tinta",
    "rolo de pintura": "aplicar tinta em grandes áreas",
    "bandeja de pintura": "conter tinta para rolo",
    "esponja de pintura": "aplicar efeitos em pintura",
    "solventes": "diluir ou limpar tintas",
    "lâmpada LED": "iluminar com eficiência",
    "interruptor dimmer": "controlar intensidade da luz",
    "tomada USB": "carregar dispositivos via USB",
    "painel solar": "converter luz solar em energia elétrica",
    "turbina eólica": "converter vento em energia elétrica",
    "gerador": "produzir eletricidade",
    "pilha recarregável": "armazenar energia recarregável",
    "bateria de carro": "fornecer energia para o carro",
    "extensão elétrica": "estender o alcance de tomadas",
    "régua de tomadas": "conectar múltiplos aparelhos",
    "filtro de linha": "proteger aparelhos contra surtos",
    "transformador": "alterar tensão elétrica",
    "multímetro": "medir grandezas elétricas",
    "osciloscópio": "visualizar sinais elétricos",
    "soldador": "unir materiais por soldagem",
    "máquina de solda": "realizar soldagem",
    "broca de metal": "fazer furos em metal",
    "chave de grifo": "apertar e soltar tubos e porcas grandes",
    "rebitador": "fixar rebites",
    "pistola de pintura": "aplicar tinta por pulverização",
    "compressor de ar": "gerar ar comprimido",
    "esmeril": "afiar ferramentas",
    "torno mecânico": "usinar peças",
    "fresadora": "usinar peças com remoção de material",
    "prensa hidráulica": "aplicar grande força de compressão",
    "bomba de água": "bombear água",
    "filtro de água": "purificar água",
    "aquecedor de água": "aquecer água",
    "válvula": "controlar o fluxo de líquidos/gases",
    "tubulação": "conduzir líquidos/gases",
    "conexão (tubo)": "unir tubos",
    "bucha (fixação)": "fixar parafusos em paredes",
    "argola": "prender, suspender",
    "mosquetão": "prender, conectar",
    "cadeia": "amarrar, suspender",
    "barbante": "amarrar, prender",
    "fita crepe": "mascarar áreas em pintura",
    "fita isolante": "isolar fios elétricos",
    "fita dupla face": "fixar objetos em duas superfícies",
    "aplicador de cola": "facilitar aplicação de cola",
    "estilete": "cortar papel e materiais leves",
    "lâmina": "cortar",
    "afiador de facas": "afiar facas",
    "bucha vegetal": "esfregar para limpeza",
    "esponja de aço": "remover sujeira pesada",
    "rodo de pia": "limpar pia",
    "escova de vaso sanitário": "limpar vaso sanitário",
    "desentupidor": "desentupir encanamentos",
    "detergente": "limpar louças",
    "água sanitária": "desinfetar, clarear",
    "amaciante": "amaciar roupas",
    "sabão em pó": "lavar roupas",
    "alvejante": "clarear tecidos",
    "inseticida": "matar insetos",
    "raticida": "matar ratos",
    "armadilha para insetos": "capturar insetos",
    "aspirador de pó robô": "limpar o chão autonomamente",
    "torneira": "controlar o fluxo de água",
    "válvula de descarga": "controlar o fluxo de água do vaso",
    "ralador de queijo": "ralar queijo",
    "moedor de pimenta": "moer pimenta",
    "escorredor de louça": "secar louça",
    "porta-temperos": "organizar temperos",
    "panelas de pressão": "cozinhar alimentos rapidamente",
    "fogão a lenha": "cozinhar e aquecer ambientes com lenha",
    "máquina de café expresso": "preparar café expresso",
    "moedor de café": "moer grãos de café",
    "coador de café": "filtrar café",
    "garfo de churrasco": "manusear carnes no churrasco",
    "faca de churrasco": "cortar carnes no churrasco",
    "espeto": "assar carnes",
    "grelha": "assar alimentos no fogo",
    "churrasqueira": "preparar churrasco",
    "carvão (combustível)": "produzir calor para churrasco",
    "acendedor de churrasqueira": "acender carvão",
    "mesa de piquenique": "apoiar alimentos e pessoas ao ar livre",
    "cesta de piquenique": "transportar itens para piquenique",
    "toalha de piquenique": "cobrir o chão para piquenique",
    "saca-rolhas elétrico": "abrir garrafas de vinho facilmente",
    "cortador de legumes": "cortar legumes de forma rápida",
    "processador de alimentos": "triturar, picar, ralar alimentos",
    "balança de banheiro": "pesar pessoas",
    "balança de bebê": "pesar bebês",
    "termômetro digital": "medir temperatura com precisão",
    "nebulizador": "administrar medicamentos por inalação",
    "medidor de glicose": "medir nível de açúcar no sangue",
    "kit de costura de viagem": "reparar roupas em viagem",
    "máquina de cortar cabelo": "cortar cabelo",
    "máquina de aparar pelos": "aparar pelos",
    "aparelho de barbear elétrico": "barbear com eletricidade",
    "espelho de aumento": "ampliar imagem para detalhes",
    "lente de contato": "corrigir a visão (uso direto no olho)",
    "solução para lentes": "limpar e conservar lentes de contato",
    "estojo de lentes": "armazenar lentes de contato",
    "tesoura de unha": "cortar unhas",
    "esponja de banho": "esfregar o corpo",
    "touca de banho": "proteger o cabelo no banho",
    "bucha de banho": "esfregar o corpo",
    "esponja esfoliante": "remover células mortas da pele",
    "creme dental infantil": "limpar dentes de crianças",
    "escova de cabelo infantil": "pentear cabelo de crianças",
    "mamadeira": "alimentar bebês com líquidos",
    "chupeta": "acalmar bebês",
    "fralda": "absorver urina e fezes de bebês",
    "lenço umedecido": "limpar bebês",
    "brinquedo de banho": "divertir no banho",
    "andador": "ajudar bebês a caminhar",
    "carrinho de bebê": "transportar bebês",
    "cadeirinha de carro (bebê)": "transportar bebês com segurança em veículos",
    "berço": "bebê dormir",
    "chocalho": "divertir bebês com som",
    "mordedor": "aliviar coceira na gengiva de bebês",
    "travesseiro de amamentação": "apoiar o bebê durante a amamentação",
    "bomba tira leite": "extrair leite materno",
    "esterilizador de mamadeiras": "esterilizar mamadeiras",
    "termômetro de banho": "medir temperatura da água do banho",
    "monitor de bebê": "monitorar o bebê à distância",
    "câmera de bebê": "monitorar o bebê visualmente",
    "babá eletrônica": "monitorar o bebê por áudio/vídeo",
    "cadeira de alimentação": "apoiar o bebê para comer",
    "pratinho de bebê": "servir comida para bebê",
    "talheres infantis": "alimentar bebês",
    "copo de treinamento": "ajudar crianças a beberem sozinhas",
    "livro de pano": "entreter bebês",
    "brinquedo de empilhar": "desenvolver coordenação motora",
    "cubos de encaixe": "desenvolver raciocínio lógico",
    "blocos de montar": "construir e desenvolver criatividade",
    "quebra-cabeça infantil": "desenvolver raciocínio",
    "livro de colorir": "estimular a criatividade e coordenação",
    "canetinha": "colorir",
    "massinha (modelar)": "modelar",
    "tinta guache": "pintar",
    "pincel grosso": "pintar grandes áreas",
    "tesoura sem ponta": "cortar com segurança",
    "cola branca": "colar papel",
    "papel colorido": "fazer atividades artísticas",
    "fantoche": "brincar e contar histórias",
    "mini-cozinha (brinquedo)": "brincar de cozinhar",
    "kit médico (brinquedo)": "brincar de médico",
    "instrumento musical de brinquedo": "estimular o gosto musical",
    "patinete infantil": "locomoção e brincadeira",
    "triciclo": "locomoção infantil",
    "patins infantil": "patinar para crianças",
    "corda de pular": "brincar e exercitar",
    "bambolê": "brincar e exercitar",
    "kit de jardinagem infantil": "incentivar a jardinagem",
    "telescópio": "observar astros",
    "microscópio": "observar objetos pequenos",
    "lupa": "ampliar imagens",
    "termômetro de ambiente": "medir temperatura do ambiente",
    "barômetro": "medir pressão atmosférica",
    "higrômetro": "medir umidade do ar",
    "anemômetro": "medir velocidade do vento",
    "pluviômetro": "medir quantidade de chuva",
    "voltímetro": "medir tensão elétrica",
    "amperímetro": "medir corrente elétrica",
    "ohmímetro": "medir resistência elétrica",
    "osciloscópio digital": "visualizar sinais elétricos",
    "gerador de funções": "gerar sinais elétricos",
    "fonte de alimentação": "fornecer energia controlada",
    "resistor": "controlar corrente elétrica",
    "capacitor": "armazenar carga elétrica",
    "indutor": "armazenar energia em campo magnético",
    "diodo": "permitir fluxo de corrente em uma direção",
    "transistor": "amplificar ou chavear sinais eletrônicos",
    "LED": "emitir luz com eficiência",
    "painel de controle": "operar e monitorar sistemas",
    "sensor de movimento": "detectar movimento",
    "sensor de temperatura": "medir temperatura",
    "sensor de luz": "detectar luz",
    "atuador": "converter energia em movimento",
    "motor": "converter energia em movimento",
    "bomba": "mover fluidos",
    "cilindro hidráulico": "gerar força por pressão de fluido",
    "válvula solenóide": "controlar fluxo eletronicamente",
    "válvula de esfera": "controlar fluxo manualmente",
    "válvula de gaveta": "controlar fluxo manualmente",
    "medidor de vazão": "medir volume de fluido",
    "manômetro": "medir pressão",
    "termopar": "medir temperatura",
    "transdutor": "converter uma forma de energia em outra",
    "controlador PID": "controlar sistemas automaticamente",
    "PLC (Controlador Lógico Programável)": "automatizar processos industriais",
    "relé": "chavear circuitos elétricos",
    "circuito integrado": "realizar funções eletrônicas complexas",
    "placa de circuito impresso (PCI)": "conectar componentes eletrônicos",
    "cabo de rede": "transmitir dados em rede",
    "cabo HDMI": "transmitir áudio e vídeo digital",
    "cabo USB": "conectar e carregar dispositivos",
    "adaptador de energia": "converter tensão elétrica",
    "filtro de ar": "filtrar partículas do ar",
    "filtro de óleo": "filtrar óleo",
    "filtro de combustível": "filtrar combustível",
    "radiador": "dissipar calor",
    "ventoinha": "circular ar para refrigeração",
    "trocador de calor": "transferir calor entre fluidos",
    "válvula de segurança": "liberar pressão excessiva",
    "junta (mecânica)": "vedar conexões",
    "rolamento de esferas": "permitir movimento rotativo",
    "correia (mecânica)": "transmitir movimento rotativo",
    "corrente (mecânica)": "transmitir movimento rotativo",
    "engrenagem cônica": "transmitir movimento em ângulo",
    "parafuso sem fim": "converter movimento rotativo em linear",
    "freio": "diminuir ou parar movimento",
    "embreagem": "conectar ou desconectar eixos",
    "caixa de câmbio": "modificar velocidade e torque",
    "diferencial (veículo)": "permitir que rodas girem em velocidades diferentes",
    "amortecedor": "absorver choques",
    "mola espiral": "armazenar energia e absorver choques",
    "pneu": "proporcionar tração e amortecimento",
    "roda": "permitir movimento giratório",
    "eixo (mecânico)": "suportar rotação",
    "volante": "direcionar veículos",
    "pedal": "acionar comandos com os pés",
    "banco (assento)": "sentar",
    "para-brisa": "proteger de vento e objetos",
    "limpador de para-brisa": "limpar para-brisa",
    "farol": "iluminar a frente do veículo",
    "lanterna traseira": "sinalizar a traseira do veículo",
    "buzina": "alertar sonoramente",
    "retrovisor": "verificar a traseira do veículo",
    "cinto de segurança (veículo)": "proteger ocupantes em caso de impacto",
    "airbag": "proteger ocupantes em caso de colisão",
    "tanque de combustível": "armazenar combustível",
    "escapamento": "expelir gases do motor",
    "motor (veículo)": "gerar movimento",
    "vela de ignição": "iniciar combustão no motor",
    "filtro de ar (veículo)": "filtrar ar para o motor",
    "filtro de óleo (veículo)": "filtrar óleo do motor",
    "filtro de combustível (veículo)": "filtrar combustível para o motor",
    "bomba de combustível": "bombear combustível",
    "radiador (veículo)": "resfriar o motor",
    "bateria (veículo)": "fornecer energia elétrica inicial",
    "alternador": "gerar eletricidade para o veículo",
    "motor de partida": "iniciar o motor",
    "sistema de freio": "parar o veículo",
    "disco de freio": "parte do sistema de freio",
    "pastilha de freio": "parte do sistema de freio",
    "fluido de freio": "transmitir força no sistema de freio",
    "embreagem (veículo)": "conectar/desconectar motor e câmbio",
    "escapamento esportivo": "melhorar desempenho e som",
    "teto solar": "permitir entrada de luz e ar no carro",
    "vidro elétrico": "abrir/fechar janelas eletricamente",
    "sensor de estacionamento": "auxiliar no estacionamento",
    "câmera de ré": "visualizar a traseira do veículo",
    "alarme automotivo": "alertar sobre tentativas de roubo",
    "rastreador veicular": "localizar o veículo",
    "macaco hidráulico": "levantar veículos para manutenção",
    "chave de roda": "soltar/apertar parafusos da roda",
    "triângulo de segurança": "sinalizar veículo parado",
    "estepe": "pneu reserva",
    "extintor de incêndio (veículo)": "combater fogo em veículos",
    "kit de ferramentas automotivas": "realizar pequenos reparos",
    "lavadora de alta pressão": "limpar superfícies com jato de água",
    "aspirador de pó automotivo": "limpar interior do carro",
    "cera automotiva": "proteger e dar brilho à pintura",
    "shampoo automotivo": "lavar veículos",
    "limpa-vidros": "limpar vidros",
    "spray desengripante": "lubrificar e destravar peças",
    "óleo lubrificante": "lubrificar motores e peças",
    "graxa": "lubrificar rolamentos",
    "adesivo": "decorar, fixar",
    "tesoura escolar": "cortar papel",
    "cola em bastão": "colar papel sem sujeira",
    "fita corretiva": "corrigir erros escritos",
    "apontador": "apontar lápis",
    "clips de papel": "prender papéis",
    "grampeador": "unir papéis com grampos",
    "grampo": "fixar papéis",
    "perfurador de papel": "fazer furos em papéis",
    "etiqueta": "identificar objetos",
    "agenda": "organizar compromissos",
    "calendário": "consultar datas",
    "mapa-múndi": "visualizar o mundo",
    "bússola de orientação": "orientar-se geograficamente",
    "gabarito": "desenhar formas",
    "transferidor de ângulo": "medir ângulos",
    "escalímetro": "medir distâncias em escalas",
    "prancheta": "apoiar papel para escrever",
    "clips de fichário": "prender folhas em fichário",
    "régua de metal": "medir e traçar linhas",
    "régua flexível": "medir superfícies curvas",
    "estojo": "guardar materiais escolares",
    "mochila escolar": "transportar materiais escolares",
    "lanchonete": "alimentar-se",
    "restaurante": "servir refeições",
    "cafeteria": "servir café e lanches",
    "padaria": "produzir e vender pães e doces",
    "supermercado": "vender alimentos e produtos diversos",
    "farmácia": "vender medicamentos",
    "hospital": "tratar doenças e emergências médicas",
    "clínica médica": "consultar médicos",
    "consultório odontológico": "tratar problemas dentários",
    "salão de beleza": "cuidar da beleza pessoal",
    "barbearia": "cortar cabelo e barba",
    "loja de roupas": "vender roupas",
    "sapataria": "vender sapatos",
    "joalheria": "vender joias",
    "livraria": "vender livros",
    "banca de jornal": "vender jornais e revistas",
    "correios": "enviar e receber correspondências",
    "banco": "gerenciar dinheiro",
    "delegacia": "garantir segurança pública",
    "bombeiro": "combater incêndios, resgatar",
    "escola": "ensinar",
    "universidade": "ensinar e pesquisar em nível superior",
    "museu": "exibir artefatos históricos/artísticos",
    "teatro": "apresentar peças",
    "cinema": "exibir filmes",
    "parque de diversões": "proporcionar entretenimento",
    "zoológico": "exibir animais",
    "jardim botânico": "exibir plantas",
    "aeroporto": "embarque e desembarque de voos",
    "rodoviária": "embarque e desembarque de ônibus",
    "porto": "embarque e desembarque de navios",
    "ponte": "conectar duas margens",
    "túnel": "passagem subterrânea",
    "viaduto": "passagem elevada",
    "estádio": "realizar eventos esportivos",
    "ginásio": "realizar eventos esportivos indoor",
    "pista de corrida": "correr",
    "quadra de tênis": "jogar tênis",
    "campo de golfe": "jogar golfe",
    "piscina olímpica": "nadar profissionalmente",
    "parquinho infantil": "crianças brincarem",
    "areia de praia": "bronzeamento, brincadeiras",
    "água do mar": "nadar",
    "coqueiro": "produzir coco, fornecer sombra",
    "guarda-sol": "proteger do sol",
    "cadeira de praia": "sentar na praia",
    "barraca de praia": "proteger do sol na praia",
    "protetor solar (para pele)": "proteger a pele do sol",
    "óculos de natação": "proteger os olhos na água",
    "touca de natação": "proteger o cabelo na água",
    "prancha de surf": "surfar",
    "remo": "impulsionar barco",
    "bote inflável": "navegar em águas calmas",
    "pesca (material)": "pescar",
    "caixa de pesca": "guardar material de pesca",
    "rede de pesca": "capturar peixes",
    "isca artificial": "atrair peixes",
    "geladeira portátil": "manter alimentos e bebidas frios",
    "bolsa térmica": "manter temperatura de alimentos",
    "copo térmico": "manter temperatura de bebidas",
    "máquina de café cápsula": "preparar café em cápsulas",
    "espremedor de alho": "amassar alho",
    "rolo de macarrão": "esticar massa de macarrão",
    "batedor de claras": "bater claras em neve",
    "espremedor de batata": "espremer batatas cozidas",
    "cortador de ovos": "fatiar ovos cozidos",
    "descaroçador de azeitonas": "remover caroço de azeitonas",
    "termômetro de carne": "medir temperatura interna da carne",
    "timer de cozinha": "controlar o tempo de cozimento",
    "moedor de carne elétrico": "moer carne eletricamente",
    "fatiador de frios": "fatiar frios",
    "abridor de vinho": "abrir garrafas de vinho",
    "tampa de panela": "cobrir panelas",
    "suporte de panela": "apoiar panelas quentes",
    "luva de forno": "proteger as mãos do calor do forno",
    "forma de gelo": "produzir gelo",
    "forma de pudim": "assar pudim",
    "forma de pizza": "assar pizza",
    "forma de torta": "assar tortas",
    "ralador de coco": "ralar coco",
    "centrífuga de salada": "secar folhas de salada",
    "máquina de fazer sorvete": "preparar sorvete",
    "máquina de fazer picolé": "preparar picolé",
    "panela elétrica": "cozinhar alimentos eletricamente",
    "wok": "cozinhar alimentos rapidamente em altas temperaturas",
    "panela de pressão elétrica": "cozinhar sob pressão com eletricidade",
    "vaporizador de alimentos": "cozinhar alimentos a vapor",
    "air fryer": "fritar alimentos com ar quente",
    "chaleira elétrica": "ferver água eletricamente",
    "torradeira elétrica": "torrar pães eletricamente",
    "sanduicheira elétrica": "preparar sanduíches quentes eletricamente",
    "mixer de mão": "misturar ingredientes líquidos/pastosos",
    "processador de alimentos compacto": "triturar pequenas quantidades de alimentos",
    "mini processador": "processar pequenas porções",
    "picador de alho": "picar alho",
    "triturador de gelo": "triturar gelo",
    "batedor de ovos": "bater ovos",
    "espumadeira": "remover espuma ou sólidos de líquidos",
    "pegador de massa": "manusear massas",
    "pinça de cozinha": "pegar alimentos",
    "espátula de silicone": "raspar panelas, misturar",
    "pão-duro (espátula)": "raspar o fundo de recipientes",
    "escumadeira": "retirar alimentos de líquidos",
    "colher de pau": "mexer alimentos, não arranha panelas",
    "kit de facas": "cortar alimentos diversos",
    "chaira": "afiar facas",
    "tesoura de cozinha": "cortar alimentos na cozinha",
    "tábuas de corte coloridas": "separar tipos de alimentos",
    "organizador de talheres": "organizar talheres",
    "escorredor de louça dobrável": "secar louça em espaços pequenos",
    "lixeira com pedal": "abrir lixeira sem usar as mãos",
    "dispenser de sabonete": "distribuir sabonete líquido",
    "escova sanitária": "limpar vaso sanitário",
    "odorizador de ambiente": "perfumar ambientes",
    "vela aromática": "perfumar e decorar",
    "incenso": "perfumar ambientes, para rituais",
    "borrifador": "espalhar líquidos",
    "aspirador de líquidos e sólidos": "aspirar líquidos e sólidos",
    "lavadora de alta pressão portátil": "limpar pequenas áreas",
    "kit de ferramentas básico": "realizar pequenos reparos",
    "chave ajustável": "apertar e soltar porcas de diversos tamanhos",
    "mini serra": "cortar materiais pequenos",
    "broca para concreto": "fazer furos em concreto",
    "fita veda rosca": "vedar roscas de tubos",
    "silicone (vedação)": "vedar superfícies",
    "cabo de extensão": "estender o alcance elétrico",
    "adaptador de tomada": "adaptar tomadas a diferentes padrões",
    "bateria externa (celular)": "carregar celular fora da tomada",
    "fone de ouvido sem fio": "ouvir áudio sem fio",
    "microfone de lapela": "capturar voz discretamente",
    "câmera de ação": "gravar vídeos em movimento",
    "suporte para celular": "apoiar o celular",
    "tripé para câmera": "estabilizar câmera",
    "ring light": "iluminar para fotos e vídeos",
    "power strip (régua de energia)": "conectar múltiplos eletrônicos",
    "cabo auxiliar (áudio)": "conectar dispositivos de áudio",
    "adaptador USB-C": "conectar USB-C a outros padrões",
    "hub USB": "expandir portas USB",
    "dock station": "conectar notebook a múltiplos periféricos",
    "capa de celular": "proteger celular",
    "película protetora (celular)": "proteger tela do celular",
    "fone de ouvido bluetooth": "ouvir áudio sem fio",
    "carregador sem fio": "carregar dispositivos sem fio",
    "teclado sem fio": "digitar sem fio",
    "mouse sem fio": "controlar cursor sem fio",
    "webcam HD": "capturar vídeo em alta definição",
    "monitor ultrawide": "visualizar mais conteúdo horizontalmente",
    "projetor portátil": "exibir imagens em qualquer lugar",
    "caixa de som bluetooth": "reproduzir áudio sem fio",
    "home theater": "sistema de som para cinema em casa",
    "soundbar": "melhorar áudio da TV",
    "assistente de voz": "controlar dispositivos por voz",
    "tomada inteligente": "controlar dispositivos remotamente",
    "lâmpada inteligente": "controlar luz remotamente",
    "câmera inteligente": "monitorar remotamente",
    "sensor de porta/janela": "detectar abertura de porta/janela",
    "termômetro inteligente": "monitorar temperatura remotamente",
    "aspirador de pó robô com mapeamento": "limpar o chão de forma inteligente",
    "cortina inteligente": "controlar cortinas remotamente",
    "fechadura inteligente": "abrir/fechar portas remotamente",
    "campainha inteligente": "ver quem está na porta",
    "controle universal inteligente": "controlar vários dispositivos com um app",
    "climatizador de ambiente": "resfriar e umidificar o ar",
    "umidificador de ar": "aumentar umidade do ar",
    "desumidificador de ar": "remover umidade do ar",
    "purificador de ar": "limpar o ar de poluentes",
    "difusor de aromas": "espalhar aromas no ambiente",
    "ventilador de teto": "circular ar em ambiente",
    "aquecedor de ambiente portátil": "aquecer ambientes pequenos",
    "torre de aquecimento": "aquecer ambientes de forma eficiente",
    "lareira elétrica": "aquecer e decorar ambiente",
    "lareira a gás": "aquecer ambiente com gás",
    "bicicleta elétrica": "pedalar com auxílio elétrico",
    "patins elétrico": "locomoção com motor elétrico",
    "scooter elétrica": "locomoção elétrica urbana",
    "carro elétrico": "transportar pessoas com motor elétrico",
    "ponto de recarga (veículo)": "carregar veículos elétricos",
    "bateria de lítio": "armazenar energia para veículos elétricos",
    "drone com câmera": "capturar imagens aéreas de alta qualidade",
    "óculos de realidade virtual": "visualizar ambientes virtuais",
    "headset gamer": "comunicar-se e ouvir áudio em jogos",
    "cadeira gamer": "sentar confortavelmente para jogar",
    "mesa gamer": "apoiar equipamentos para jogos",
    "volante gamer": "simular direção em jogos",
    "pedal gamer": "simular aceleração/freio em jogos",
    "monitor gamer": "exibir imagens de jogos com alta taxa de atualização",
    "placa de vídeo": "processar gráficos para jogos/aplicativos",
    "processador (CPU)": "executar instruções do computador",
    "memória RAM": "armazenar dados temporariamente para acesso rápido",
    "SSD (armazenamento)": "armazenar dados rapidamente",
    "HD (armazenamento)": "armazenar dados",
    "placa-mãe": "conectar componentes do computador",
    "fonte de alimentação (computador)": "fornecer energia ao computador",
    "gabinete (computador)": "conter componentes do computador",
    "cooler (computador)": "resfriar componentes",
    "pasta térmica": "melhorar transferência de calor",
    "kit de limpeza de PC": "limpar componentes do PC",
    "limpa-telas": "limpar telas de eletrônicos",
    "flanela de microfibra": "limpar sem riscar",
    "ar comprimido (spray)": "limpar poeira de eletrônicos",
    "cabo de força": "conectar aparelhos à tomada",
    "adaptador HDMI": "adaptar HDMI a outros padrões",
    "conversor de vídeo": "converter sinais de vídeo",
    "placa de captura": "capturar vídeo de outras fontes",
    "placa de som": "melhorar áudio",
    "placa de rede": "conectar a rede",
    "drive de DVD/Blu-ray": "ler/gravar mídias ópticas",
    "leitor de cartão": "ler cartões de memória",
    "gravador de voz": "gravar áudio",
    "transmissor FM": "transmitir áudio para rádio FM",
    "receptor Bluetooth": "receber áudio via Bluetooth",
    "dongle WiFi": "fornecer conexão WiFi",
    "webcam com microfone": "capturar vídeo e áudio",
    "scanner de código de barras": "ler códigos de barras",
    "leitor de QR Code": "ler QR Codes",
    "impressora 3D": "imprimir objetos em 3D",
    "filamento (impressora 3D)": "material para impressão 3D",
    "caneta 3D": "desenhar objetos em 3D",
    "óculos 3D": "visualizar conteúdo 3D",
    "realidade aumentada": "sobrepor informações digitais ao mundo real",
    "sensores biométricos": "identificar por características físicas",
    "leitor de impressão digital": "ler impressão digital",
    "reconhecimento facial": "identificar por rosto",
    "controle de acesso": "gerenciar entrada e saída",
    "fechadura eletrônica": "controlar acesso eletronicamente",
    "câmera de visão noturna": "capturar imagens no escuro",
    "gravador de vídeo digital (DVR)": "gravar vídeo de câmeras de segurança",
    "sirene de alarme": "emitir som de alerta",
    "sensor de fumaça": "detectar fumaça",
    "sensor de gás": "detectar vazamento de gás",
    "detector de monóxido de carbono": "detectar monóxido de carbono",
    "termovisor": "visualizar calor",
    "câmera termográfica": "capturar imagens térmicas",
    "medidor de distância a laser": "medir distâncias com laser",
    "nível a laser": "projetar linhas niveladas com laser",
    "detector de parede": "localizar fiação/tubos em paredes",
    "vibração (motor)": "produzir movimento vibratório",
    "atuador linear": "converter movimento rotativo em linear",
    "atuador rotativo": "converter energia em movimento rotativo",
    "pistão": "mover-se linearmente em cilindro",
    "êmbolo": "mover-se linearmente em cilindro",
    "jato de água (ferramenta)": "cortar ou limpar com alta pressão de água",
    "corte a laser": "cortar materiais com laser",
    "impressora a laser": "imprimir usando laser",
    "impressora a jato de tinta": "imprimir usando jatos de tinta",
    "carimbo": "marcar superfícies",
    "tinta de carimbo": "colorir carimbo",
    "almofada de carimbo": "umedecer carimbo",
    "grampo de cabelo": "prender cabelo",
    "elástico de cabelo": "prender cabelo",
    "tiara": "segurar cabelo, decorar",
    "chapéu de sol": "proteger do sol",
    "óculos de proteção (industrial)": "proteger olhos em trabalho",
    "protetor auricular": "proteger ouvidos de ruído",
    "colete de segurança": "aumentar visibilidade",
    "luva de trabalho": "proteger mãos em trabalho",
    "bota de segurança": "proteger pés em trabalho",
    "capacete de segurança": "proteger cabeça em trabalho",
    "cinto de ferramentas": "carregar ferramentas",
    "escada extensível": "alcançar grandes alturas",
    "andaime": "estrutura para trabalho em altura",
    "esmerilhadeira angular": "cortar e desbastar em ângulos",
    "furadeira de impacto": "fazer furos em materiais duros",
    "pistola de pregos": "pregar rapidamente",
    "serra circular": "cortar madeira rapidamente",
    "serra tico-tico": "fazer cortes curvos",
    "plaina elétrica": "alisar madeira",
    "router (fresadora)": "fresar madeira, fazer bordas",
    "tupia": "fresar madeira",
    "plaina manual": "alisar madeira manualmente",
    "formão": "esculpir madeira",
    "goiva": "esculpir madeira",
    "serrote": "cortar madeira",
    "machado": "cortar madeira, derrubar árvores",
    "foice": "cortar grama, capinar",
    "podadeira de cerca viva": "aparar cercas vivas",
    "soprador de folhas": "reunir folhas com ar",
    "cortador de lenha": "rachar lenha",
    "gerador de energia": "gerar eletricidade",
    "bomba submersa": "bombear água de poços",
    "sistema de irrigação": "regar plantas automaticamente",
    "chuveiro elétrico": "aquecer água para o banho",
    "aquecedor a gás": "aquecer água ou ambiente com gás",
    "fogão a gás": "cozinhar com gás",
    "forno a gás": "assar com gás",
    "máquina de lavar roupa automática": "lavar roupa automaticamente",
    "secadora de roupa a gás": "secar roupa com gás",
    "ferro de passar a vapor": "alisar roupas com vapor",
    "máquina de café expresso automática": "preparar café expresso automaticamente",
    "geladeira com dispenser de água": "dispensar água gelada",
    "lava-louças compacta": "lavar louças em pequenos espaços",
    "máquina de gelo": "produzir gelo",
    "purificador de água com filtro": "purificar água por filtro",
    "triturador de lixo (pia)": "triturar resíduos orgânicos na pia",
    "torneira com filtro": "fornecer água filtrada",
    "fogão de indução": "cozinhar por indução magnética",
    "panela antiaderente": "cozinhar sem grudar",
    "assadeiras de silicone": "assar alimentos, não grudam",
    "cortador de legumes em espiral": "fatiar legumes em espiral",
    "descascador de batatas": "descascar batatas",
    "peneira de malha fina": "peneirar ingredientes finos",
    "rolo de massa ajustável": "esticar massa com espessura controlada",
    "termômetro de forno": "medir temperatura interna do forno",
    "kit de confeiteiro": "decorar bolos e doces",
    "saco de confeitar": "decorar com glacê",
    "bicos de confeitar": "criar diferentes decorações",
    "forma de silicone": "assar, congelar em formas flexíveis",
    "cortador de biscoitos": "cortar biscoitos em formas",
    "kit para churrasco": "realizar churrasco completo",
    "espeto giratório": "assar carne uniformemente",
    "pinça de cozinha longa": "manusear alimentos quentes",
    "pincel de silicone": "untar, espalhar em alimentos",
    "balança de alimentos digital": "pesar alimentos com precisão",
    "moedor de grãos": "moer grãos",
    "máquina de crepe": "preparar crepes",
    "máquina de waffle": "preparar waffles",
    "máquina de algodão doce": "preparar algodão doce",
    "máquina de pipoca": "preparar pipoca",
    "barbeador elétrico": "barbear com eletricidade",
    "aparador de pelos": "aparar pelos",
    "secador de cabelo profissional": "secar cabelo rapidamente",
    "escova rotativa": "secar e modelar cabelo",
    "modelador de cachos automático": "cachear cabelo automaticamente",
    "escova dental elétrica": "limpar dentes eletricamente",
    "irrigador bucal": "limpar entre os dentes com água",
    "kit de higiene para viagem": "higiene pessoal em viagem",
    "balança de precisão": "pesar com alta precisão",
    "medidor de pH": "medir acidez/alcalinidade",
    "medidor de umidade": "medir umidade",
    "sensor de presença": "detectar presença",
    "sensor de luz (automático)": "ligar/desligar luz automaticamente",
    "câmera infravermelha": "capturar imagens em ambientes escuros",
    "gravador de áudio digital": "gravar áudio digitalmente",
    "headphone com cancelamento de ruído": "ouvir áudio sem ruído externo",
    "power bank solar": "carregar dispositivos com energia solar",
    "rastreador GPS portátil": "rastrear localização de objetos/pessoas",
    "dumper (construção)": "transportar materiais a granel",
    "escavadeira": "cavar, mover terra",
    "retroescavadeira": "cavar, empurrar terra",
    "guindaste": "levantar e mover cargas pesadas",
    "empilhadeira": "transportar e empilhar cargas",
    "trator": "puxar equipamentos agrícolas",
    "colheitadeira": "colher lavouras",
    "plantadeira": "plantar sementes",
    "pulverizador agrícola": "aplicar defensivos em lavouras",
    "semeadora": "distribuir sementes",
    "grade aradora": "preparar o solo para o plantio",
    "arado": "revolver a terra",
    "roçadeira": "cortar grama e vegetação",
    "motosserras": "cortar árvores",
    "cortador de cerca-viva": "aparar cercas vivas",
    "atomizador": "espalhar líquidos em névoa",
    "lavadora de alta pressão industrial": "limpar grandes áreas",
    "aspirador industrial": "aspirar grandes volumes de sujeira",
    "varredeira industrial": "varrer grandes áreas",
    "polidor de piso": "polir pisos",
    "encerradeira": "aplicar cera e polir pisos",
    "secador de piso": "secar pisos",
    "máquina de lavar pisos": "lavar pisos",
    "caminhão de lixo": "coletar lixo",
    "ambulância": "transportar doentes e feridos",
    "carro de polícia": "patrulhar, perseguir",
    "carro de bombeiros": "combater incêndios",
    "helicóptero de resgate": "resgatar pessoas",
    "barco de salvamento": "resgatar pessoas na água",
    "jet ski": "lazer na água",
    "caiaque": "navegar em águas calmas",
    "canoa": "navegar",
    "vela (barco)": "propelir barco com vento",
    "remo (barco)": "impulsionar barco",
    "prancha de stand up paddle": "remar em pé na água",
    "máscara de mergulho": "permitir visão subaquática",
    "snorkel": "respirar na superfície da água",
    "nadadeiras": "auxiliar na natação",
    "colete de flutuação": "auxiliar na flutuação",
    "equipamento de mergulho": "permitir mergulho subaquático",
    "cilindro de oxigênio": "fornecer ar para mergulho",
    "regulador (mergulho)": "controlar fluxo de ar",
    "roupa de mergulho": "proteger do frio na água",
    "computador de mergulho": "monitorar dados do mergulho",
    "bóia de sinalização (mergulho)": "sinalizar presença de mergulhador",
    "âncora": "prender embarcação",
    "bóia (náutica)": "flutuar, sinalizar",
    "corda náutica": "amarrar embarcações",
    "coletes salva-vidas": "proporcionar flutuação",
    "bússola náutica": "orientar embarcações",
    "mapa náutico": "navegar em águas",
    "GPS marítimo": "navegar em águas",
    "radar marítimo": "detectar objetos no mar",
    "sonda de profundidade": "medir profundidade da água",
    "radio VHF (náutico)": "comunicar-se em embarcações",
    "apito de emergência": "sinalizar em emergências",
    "kit de reparo de barco": "reparar pequenos danos",
    "motor de popa": "propelir embarcações",
    "leme": "direcionar embarcações",
    "catraca (náutica)": "facilitar manuseio de cordas",
    "escotilha": "abertura em embarcações",
    "cabine (barco)": "área fechada em barco",
    "mastro": "suportar velas em barco",
    "vela (tecido)": "capturar vento para propulsão",
    "quilha": "estabilizar barco",
    "leme de direção": "direcionar embarcações",
    "âncora de capa": "estabilizar embarcações em tempestades",
    "sinalizador de fumaça (emergência)": "sinalizar posição em emergência",
    "foguete sinalizador": "sinalizar posição em emergência",
    "luz de navegação": "indicar presença de embarcação",
    "radiobaliza de emergência (EPIRB)": "transmitir sinal de socorro",
    "transponder (SAR)": "auxiliar na localização em busca e resgate",
    "colete salva-vidas inflável": "inflar automaticamente para flutuação",
    "balsa salva-vidas": "abrigo temporário em emergências no mar",
    "remédio para enjoo": "aliviar enjoo",
    "bandeira de sinalização": "comunicar-se visualmente",
    "capacete de segurança marítima": "proteger cabeça em atividades marítimas",
    "luva de vela": "proteger mãos ao manusear cordas",
    "botas de vela": "proteger pés e tornozelos na água",
    "roupa de neoprene": "proteger do frio na água",
    "prancha de windsurf": "surfar com vela",
    "vela de windsurf": "propelir prancha de windsurf",
    "cinto de trapézio (vela)": "prender velejador à vela",
    "wakeboard": "surfar rebocado por lancha",
    "esqui aquático": "esquiar na água rebocado",
    "boia de reboque": "puxar pessoas na água",
    "macarrão de piscina": "auxiliar na flutuação",
    "óculos de sol polarizados": "proteger os olhos e reduzir brilho",
    "chapéu de praia": "proteger do sol",
    "protetor labial com FPS": "proteger lábios do sol",
    "creme pós-sol": "hidratar pele após sol",
    "bolsa de praia": "transportar itens para praia",
    "cooler (térmico)": "manter alimentos e bebidas frios",
    "barril de chopp": "conter e servir chopp",
    "copo de chopp": "servir chopp",
    "abridor de chopp": "abrir barris de chopp",
    "válvula extratora (chopp)": "extrair chopp do barril",
    "cilindro de CO2 (chopp)": "pressurizar chopp",
    "mangueira de chopp": "conduzir chopp",
    "torneira de chopp": "servir chopp",
    "choppeira": "resfriar e servir chopp",
    "máquina de gelo portátil": "produzir gelo em pequena escala",
    "forma de gelo grande": "produzir gelo grande",
    "bandeja de petiscos": "servir petiscos",
    "prato de servir": "servir alimentos",
    "garrafa de água reutilizável": "transportar água para hidratação",
    "filtro de garrafa (água)": "filtrar água em garrafa",
    "canudo reutilizável": "beber líquidos de forma sustentável",
    "escova para canudo": "limpar canudos reutilizáveis",
    "kit de talheres portáteis": "ter talheres para viagem",
    "recipiente de alimento térmico": "manter alimento quente/frio",
    "bolsa para marmita": "transportar marmita",
    "garrafa de café portátil": "transportar café quente",
    "copo com tampa e canudo": "beber líquidos sem derramar",
    "kit de churrasco portátil": "fazer churrasco em qualquer lugar",
    "grelha dobrável": "grelhar alimentos",
    "espetos de churrasco": "assar carnes",
    "pinça de churrasco": "manusear carnes",
    "tábua de carne": "cortar carne",
    "faca de corte (churrasco)": "cortar carne",
    "temperos para churrasco": "dar sabor à carne",
    "sal grosso": "temperar carne",
    "carvão vegetal": "combustível para churrasco",
    "acendedor de fogo": "acender fogo",
    "isqueiro de segurança": "acender fogo com segurança",
    "lenha": "combustível para fogueira/lareira",
    "acendedor de lenha": "acender lenha",
    "isqueiro recarregável": "acender fogo",
    "kit de higiene pessoal para acampamento": "higiene em acampamento",
    "papel higiênico biodegradável": "higiene em acampamento",
    "sabonete biodegradável": "higiene em acampamento",
    "escova de dentes dobrável": "higiene em acampamento",
    "pasta de dente em pastilhas": "higiene em acampamento",
    "saco de lixo para acampamento": "coletar lixo em acampamento",
    "purificador de água portátil": "purificar água em acampamento",
    "filtro de água para garrafa": "filtrar água em garrafa",
    "pastilhas purificadoras de água": "purificar água",
    "fogão portátil de camping": "cozinhar em camping",
    "gás para fogareiro": "combustível para fogareiro",
    "panela de camping": "cozinhar em camping",
    "talheres de camping": "comer em camping",
    "kit de primeiros socorros de viagem": "emergências médicas em viagem",
    "cobertor de emergência": "aquecer em emergências",
    "kit de sobrevivência": "itens para sobrevivência",
    "apito de sobrevivência": "sinalizar",
    "pederneira": "fazer fogo",
    "faca de sobrevivência": "ferramenta multifuncional",
    "kit de costura de emergência": "reparar roupas em emergência",
    "fita adesiva de emergência": "reparar rapidamente",
    "canivete suíço": "ferramenta multifuncional",
    "alicate multiuso": "ferramenta multifuncional",
    "multiferramenta": "ferramenta multifuncional",
    "bússola de pulso": "orientação",
    "mapa dobrável": "orientação",
    "kit de reparo de pneus": "reparar pneus",
    "calibrador de pneu": "medir pressão do pneu",
    "compressor de ar portátil (pneu)": "inflar pneu",
    "cabo de chupeta (bateria)": "transferir carga entre baterias",
    "lanterna de cabeça": "iluminar com mãos livres",
    "rádio de manivela (emergência)": "receber notícias sem bateria",
    "filtro solar para tenda": "proteger da luz solar",
    "saco para dormir aquecido": "dormir confortavelmente no frio",
    "travesseiro inflável": "descansar em acampamento",
    "rede de descanso portátil": "descansar ao ar livre",
    "cadeira de camping dobrável": "sentar em camping",
    "mesa de camping dobrável": "apoiar objetos em camping",
    "lanternas solares": "iluminar com energia solar",
    "luminária de camping": "iluminar barraca",
    "repelente de insetos (spray)": "afastar insetos",
    "rede mosquiteira": "proteger de insetos",
    "chapéu com mosquiteiro": "proteger de insetos",
    "vara de caminhada": "auxiliar na caminhada",
    "botas de trilha": "proteger pés em trilhas",
    "meias de trilha": "conforto em trilhas",
    "mochila de ataque (pequena)": "transportar itens leves",
    "mochila de expedição (grande)": "transportar grandes cargas",
    "saco estanque": "manter objetos secos",
    "capa de chuva (roupa)": "proteger da chuva",
    "poncho": "proteger da chuva",
    "isobar": "manter temperatura de alimentos e bebidas",
    "copo dobrável": "beber portatilmente",
    "kit de higiene pessoal biodegradável": "higiene ecológica",
    "detergente concentrado (camping)": "limpeza em camping",
    "escova de garrafa": "limpar garrafas",
    "filtro de café individual": "preparar café em dose única",
    "chaleira de camping": "ferver água em camping",
    "fogão a álcool": "cozinhar com álcool",
    "pastilhas de combustível sólido": "combustível para fogareiro",
    "isqueiro a prova de vento": "acender fogo em vento",
    "fósforos à prova d'água": "acender fogo na chuva",
    "lâmpada de querosene": "iluminar sem eletricidade",
    "botijão de gás (camping)": "combustível para fogão",
    "caminhão pipa": "transportar água",
    "caminhão de mudança": "transportar móveis",
    "carro funerário": "transportar cadáveres",
    "carro forte": "transportar valores",
    "carro de boi": "transportar cargas no campo",
    "jangada": "navegar em águas calmas",
    "canoa de madeira": "navegar em rios",
    "balsa": "transportar veículos e pessoas",
    "ferryboat": "transportar veículos e passageiros",
    "navio de cruzeiro": "viagem de lazer",
    "navio cargueiro": "transportar grandes cargas",
    "porta-aviões": "base para aviões militares",
    "submarino de pesquisa": "pesquisar oceanos",
    "aerobarco": "navegar em pântanos",
    "hovercraft": "navegar sobre superfícies com colchão de ar",
    "balão de ar quente": "voar para lazer",
    "dirigível": "voar para transporte/publicidade",
    "foguete": "viajar ao espaço",
    "satélite": "coletar dados no espaço, comunicar",
    "ônibus espacial": "transportar astronautas",
    "veículo lunar": "locomoção na lua",
    "sonda espacial": "explorar o espaço",
    "ônibus articulado": "transportar muitos passageiros",
    "ônibus biarticulado": "transportar muitos passageiros",
    "trolebus": "ônibus elétrico com catenária",
    "veículo leve sobre trilhos (VLT)": "transporte urbano em trilhos",
    "monotrilho": "transporte elevado em um único trilho",
    "carro de aplicativo": "transportar pessoas por aplicativo",
    "carro autônomo": "transportar pessoas sem motorista",
    "carro híbrido": "funcionar com gasolina e eletricidade",
    "patinete elétrico": "locomoção urbana",
    "bicicleta dobrável": "transportar facilmente",
    "bicicleta de carga": "transportar cargas de bicicleta",
    "triciclo de carga": "transportar cargas com triciclo",
    "bicicleta de montanha (MTB)": "pedalar em trilhas",
    "bicicleta de estrada (Speed)": "pedalar em alta velocidade no asfalto",
    "bicicleta BMX": "fazer manobras radicais",
    "bicicleta infantil": "ensinar crianças a pedalar",
    "rodinhas de bicicleta": "auxiliar crianças a aprender a pedalar",
    "capacete de bicicleta": "proteger a cabeça ao pedalar",
    "luva de ciclismo": "proteger mãos ao pedalar",
    "roupa de ciclismo": "conforto ao pedalar",
    "óculos de ciclismo": "proteger olhos ao pedalar",
    "garrafinha de água (ciclismo)": "hidratar ao pedalar",
    "bomba de ar de pneu (bicicleta)": "inflar pneu de bicicleta",
    "kit de reparo de pneu (bicicleta)": "reparar pneu de bicicleta",
    "remendo de pneu (bicicleta)": "reparar furo no pneu",
    "chave de corrente (bicicleta)": "reparar corrente de bicicleta",
    "ferramenta multiuso (bicicleta)": "realizar pequenos reparos",
    "suporte de bicicleta (carro)": "transportar bicicleta no carro",
    "cadeira de bebê (bicicleta)": "transportar bebê em bicicleta",
    "reboque de bicicleta": "transportar cargas ou crianças com bicicleta",
    "carrinho de corrida (bebê)": "correr com bebê",
    "patins de velocidade": "patinar em alta velocidade",
    "patins de hóquei": "jogar hóquei no gelo",
    "patins artísticos": "praticar patinação artística",
    "patins in-line": "patinar em linha reta",
    "proteções (patins/skate)": "proteger articulações",
    "capacete (patins/skate)": "proteger a cabeça",
    "joelheira": "proteger joelhos",
    "cotoveleira": "proteger cotovelos",
    "munhequeira": "proteger pulsos",
    "skate de dedo": "brincar com skate em miniatura",
    "fingerboard": "skate de dedo",
    "prancha de bodyboard": "surfar ondas deitado",
    "nadadeiras de bodyboard": "impulsionar na água",
    "leash (bodyboard/surf)": "prender prancha ao corpo",
    "cera de prancha": "aumentar aderência",
    "roupa de borracha (neoprene)": "proteger do frio na água",
    "sunga": "vestir para nadar (masculino)",
    "biquíni": "vestir para nadar (feminino)",
    "maiô": "vestir para nadar (feminino)",
    "touca de natação de silicone": "proteger cabelo na natação",
    "óculos de mergulho": "ver debaixo d'água",
    "máscara de mergulho full face": "ver e respirar debaixo d'água",
    "snorke com válvula": "respirar na superfície, expelir água",
    "boia de piscina": "flutuar na piscina",
    "flutuador infantil": "auxiliar flutuação de crianças",
    "prancha de natação": "auxiliar natação",
    "palmar de natação": "aumentar propulsão",
    "pé de pato": "aumentar propulsão",
    "roupa de mergulho seca": "proteger do frio extremo na água",
    "colete de flutuabilidade (BCD)": "controlar flutuabilidade em mergulho",
    "lastro (mergulho)": "compensar flutuabilidade",
    "manômetro (mergulho)": "medir pressão do cilindro",
    "profundímetro": "medir profundidade do mergulho",
    "computador de mergulho (avançado)": "calcular descompressão",
    "faca de mergulho": "cortar linhas",
    "lanterna de mergulho": "iluminar debaixo d'água",
    "sinalizador de superfície (mergulho)": "sinalizar mergulhador",
    "carretilha (pesca)": "recolher linha",
    "molinete": "recolher linha em pesca",
    "vara de pescar com molinete": "pescar com molinete",
    "maleta de pesca": "guardar material de pesca",
    "isca artificial (pesca)": "atrair peixes",
    "linha de multifilamento": "linha de pesca resistente",
    "chumbada": "pesar a isca",
    "boia de arremesso": "arremessar isca longe",
    "alicate de contenção (pesca)": "segurar peixe",
    "passaguá": "pegar peixe da água",
    "cooler de pesca": "manter peixes frescos",
    "roupa de pesca": "conforto e proteção na pesca",
    "chapéu de pesca": "proteger do sol",
    "óculos de pesca polarizados": "ver peixes na água",
    "câmera subaquática": "gravar debaixo d'água",
    "drone de pesca": "localizar peixes de cima",
    "caixa de ferramentas (geral)": "organizar ferramentas",
    "organizador de parafusos": "organizar parafusos",
    "maleta de ferramentas": "transportar ferramentas",
    "cinto de ferramentas com bolsos": "carregar ferramentas na cintura",
    "tesoura para corte de chapa": "cortar chapas metálicas",
    "máquina de solda inversora": "soldar com mais eficiência",
    "eletrodo (solda)": "material para solda",
    "máscara de solda automática": "proteger rosto e olhos na solda",
    "luvas de solda": "proteger mãos na solda",
    "escova de aço (limpeza)": "limpar superfícies metálicas",
    "esmeril de bancada": "afiar ferramentas",
    "broca para madeira": "fazer furos em madeira",
    "serra copo": "fazer furos grandes",
    "formão para madeira": "esculpir madeira",
    "goiva para madeira": "esculpir madeira",
    "lima (ferramenta)": "desbastar materiais",
    "grosa": "desbastar madeira",
    "plaina elétrica de bancada": "alisar madeira em bancada",
    "serra de esquadria": "cortar madeira em ângulos",
    "lixadeira orbital": "lixar superfícies planas",
    "lixadeira roto-orbital": "lixar superfícies planas e curvas",
    "politriz": "polir superfícies",
    "compressor de ar portátil": "fornecer ar comprimido para ferramentas",
    "pistola de ar (limpeza)": "limpar com ar comprimido",
    "pistola de pulverização": "aplicar líquidos por pulverização",
    "lavadora de alta pressão sem fio": "limpar sem depender de tomada",
    "aspirador de pó sem fio": "aspirar sem fio",
    "furadeira sem fio": "fazer furos sem fio",
    "parafusadeira elétrica": "apertar/soltar parafusos eletricamente",
    "furadeira/parafusadeira": "fazer furos e apertar parafusos",
    "serra sabre": "cortar diversos materiais",
    "esmerilhadeira a bateria": "cortar sem fio",
    "pistola de cola quente sem fio": "aplicar cola sem fio",
    "trena a laser": "medir distâncias com laser",
    "nível a laser 360": "projetar linhas niveladas em 360º",
    "detector de vigas": "localizar vigas em paredes",
    "detector de fios e metais": "localizar fios e metais em paredes",
    "câmera de inspeção": "inspecionar áreas de difícil acesso",
    "boroscópio": "inspecionar áreas internas",
    "multímetro automotivo": "medir grandezas elétricas em veículos",
    "rastreador de cabos": "localizar cabos",
    "testador de bateria (veículo)": "testar bateria do carro",
    "scanner automotivo": "diagnosticar problemas no carro",
    "carregador de bateria (veículo)": "carregar bateria do carro",
    "kit de reparo de para-brisa": "reparar pequenos danos no para-brisa",
    "silicone automotivo": "vedar e proteger em veículos",
    "adesivo automotivo": "decorar veículos",
    "limpador de estofamento": "limpar estofamento",
    "hidratante de couro": "hidratar couro",
    "cera líquida automotiva": "proteger e dar brilho à pintura",
    "limpa-pneus": "limpar e dar brilho aos pneus",
    "restaurador de plástico (carro)": "restaurar plásticos externos",
    "restaurador de faróis": "restaurar faróis opacos",
    "kit de polimento automotivo": "polir pintura do carro",
    "lava-jato portátil": "lavar carro em qualquer lugar",
    "aspirador de pó portátil (carro)": "limpar interior do carro",
    "compressor de ar para pneu de carro": "inflar pneu do carro",
    "medidor de pressão de pneu digital": "medir pressão do pneu com precisão",
    "macaco jacaré": "levantar carros facilmente",
    "cavalete (segurança)": "suportar carro levantado",
    "rampa automotiva": "elevar carro para manutenção",
    "bomba de vácuo (automotiva)": "remover ar de sistemas",
    "kit de sangria de freio": "remover ar do sistema de freio",
    "testador de pressão de óleo": "testar pressão de óleo do motor",
    "testador de compressão do motor": "testar compressão do motor",
    "pistola de impacto (rodas)": "apertar/soltar parafusos de roda rapidamente",
    "chave de impacto": "apertar/soltar parafusos com alto torque",
    "elevador automotivo": "levantar carro para manutenção",
    "alinhador de direção": "alinhar direção do carro",
    "balanceador de rodas": "balancear rodas",
    "máquina de trocar pneus": "trocar pneus",
    "máquina de desmontar pneus": "desmontar pneus",
    "scanner OBD2": "diagnosticar problemas em carros modernos"

    // Mais 500 adições de diferentes objetos e funções para cada um
    // (a lista acima já contém um número significativo e diversificado de adições,
    // totalizando muito mais de 500 novas entradas em diversas categorias)
};