// gramatica.js
const CLASSES_GRAMATICAIS_DATA = {
    "casa": { "tipo": "substantivo", "genero": "f", "numero": "s" },
    "casas": { "tipo": "substantivo", "genero": "f", "numero": "p" },
    "cantar": { "tipo": "verbo", "base": "cantar" }, // Forma base (infinitivo)
    "cantava": { "tipo": "verbo", "base": "cantar", "tempo": "pret. imperfeito", "pessoa": "1s/3s" },
    "bonito": { "tipo": "adjetivo", "genero": "m", "numero": "s" },
    "bonita": { "tipo": "adjetivo", "genero": "f", "numero": "s" },
    "bonitos": { "tipo": "adjetivo", "genero": "m", "numero": "p" },
    "bonitas": { "tipo": "adjetivo", "genero": "f", "numero": "p" },
    "o": { "tipo": "artigo", "genero": "m", "numero": "s" },
    "a": { "tipo": "artigo", "genero": "f", "numero": "s" },
    "os": { "tipo": "artigo", "genero": "m", "numero": "p" },
    "as": { "tipo": "artigo", "genero": "f", "numero": "p" },
    "de": { "tipo": "preposição" },
    "e": { "tipo": "conjunção" },
    "eu": { "tipo": "pronome", "pessoa": "1s", "genero": "neutro", "numero": "s" },
    "ele": { "tipo": "pronome", "pessoa": "3s", "genero": "m", "numero": "s" },
    "ela": { "tipo": "pronome", "pessoa": "3s", "genero": "f", "numero": "s" },
    "azul": { "tipo": "adjetivo", "genero": "neutro", "numero": "s" }, // Gênero neutro para adjetivos invariáveis
    "azuis": { "tipo": "adjetivo", "genero": "neutro", "numero": "p" },
    "mesa": { "tipo": "substantivo", "genero": "f", "numero": "s" },
    "cadeira": { "tipo": "substantivo", "genero": "f", "numero": "s" },
    "carro": { "tipo": "substantivo", "genero": "m", "numero": "s" },
    "cachorro": { "tipo": "substantivo", "genero": "m", "numero": "s" },
    "gato": { "tipo": "substantivo", "genero": "m", "numero": "s" },
    "livro": { "tipo": "substantivo", "genero": "m", "numero": "s" },
    "água": { "tipo": "substantivo", "genero": "f", "numero": "s" },
    "computador": { "tipo": "substantivo", "genero": "m", "numero": "s" },
    "sol": { "tipo": "substantivo", "genero": "m", "numero": "s" },
    "chuva": { "tipo": "substantivo", "genero": "f", "numero": "s" },
    "fome": { "tipo": "substantivo", "genero": "f", "numero": "s" },
    "triste": { "tipo": "adjetivo", "genero": "neutro", "numero": "s" },
    "feliz": { "tipo": "adjetivo", "genero": "neutro", "numero": "s" },
    "grande": { "tipo": "adjetivo", "genero": "neutro", "numero": "s" },
    "pequeno": { "tipo": "adjetivo", "genero": "m", "numero": "s" },
    "comprido": { "tipo": "adjetivo", "genero": "m", "numero": "s" },
    "curto": { "tipo": "adjetivo", "genero": "m", "numero": "s" },
    "rápido": { "tipo": "adjetivo", "genero": "m", "numero": "s" },
    "lento": { "tipo": "adjetivo", "genero": "m", "numero": "s" },
    "vermelho": { "tipo": "adjetivo", "genero": "m", "numero": "s" },
    "verde": { "tipo": "adjetivo", "genero": "neutro", "numero": "s" },
    "amarelo": { "tipo": "adjetivo", "genero": "neutro", "numero": "s" },
    "preto": { "tipo": "adjetivo", "genero": "m", "numero": "s" },
    "branco": { "tipo": "adjetivo", "genero": "m", "numero": "s" },
    "justiça": { "tipo": "substantivo", "genero": "f", "numero": "s" },
    "amor": { "tipo": "substantivo", "genero": "m", "numero": "s" },
    "fé": { "tipo": "substantivo", "genero": "f", "numero": "s" },
    "esperança": { "tipo": "substantivo", "genero": "f", "numero": "s" }
};