// sentimento.js

/**
 * @file Dicionário de termos associados a sentimentos em Português do Brasil.
 * Mapeia palavras-chave para uma categoria de sentimento (positivo, negativo, neutro).
 * Esta lista é abrangente e pode ser utilizada para análise de sentimentos em textos.
 * @author [Seu Nome ou Nome da Organização]
 * @version 1.0.0
 */

const SENTIMENTO_DATA = {
    // --- Palavras Positivas ---
    "bom": "positivo", "ótimo": "positivo", "excelente": "positivo", "feliz": "positivo",
    "alegre": "positivo", "amor": "positivo", "paz": "positivo", "lindo": "positivo",
    "maravilhoso": "positivo", "incrível": "positivo", "agradável": "positivo",
    "divertido": "positivo", "legal": "positivo", "perfeito": "positivo",
    "sucesso": "positivo", "ganhar": "positivo", "conquista": "positivo",
    "melhor": "positivo", "sorte": "positivo", "esperança": "positivo",
    "confiança": "positivo", "prazer": "positivo", "satisfeito": "positivo",
    "gratidão": "positivo", "entusiasmo": "positivo", "admiração": "positivo",
    "alívio": "positivo", "apreciação": "positivo", "bem-estar": "positivo",
    "brilhante": "positivo", "calmo": "positivo", "carinho": "positivo",
    "celebração": "positivo", "comemoração": "positivo", "conforto": "positivo",
    "crescimento": "positivo", "cuidado": "positivo", "curiosidade": "positivo",
    "dedicação": "positivo", "desejo": "positivo", "determinação": "positivo",
    "dignidade": "positivo", "êxito": "positivo", "eficaz": "positivo",
    "eficiência": "positivo", "empolgação": "positivo", "encanto": "positivo",
    "energia": "positivo", "equilíbrio": "positivo", "estima": "positivo",
    "euforia": "positivo", "excelência": "positivo", "expansão": "positivo",
    "fabuloso": "positivo", "fantástico": "positivo", "fascinante": "positivo",
    "favorável": "positivo", "felicidade": "positivo", "firmeza": "positivo",
    "florir": "positivo", "força": "positivo", "fraternidade": "positivo",
    "generosidade": "positivo", "gentileza": "positivo", "glória": "positivo",
    "harmonia": "positivo", "honestidade": "positivo", "honra": "positivo",
    "iluminação": "positivo", "inspiração": "positivo", "inteligência": "positivo",
    "interesse": "positivo", "júbilo": "positivo", "justiça": "positivo",
    "liberdade": "positivo", "lucidez": "positivo", "luz": "positivo",
    "maturidade": "positivo", "memorável": "positivo", "merecimento": "positivo",
    "motivação": "positivo", "nobreza": "positivo", "otimismo": "positivo",
    "paixão": "positivo", "perseverança": "positivo", "positividade": "positivo",
    "prosperidade": "positivo", "realização": "positivo", "recompensa": "positivo",
    "refrescante": "positivo", "respeito": "positivo", "satisfação": "positivo",
    "segurança": "positivo", "serenidade": "positivo", "simpatia": "positivo",
    "sinceridade": "positivo", "solidariedade": "positivo", "sossego": "positivo",
    "superação": "positivo", "surpreendente": "positivo", "ternura": "positivo",
    "tranquilidade": "positivo", "união": "positivo", "valor": "positivo",
    "ventura": "positivo", "vitalidade": "positivo", "vitória": "positivo",
    "vitorioso": "positivo", "sabedoria": "positivo", "lealdade": "positivo",
    "confiável": "positivo", "proteção": "positivo", "amizade": "positivo",
    "apoio": "positivo", "reconciliação": "positivo", "inovação": "positivo",
    "progresso": "positivo", "gratificante": "positivo", "fascinante": "positivo",
    "radiante": "positivo", "promissor": "positivo", "benéfico": "positivo",
    "exuberante": "positivo", "magnífico": "positivo", "esplêndido": "positivo",
    "brilhantismo": "positivo", "perseverante": "positivo", "resiliente": "positivo",
    "compreensão": "positivo", "empatia": "positivo", "colaboração": "positivo",
    "compaixão": "positivo", "gratificante": "positivo", "edificante": "positivo",
    "inspirador": "positivo", "revigorante": "positivo", "zelo": "positivo",
    "efusão": "positivo", "êxtase": "positivo", "jubiloso": "positivo",
    "contente": "positivo", "deleite": "positivo", "êxito": "positivo",
    "gostoso": "positivo", "agradável": "positivo", "lazer": "positivo",
    "deslumbrante": "positivo", "refinado": "positivo", "saboroso": "positivo",

    // --- Palavras Negativas ---
    "ruim": "negativo", "mau": "negativo", "triste": "negativo", "chateado": "negativo",
    "problema": "negativo", "erro": "negativo", "medo": "negativo", "raiva": "negativo",
    "ódio": "negativo", "horrível": "negativo", "péssimo": "negativo",
    "difícil": "negativo", "perder": "negativo", "fracasso": "negativo",
    "pior": "negativo", "doença": "negativo", "dor": "negativo",
    "sofrimento": "negativo", "ansiedade": "negativo", "preocupação": "negativo",
    "falso": "negativo", "mentira": "negativo", "desagradável": "negativo",
    "chato": "negativo", "tédio": "negativo", "culpa": "negativo",
    "aborrecido": "negativo", "amargura": "negativo", "angústia": "negativo",
    "apatia": "negativo", "apreensão": "negativo", "arrogância": "negativo",
    "assustado": "negativo", "atroz": "negativo", "aversão": "negativo",
    "burrice": "negativo", "cansaço": "negativo", "caos": "negativo",
    "choque": "negativo", "ciúme": "negativo", "complexo": "negativo", // No sentido de dificuldade
    "condenação": "negativo", "conflito": "negativo", "confusão": "negativo",
    "consternação": "negativo", "contaminação": "negativo", "crise": "negativo",
    "crueldade": "negativo", "culpa": "negativo", "decepção": "negativo",
    "defeito": "negativo", "demora": "negativo", "depressão": "negativo",
    "derrota": "negativo", "desacordo": "negativo", "desânimo": "negativo",
    "desastre": "negativo", "desconfiança": "negativo", "descontentamento": "negativo",
    "descontrole": "negativo", "desespero": "negativo", "desgosto": "negativo",
    "desgraça": "negativo", "desilusão": "negativo", "desonestidade": "negativo",
    "desperdício": "negativo", "desprazer": "negativo", "destruição": "negativo",
    "dificuldade": "negativo", "discórdia": "negativo", "doente": "negativo",
    "doloroso": "negativo", "enfado": "negativo", "engano": "negativo",
    "escassez": "negativo", "escuridão": "negativo", "estresse": "negativo",
    "falha": "negativo", "fobia": "negativo", "fragilidade": "negativo",
    "fúria": "negativo", "hostilidade": "negativo", "ignominia": "negativo",
    "ignorância": "negativo", "ilegal": "negativo", "impedimento": "negativo",
    "impaciência": "negativo", "incompetência": "negativo", "injustiça": "negativo",
    "inimigo": "negativo", "inquietude": "negativo", "insatisfação": "negativo",
    "insegurança": "negativo", "insucesso": "negativo", "irritação": "negativo",
    "isolamento": "negativo", "luto": "negativo", "mágoa": "negativo",
    "mediocridade": "negativo", "melancolia": "negativo", "miséria": "negativo",
    "monotonia": "negativo", "morte": "negativo", "negligência": "negativo",
    "nervosismo": "negativo", "nojo": "negativo", "obscuridade": "negativo",
    "pânico": "negativo", "perigo": "negativo", "preconceito": "negativo",
    "pressão": "negativo", "punição": "negativo", "rejeição": "negativo",
    "ressentimento": "negativo", "revolta": "negativo", "risco": "negativo",
    "sacrifício": "negativo", "solidão": "negativo", "sufoco": "negativo",
    "terror": "negativo", "traição": "negativo", "trágico": "negativo",
    "vazio": "negativo", "vergonha": "negativo", "violência": "negativo",
    "vulnerabilidade": "negativo", "zanga": "negativo", "deprimente": "negativo",
    "pavor": "negativo", "hostil": "negativo", "desamparo": "negativo",
    "opressor": "negativo", "problemático": "negativo", "desespero": "negativo",
    "infelicidade": "negativo", "desgosto": "negativo", "agonizar": "negativo",
    "aflito": "negativo", "cansativo": "negativo", "desorientado": "negativo",
    "perturbador": "negativo", "ruído": "negativo", "obsceno": "negativo",
    "sombrio": "negativo", "incômodo": "negativo", "irritante": "negativo",
    "inconveniente": "negativo", "danoso": "negativo", "prejudicial": "negativo",
    "terrível": "negativo", "desespero": "negativo", "abatido": "negativo",
    "carrancudo": "negativo", "desolado": "negativo", "frustrado": "negativo",
    "indignado": "negativo", "melancólico": "negativo", "miséria": "negativo",
    "oprimido": "negativo", "pessimista": "negativo", "revoltado": "negativo",
    "temeroso": "negativo", "vexame": "negativo", "vitimado": "negativo",
    "desconforto": "negativo", "amargo": "negativo", "azedo": "negativo",
    "pesadelo": "negativo", "arrependimento": "negativo", "nostalgia": "negativo", // Pode ser neutro/negativo
    "melindroso": "negativo", "suspeito": "negativo", "dolorido": "negativo",
    "mortificado": "negativo", "esgotado": "negativo", "atormentado": "negativo",
    "consternado": "negativo", "desanimado": "negativo", "abatimento": "negativo",
    "irritadiço": "negativo", "desprezo": "negativo", "inveja": "negativo",
    "ciúmes": "negativo", "ressaca": "negativo", "amargurado": "negativo",
    "pesar": "negativo", "remorso": "negativo", "piedade": "negativo",
    "desolação": "negativo", "desilusão": "negativo", "pesaroso": "negativo",
    "desgostoso": "negativo", "afligido": "negativo", "desacreditado": "negativo",
    "estressado": "negativo", "abatido": "negativo", "desesperado": "negativo",
    "nervoso": "negativo", "desamparado": "negativo", "abatido": "negativo",

    // --- Palavras Neutras ---
    "casa": "neutro", "mesa": "neutro", "carro": "neutro", "água": "neutro",
    "computador": "neutro", "livro": "neutro", "caneta": "neutro", "azul": "neutro",
    "árvore": "neutro", "nuvem": "neutro", "telefone": "neutro", "cadeira": "neutro",
    "porta": "neutro", "janela": "neutro", "parede": "neutro", "chão": "neutro",
    "céu": "neutro", "sol": "neutro", "lua": "neutro", "estrela": "neutro",
    "tempo": "neutro", "dia": "neutro", "noite": "neutro", "semana": "neutro",
    "mês": "neutro", "ano": "neutro", "hora": "neutro", "minuto": "neutro",
    "segundo": "neutro", "cidade": "neutro", "país": "neutro", "mundo": "neutro",
    "pessoa": "neutro", "animal": "neutro", "planta": "neutro", "objeto": "neutro",
    "ideia": "neutro", "fato": "neutro", "informação": "neutro", "dado": "neutro",
    "cor": "neutro", "forma": "neutro", "tamanho": "neutro", "peso": "neutro",
    "altura": "neutro", "largura": "neutro", "profundidade": "neutro", "quantidade": "neutro",
    "número": "neutro", "letra": "neutro", "palavra": "neutro", "frase": "neutro",
    "texto": "neutro", "som": "neutro", "luz": "neutro", "vento": "neutro",
    "chuva": "neutro", "terra": "neutro", "pedra": "neutro", "metal": "neutro",
    "plástico": "neutro", "vidro": "neutro", "madeira": "neutro", "papel": "neutro",
    "tecido": "neutro", "roupa": "neutro", "comida": "neutro", "bebida": "neutro",
    "caminho": "neutro", "rua": "neutro", "estrada": "neutro", "ponte": "neutro",
    "montanha": "neutro", "rio": "neutro", "lago": "neutro", "oceano": "neutro",
    "praia": "neutro", "floresta": "neutro", "deserto": "neutro", "vale": "neutro",
    "campo": "neutro", "ar": "neutro", "fogo": "neutro", "energia": "neutro",
    "sistema": "neutro", "processo": "neutro", "função": "neutro", "operação": "neutro",
    "resultado": "neutro", "causa": "neutro", "efeito": "neutro", "solução": "neutro",
    "problema": "neutro", "pergunta": "neutro", "resposta": "neutro", "opinião": "neutro",
    "argumento": "neutro", "exemplo": "neutro", "detalhe": "neutro", "método": "neutro",
    "técnica": "neutro", "ferramenta": "neutro", "máquina": "neutro", "dispositivo": "neutro",
    "programa": "neutro", "aplicativo": "neutro", "site": "neutro", "internet": "neutro",
    "dicionário": "neutro", "base de dados": "neutro", "arquivo": "neutro", "pasta": "neutro",
    "documento": "neutro", "relatório": "neutro", "estudo": "neutro", "pesquisa": "neutro",
    "projeto": "neutro", "plano": "neutro", "meta": "neutro", "objetivo": "neutro",
    "desafio": "neutro", "oportunidade": "neutro", "decisão": "neutro", "escolha": "neutro",
    "mudança": "neutro", "crescimento": "neutro", "desenvolvimento": "neutro", "evolução": "neutro",
    "história": "neutro", "cultura": "neutro", "sociedade": "neutro", "economia": "neutro",
    "política": "neutro", "ciência": "neutro", "arte": "neutro", "música": "neutro",
    "filme": "neutro", "livro": "neutro", "jornal": "neutro", "revista": "neutro",
    "esporte": "neutro", "jogo": "neutro", "brinquedo": "neutro", "escola": "neutro",
    "universidade": "neutro", "trabalho": "neutro", "profissão": "neutro", "negócio": "neutro",
    "empresa": "neutro", "mercado": "neutro", "venda": "neutro", "compra": "neutro",
    "dinheiro": "neutro", "recurso": "neutro", "material": "neutro", "equipamento": "neutro",
    "estrutura": "neutro", "forma": "neutro", "local": "neutro", "área": "neutro",
    "região": "neutro", "ponto": "neutro", "linha": "neutro", "círculo": "neutro",
    "quadrado": "neutro", "triângulo": "neutro", "ângulo": "neutro", "curva": "neutro",
    "reta": "neutro", "superfície": "neutro", "volume": "neutro", "distância": "neutro",
    "velocidade": "neutro", "força": "neutro", "pressão": "neutro", "temperatura": "neutro",
    "lugar": "neutro", "evento": "neutro", "ocorrência": "neutro", "situação": "neutro",
    "condição": "neutro", "estado": "neutro", "processo": "neutro", "fluxo": "neutro",
    "momento": "neutro", "período": "neutro", "ciclo": "neutro", "tendência": "neutro",
    "padrão": "neutro", "exceção": "neutro", "regra": "neutro", "lei": "neutro",
    "princípio": "neutro", "base": "neutro", "fundamento": "neutro", "teoria": "neutro",
    "conceito": "neutro", "ideia": "neutro", "pensamento": "neutro", "raciocínio": "neutro",
    "conhecimento": "neutro", "aprendizagem": "neutro", "educação": "neutro", "habilidade": "neutro",
    "capacidade": "neutro", "talento": "neutro", "experiência": "neutro", "prática": "neutro",
    "teoria": "neutro", "dúvida": "neutro", "questionamento": "neutro", "conversa": "neutro",
    "discurso": "neutro", "diálogo": "neutro", "comunicação": "neutro", "informação": "neutro",
    "notícia": "neutro", "mensagem": "neutro", "carta": "neutro", "e-mail": "neutro",
    "telefone": "neutro", "reunião": "neutro", "apresentação": "neutro", "aula": "neutro",
    "curso": "neutro", "disciplina": "neutro", "matéria": "neutro", "exercício": "neutro",
    "teste": "neutro", "exame": "neutro", "avaliação": "neutro", "resultado": "neutro",
    "análise": "neutro", "síntese": "neutro", "pesquisa": "neutro", "descoberta": "neutro",
    "invenção": "neutro", "criação": "neutro", "produção": "neutro", "fabricação": "neutro",
    "construção": "neutro", "montagem": "neutro", "reparação": "neutro", "manutenção": "neutro",
    "uso": "neutro", "aplicação": "neutro", "função": "neutro", "utilidade": "neutro",
    "finalidade": "neutro", "propósito": "neutro", "objetivo": "neutro", "meta": "neutro",
    "plano": "neutro", "estratégia": "neutro", "tática": "neutro", "ação": "neutro",
    "movimento": "neutro", "caminhada": "neutro", "viagem": "neutro", "transporte": "neutro",
    "velocidade": "neutro", "distância": "neutro", "direção": "neutro", "sentido": "neutro",
    "posição": "neutro", "localização": "neutro", "mapa": "neutro", "rota": "neutro",
    "guia": "neutro", "sinal": "neutro", "código": "neutro", "símbolo": "neutro",
    "identidade": "neutro", "nome": "neutro", "título": "neutro", "tipo": "neutro",
    "categoria": "neutro", "grupo": "neutro", "membro": "neutro", "parte": "neutro",
    "todo": "neutro", "fragmento": "neutro", "elemento": "neutro", "componente": "neutro",
    "estrutura": "neutro", "organização": "neutro", "sistema": "neutro", "rede": "neutro",
    "conexão": "neutro", "relação": "neutro", "vínculo": "neutro", "ligação": "neutro",
    "junção": "neutro", "separação": "neutro", "divisão": "neutro", "distinção": "neutro",
    "diferença": "neutro", "similaridade": "neutro", "semelhança": "neutro", "contraste": "neutro",
    "oposição": "neutro", "equivalência": "neutro", "igualdade": "neutro", "desigualdade": "neutro",
    "equilíbrio": "neutro", "desequilíbrio": "neutro", "simetria": "neutro", "assimetria": "neutro"
};